### ISSUE TITLE
Can't trigger Jenkins except with button

### ISSUE THREAD

**Issue by zcsongor** [tomasbjerre/pull-request-notifier-for-bitbucket#100]
Hi!

I really do not know what am I missing here... triggering Jenkins with button is working, but when I create/update/approve/decline a PR, nothing happens despite the fact that all of these are checked in the settings. Any idea?

Thanks!

**Comment by tomasbjerre** [comment]
Do you have a filter string or regexp?

**Comment by zcsongor** [comment]
Yes, for the button, that's what I have:
![capture](https://cloud.githubusercontent.com/assets/11615844/13327820/c5770a14-dbeb-11e5-8005-f8dd0d80b9ff.PNG)

Tried w/o button. no success.

**Comment by zcsongor** [comment]
Oh, snap, deleted the button again, created a PR and triggered my build! So this is not an OR? I have to create a trigger for the button and another one for PR actions?

**Comment by tomasbjerre** [comment]
What you want is probably to remove the filter. Now the filter sais only to
trigger on buttons and only if the name of that button is "trigger jenkins".
Den 25 feb 2016 18:15 skrev "zcsongor" <notifications@github.com>:

**Comment by zcsongor** [comment]
Thanks! I'll create several triggers from now on. Big up, great work!
