### ISSUE TITLE
Capability to support different jenkins servers for different repos

### ISSUE THREAD

**Issue by rajeshgupthar** [tomasbjerre/pull-request-notifier-for-bitbucket#101]
Hi,
We use Stash server in an enterprise setup. Where we have multiple teams creating their own repos with  specific settings for each repo. We also have different jenkins servers used by each team. 
Our team has decided to mandate PRs on our repo and would like to validate the PR before approving it. This validation shall happen on jenkins servers specific to our team. It is possible that other teams might want to integrate their repos with their own jenkins servers. 
For our requirement, this plugin seems to be the only solution, but lacking the capability to support different jenkins servers for different repos. 
Could you suggest a way out for us to use this plugin? Or if you are aware of another plugin that shall help us to achieve the same, we would be more than glad to use it.

**Comment by tomasbjerre** [comment]
It is supported. Using the *filter string* and *filter regexp*.
You may want to put ${PULL_REQUEST_TO_REPO_SLUG} in the filter string field and "rep_1" in filter regexp.

You can add another notification, for another Jenkins instance, perhaps also with ${PULL_REQUEST_TO_REPO_SLUG} as filter string but maby "rep_2" as filter string.
