### ISSUE TITLE
Q: Any issues with using quotes around variables?

### ISSUE THREAD

**Issue by carlmot** [tomasbjerre/pull-request-notifier-for-bitbucket#102]
Have 3 instances of Bitbucket (4.0.1). 2 have version 2.15 of this plugin, one has 2.12.
Configured the plugin to used quotes around the comment var (e.g. "${PULL_REQUEST_COMMENT_TEXT}").
The instance using 2.12 has no issues with the quotes, but both instances using 2.15 do not work.
It produces an error in the atlassian-bitbucket.log file and it references the first instance of the quote (e.g. ava.lang.RuntimeException: java.net.URISyntaxException: Illegal character in query at index 337:).

**Comment by tomasbjerre** [comment]
I would suggest you replace the quotes with `%22`.

**Comment by carlmot** [comment]
Using the encoding works, thanks. Just wondering if this was something in my env. or it was a change in the plugin.
