### ISSUE TITLE
Support Bitbucket Server 4.4

### ISSUE THREAD

**Issue by itay** [tomasbjerre/pull-request-notifier-for-bitbucket#103]
@tomasbjerre looks like the 4.4 release is out, with some API/UI changes that will likely require reworking some of the plugin:

https://developer.atlassian.com/bitbucket/server/docs/latest/reference/api-changelog.html#Bitbucket_Server_4.4

Do you have any idea when support for 4.4 might happen?

**Comment by tomasbjerre** [comment]
I can have a look later today

**Comment by fredrikand** [comment]
We are already running 4.4, and the buttons work already . They get "hidden" under the "..." menu and Actions.

Feedback from our users is that the Actions menu is one menu to much. But, it works :-)

![image](https://cloud.githubusercontent.com/assets/13114156/13461850/7484557e-e084-11e5-9c85-e1d2998ee6a6.png)

**Comment by tomasbjerre** [comment]
Looks like this for me:
![skarmbild fran 2016-03-02 18 06 58](https://cloud.githubusercontent.com/assets/439571/13468134/99c90010-e0a1-11e5-976c-c598aae35ce7.png)

I think there is work to do here, but it can wait. Unless someone submits a PR for it =)
