### ISSUE TITLE
Don't log Authorization header value

### ISSUE THREAD

**Issue by benhumphreys** [tomasbjerre/pull-request-notifier-for-bitbucket#106]
In `UrlInvoker` any added headers are logged. This can result in passwords being logged in the case of basic auth since the value is just a Base64 encoded `<username>:<password>`

There is the risk that credentials could be leaked in the case overly permissive read access is granted to log files. Or if the logs files are sent to a third party log management or analysis service.

Best to either remove this header logging, or if it is deemed useful to at least sanitise the value for the Authorization field.

**Comment by tomasbjerre** [comment]
This is now in 2.16, open issue again if any problems!
