### ISSUE TITLE
java.lang.NullPointerException: null at PrnfbRenderer.java:367

### ISSUE THREAD

**Issue by jcurley** [tomasbjerre/pull-request-notifier-for-bitbucket#107]
Hello,

Some users are not able to trigger a Jenkins build, using the PRNFB add-on. It works for others. Unfortunately, it does not work for the primary user and a few others.

- Bitbucket 4.4.1.
- PRNFB 2.16.
- openjdk version "1.8.0_71"

The full Invoke URL is:

http://vxjenkins.wrs.com:8080/job/vx7_test_launcher/buildWithParameters?VX7_BRANCH=${PULL_REQUEST_FROM_BRANCH}&COMPLETION_MAIL_LIST=${PULL_REQUEST_USER_EMAIL_ADDRESS}&FROM_REPO=${PULL_REQUEST_FROM_REPO_NAME}

I attached pictures of the configuration settings for the trigger button and the java stack trace (text file).

Let me know if you need additional information.
Thank you for any suggestions or fixes. 

---

![prfnb-top](https://cloud.githubusercontent.com/assets/8205076/14223391/f9da49c4-f833-11e5-8b7a-3789a61fdf57.jpg)

![prfnb-bottom](https://cloud.githubusercontent.com/assets/8205076/14223395/0a737184-f834-11e5-8354-3923c9d2115e.jpg)

[prnfb-java-trace.txt](https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/files/200605/prnfb-java-trace.txt)

**Comment by tomasbjerre** [comment]
I asked a question [here](https://answers.atlassian.com/questions/38067912/get-applicationuser-instance-from-inside-servlet).

**Comment by tomasbjerre** [comment]
I just released 2.17. Should be fixed.

**Comment by jcurley** [comment]
Hi Tomas,

Thank you * 2. I installed the update. I will have to wait until Monday, for the user to try it.

**Comment by jcurley** [comment]
Problem fixed. Thank you for the fast service.

Best regards,
John
