### ISSUE TITLE
Jenkins is triggered commits to master when a pull request is open

### ISSUE THREAD

**Issue by mdio** [tomasbjerre/pull-request-notifier-for-bitbucket#108]
Hi. Thanks for making this functionality available for Bitbucket Server!

We're using Bitbucket Server v4.4.1 together with Version 2.17 of your plugin (I think... installed it a few days ago from the marketplace).

We have one trigger:
**Filter string:** ${PULL_REQUEST_TO_REPO_PROJECT_KEY}
**Filter regexp:** MO
**Triggers apply:** To PRs without merge conflicts
**Triggers do not apply to:** Merged PRs, Declined PRs
**Triggers:** OPENED, REOPENED, RESCOPED_FROM, RESCOPED_TO
**Invoke URL:** https://our.jenkins:8080/git/notifyCommit?url=${PULL_REQUEST_TO_SSH_CLONE_URL}&branches=pr/${PULL_REQUEST_TO_BRANCH}&sha1=${PULL_REQUEST_FROM_HASH}&PULL_REQUEST_URL=${PULL_REQUEST_URL}&PULL_REQUEST_ID=${PULL_REQUEST_ID}
**HTTP method:** GET

(Btw: I followed [this blog post](https://christiangalsterer.wordpress.com/2015/04/23/continuous-integration-for-pull-requests-with-jenkins-and-stash/))

So what I noticed was: 
- When no pull requests are open and I commit to master: nothing happens
- When one pull request is open and I commit to master: Jenkins is triggered for the commit in master but ${PULL_REQUEST_ID} contains the ID of the open pull request.

I believe that this should not happen and it's also very inconvenient for us.

The notifications for pull requests are working as expected.

**Comment by tomasbjerre** [comment]
What you are saying is that you dont want to trigger the job when commits are added to master?

If so, and if your pr are targeting master, dont check rescoped_to. Rescoped_from means it will trigger for changes on the source branch.

**Comment by mdio** [comment]
Thank you for your quick response.
Now that you explain it, it also makes sense to me.

This happens for the case that the commit to master changed something that breaks something in the pull request.
