### ISSUE TITLE
PULL_REQUEST_TO_HASH resolved to old commit

### ISSUE THREAD

**Issue by nwsheppard** [tomasbjerre/pull-request-notifier-for-bitbucket#117]
The PULL_REQUEST_TO_HASH is pulling to old hash of the repository the commit is going.  Shouldn't this pull the latest hash from the repository?

**Comment by tomasbjerre** [comment]
What do you mean with the old hash? The original hash that was when the PR was opened? It should point to the latest hash of the target branch of the PR.

**Comment by nwsheppard** [comment]
Yes, it points to the hash from when the PR was created.  There could have been 3 other commits since then and it does not see them.

**Comment by tomasbjerre** [comment]
I created a PR.
Added URL as: http://localhost:80/?FROM=${PULL_REQUEST_FROM_HASH}&TO=${PULL_REQUEST_TO_HASH}
Triggered on COMMENT
Added comment
got:
/?FROM=d6edcbf924697ab811a867421dab60d954ccad99&TO=0a943a29376f2336b78312d99e65da17048951db
Cloned repo
committed to target
added comment
got: 
/?FROM=d6edcbf924697ab811a867421dab60d954ccad99&TO=3f279e9c18432e315e2ff8d721e8614eaf9c8edc

What is the event you are triggering on?

**Comment by nwsheppard** [comment]
I am triggering on Button_Trigger.

**Comment by tomasbjerre** [comment]
I tried with RESCOPED_FROM and RESCOPED_TO and also with BUTTON_TRIGGER. All works fine for me. Are the PR within the same repo or forked?

**Comment by nwsheppard** [comment]
They are within the same repo.

**Comment by nwsheppard** [comment]
Is there a way to get the last Merge_Commit from the "to" branch.  The issue is that sometimes Jenkins will not get the commit notification and we have to manually rebuild the merge, but without being able to use the Merge_Commit outside of the merge I can't.

I see the issue now.
![screen shot 2016-05-12 at 12 57 26 pm](https://cloud.githubusercontent.com/assets/5550483/15223390/30c6f7a6-1842-11e6-9adc-6928d254a8f3.png)
![screen shot 2016-05-12 at 12 57 57 pm](https://cloud.githubusercontent.com/assets/5550483/15223391/30c9de94-1842-11e6-99dc-1763a8fc8a13.png)
![screen shot 2016-05-12 at 12 58 24 pm](https://cloud.githubusercontent.com/assets/5550483/15223389/30c5ee10-1842-11e6-9c86-ac8b82827e00.png)

Thanks.

**Comment by tomasbjerre** [comment]
No there is only *${PULL_REQUEST_TO_HASH}* that should be the latest commit of the target branch.
There is also *${PULL_REQUEST_MERGE_COMMIT}* but it is empty for all events but merged event.

For a repo like:
```
*       d24afe7 2016-05-10  Using password type for keystore password field (Tomas Bjerre)
*       070e7df 2016-05-10  Merge pull request #115 from sanzinger/fix/proxyurl (Tomas Bjerre)
|\  
| *     2775070 2016-05-10  Change proxy url/port fields to text (Stefan Anzinger)
* |     934453f 2016-05-09  doc (Tomas Bjerre)
```

You want to find *070e7df*? The *${PULL_REQUEST_TO_HASH}* will give you *d24afe7*.

**Comment by tomasbjerre** [comment]
Is this problem new in 2.18? I made a very big rewrite in that release.

**Comment by nwsheppard** [comment]
I tested under a earlier version, but it was only with a test repo that didn't get many commits.  I have only started using 2.18 in production and really exercising it, so I don't really have a reference to earlier versions.

**Comment by tomasbjerre** [comment]
Perhaps, as a workaround, you can use *${PULL_REQUEST_TO_BRANCH}* and resolve it to the latest commit hash in the build job.

Since I cant reproduce this, I'll wait and see if others are reporting the problem.

**Comment by tomasbjerre** [comment]
If you have time perhaps you can try reproducing this with the Atlas SDK. How to set it up is explained in the readme and also in [the travis script](https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/blob/master/.travis.yml).

I currently have no Bitbucket Server installation to test this on.

**Comment by tomasbjerre** [comment]
I added integration tests for REST API and found the problem. Missing annotations, not specifying consuming content type of resources. Will release fix in 2.21.

**Comment by nwsheppard** [comment]
I can confirm that version 2.21 fixed the issue.  Thank you for such a fast turnaround and superb communication.

**Comment by jorhett** [comment]
So this is a problem for certain kinds of tests. When we are doing code evaluation we want to do the see changes placed by the commit against what they were changing. Right now I'm not seeing any variable which contains the git commit they created the PR against. 

Can we get that in a separate variable please? (the value which was previously in TO_HASH)
