### ISSUE TITLE
How are folks handling/closing PR's?

### ISSUE THREAD

**Issue by cdancy** [tomasbjerre/pull-request-notifier-for-bitbucket#118]
Question here: when kicking an external build (e.g. jenkins, bamboo) how are you/others handling the closing of PR's? The workflow I have in mind is such:
1. Plugin kicks relevant build when PR/branch is created.
2. Build checks out branch, performs some work, then merges branch back into master then pushes.
3. Delete PR/branch from first step.

How are folks handling step 3? Is the idea that one should be calling back to bitbucket to do this through some restful API? Does the plugin do any of this for us?

**Comment by tomasbjerre** [comment]
I know of two blog posts that describes how the plugin is used.

* https://christiangalsterer.wordpress.com/2015/04/23/continuous-integration-for-pull-requests-with-jenkins-and-stash/

* http://bjurr.se/building-atlassian-stash-pull-requests-in-jenkins/

I would probably wait for code reviewers before closing the PR.

**Comment by stoleas** [comment]
Workzone can do auto-merging once you have cleared all merge blocks; such as auto-merge after set number of successful builds and/or reviews.

**Comment by cdancy** [comment]
@stoleas and others stumbling upon this issue: I write the java-client [bitbucket-rest](https://github.com/cdancy/bitbucket-rest), which is based on jclouds, and works against Bitbuckets REST api. We currently use this plugin to kick our builds and then the library to do [merges](https://github.com/cdancy/bitbucket-rest/blob/master/src/main/java/com/cdancy/bitbucket/rest/features/PullRequestApi.java#L72), [create PR's](https://github.com/cdancy/bitbucket-rest/blob/master/src/main/java/com/cdancy/bitbucket/rest/features/PullRequestApi.java#L63), [introspect PR's](https://github.com/cdancy/bitbucket-rest/blob/master/src/main/java/com/cdancy/bitbucket/rest/features/PullRequestApi.java#L54), etc.. Feel free to give it a go and provide any feedback.
