### ISSUE TITLE
Question on the configuration permissions.

### ISSUE THREAD

**Issue by carlmot** [tomasbjerre/pull-request-notifier-for-bitbucket#123]
When in a repo view and under the plugin's configuration I can see the global configs and configs for other repos. I am also able to edit and save those configs (even though I am not a system admin or admin for the other repo). The plugin's perms are set to Everyone. Is this by design or is there something wrong?

**Comment by tomasbjerre** [comment]
Perhaps it should be admin if you are admin for the reoo you are configuring.

**Comment by carlmot** [comment]
Hi and thanks for the response!

Maybe I misunderstood how the permissions work.

This is how it is working now...
PRNFB System Admin setting allows only BB System Admin perms to
create/view/edit any PRNFB config (in global view or repo view).
Admin setting allows BB Admin to create/view/edit any PRNFB config.
Everyone setting allows anyone that can edit settings in their repo view
to create/view/edit any PRNFB config (including configs for other repos and
those for ALL repos).

This is of limited usage in a large BB deployment with hundreds of repos
and thousands of users.
We need to allow a Bitbucket User who can edit their repo settings to,
while in the repo view, create/view/edit PRNFB configs for that repo - but
only for that repo.
They cannot be allowed to edit other configs for other repos (unless of
course they are in that repo view and have perms to edit those repo
settings).

Thanks.








*Carl Golaszewski*

Motorola Solutions Inc.

IT - Common Applications & Metrics

(847)-576-2053

**Comment by tomasbjerre** [comment]
I see there are things to fix here.

Users are able to browse to any project admin-page like `/bitbucket/plugins/servlet/prnfb/admin/PROJECT_1/rep_1`. Or global admin like `/bitbucket/plugins/servlet/prnfb/admin`. It may seem like an issue. But they are all just using the REST API and I'd like to implement security there.

* A user should not be able to add a button that is invisible for the user. If a user is admin of a repo. The user should not be able to add a button that is only visible for *system admin*. When doing so now it looks like the button is not saved at all, but it is.

* If the plugin is configured so that only *admins* are allowed to change settings. The user must be admin of the repo. Current implementation checks if user is global admin.

**Comment by tomasbjerre** [comment]
I think this may be fixed now in:
https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/releases/tag/pull-request-notifier-for-bitbucket-2.24

Are you able to test it like that? I don't feel I have enough time to test it and I'll out on vacation for a few weeks soon. So dont want to release something in Marketplace that is causing issues.

**Comment by carlmot** [comment]
Yes. I'll see if I can find time to do some tests.

*Carl Golaszewski*

Motorola Solutions Inc.

IT - Common Applications & Metrics

(847)-576-2053

**Comment by tomasbjerre** [comment]
I released it now to Marketplace. So you can get it there.

**Comment by carlmot** [comment]
Hi Tomas and thanks.

There does remain what seems to me is an issue.

Test
PRNFB V2.24 (Fixes some perm issues over previous 2.23 version)
BB version 4.6.0
PRNFB global perm settings set to 'Admins and Project Admins'.

In a repo config view...

The Buttons config filters the list and only shows those for the repo
config being viewed and those that are for ANY/ANY (project/repo).

By contrast however, the Notifications config lists all configs which
includes those from other project/repos and ANY/ANY.
User can pull up those configs.
User is allowed to edit the configs of other project/repos but does
correctly get blocked on a save - except for those that are ANY/ANY (see
next).

A user with admin perms to a repo can also edit and save the Button Config
or Notification Configs that are set as project ANY, repo ANY in the global
conig settings.
It will also get a new name that includes the repo name and it will be
changed from ANY/ANY to that project/repo.

The ability to change those for ANY/ANY maybe should be restricted to
Bitbucket Admins.

Thoughts?




*Carl Golaszewski*

Motorola Solutions Inc.

IT - Common Applications & Metrics

(847)-576-2053

**Comment by tomasbjerre** [comment]
Perhaps the repo level admin page should only show configs that are have
that repo explicitly set. Not those that have "any" repo.

What do you think?
Den 22 jun 2016 17:44 skrev "carlmot" <notifications@github.com>:

**Comment by carlmot** [comment]
Yes, that's what I was thinking also.

*Carl Golaszewski*

Motorola Solutions Inc.

IT - Common Applications & Metrics

(847)-576-2053

**Comment by tomasbjerre** [comment]
I just released 2.25 to marketplace. You may try that, see if it works!

**Comment by carlmot** [comment]
Looks good. Thanks!
