### ISSUE TITLE
Per-Repository support for pull-request-notifier-for-stash

### ISSUE THREAD

**Issue by AArellanoVTAS262** [tomasbjerre/pull-request-notifier-for-bitbucket#126]
Hello,

We are currently using the pull-request-notifier-for-stash v1.38 on Stash v3.11.1 to trigger validation builds on Jenkins for every pull request.  It works great however, we need the ability to configure the trigger at the repository instead of globally at Administrator settings.  Any configuration change would have to be done through our corporate Stash administrators.  We would like to avoid that.

We are basically asking for the same functionality for Stash as resolved issue https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/issues/25

Thanks,
Alex Arellano

**Comment by tomasbjerre** [comment]
I wont spend time on implementing that for Stash. I'll just refer you to
upgrade to Bitbucket Server. Sorry :)
Den 23 jun 2016 23:07 skrev "AArellanoVTAS262" <notifications@github.com>:

**Comment by AArellanoVTAS262** [comment]
Understood.  Thank you.
