### ISSUE TITLE
Git Plugin not working as expected with Pull Request Notifier for Bitbucket 

### ISSUE THREAD

**Issue by alex131290** [tomasbjerre/pull-request-notifier-for-bitbucket#127]
Hi, 

I have Jenkins 1.609, Git Plugin 2.4.4, Bitbucket v4.2.0, and pull-request-notifier-for-bitbucket v.2.26.
My workflow is the following:

I've configured the pull-request-notifier-for-bitbucket to trigget any PRs that are being opened to master branch.
On my jenkins job, i've configured the git repository (using ssh credentials), in the branch specifier, i have the following content "*/pr/*"

The pull-request-notifier-for-bitbucket is triggering the Jenkins, sometimes it's working and sometimes i'm getting the following error on jenkins:

16:44:29  > git -c core.askpass=true fetch --tags --progress ssh://git@stash.corp.mydomain.com:7999/qa/pd-tests.git +refs/heads/*:refs/remotes/origin/*
16:44:29  > git config remote.origin.url ssh://git@stash.corp.mydomain.com:7999/qa/pd-tests.git # timeout=10
16:44:29  > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
16:44:29  > git config remote.origin.url ssh://git@stash.corp.mydomain.com:7999/qa/pd-tests.git # timeout=10
16:44:29 Fetching upstream changes from ssh://git@stash.corp.mydomain.com:7999/qa/pd-tests.git
16:44:29 using GIT_SSH to set credentials tonbuilder-rhel6
16:44:29  > git -c core.askpass=true fetch --tags --progress ssh://git@stash.corp.mydomain.com:7999/qa/pd-tests.git +refs/heads/*:refs/remotes/origin/*
16:44:30  > git rev-parse bc19bbe50001d6e62a200933308458113b367498^{commit} # timeout=10
16:44:30 FATAL: Command "git rev-parse bc19bbe50001d6e62a200933308458113b367498^{commit}" returned status code 128:
16:44:30 stdout: bc19bbe50001d6e62a200933308458113b367498^{commit}
16:44:30 
16:44:30 stderr: fatal: ambiguous argument 'bc19bbe50001d6e62a200933308458113b367498^{commit}': unknown revision or path not in the working tree.
16:44:30 Use '--' to separate paths from revisions, like this:
16:44:30 'git <command> [<revision>...] -- [<file>...]'
16:44:30 
16:44:30 hudson.plugins.git.GitException: Command "git rev-parse bc19bbe50001d6e62a200933308458113b367498^{commit}" returned status code 128:
16:44:30 stdout: bc19bbe50001d6e62a200933308458113b367498^{commit}
16:44:30 
16:44:30 stderr: fatal: ambiguous argument 'bc19bbe50001d6e62a200933308458113b367498^{commit}': unknown revision or path not in the working tree.
16:44:30 Use '--' to separate paths from revisions, like this:
16:44:30 'git <command> [<revision>...] -- [<file>...]'
16:44:30 
16:44:30 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1719)
16:44:30 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1695)
16:44:30 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1691)
16:44:30 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1321)
16:44:30 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1333)
16:44:30 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.revParse(CliGitAPIImpl.java:678)
16:44:30 	at hudson.plugins.git.GitAPI.revParse(GitAPI.java:316)
16:44:30 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:44:30 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
16:44:30 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:44:30 	at java.lang.reflect.Method.invoke(Method.java:606)
16:44:30 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:326)
16:44:30 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:301)
16:44:30 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:260)
16:44:30 	at hudson.remoting.UserRequest.perform(UserRequest.java:121)
16:44:30 	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
16:44:30 	at hudson.remoting.Request$2.run(Request.java:325)
16:44:30 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
16:44:30 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
16:44:30 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
16:44:30 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
16:44:30 	at java.lang.Thread.run(Thread.java:745)
16:44:30 	at ......remote call to tonat-driver(Native Method)
16:44:30 	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1360)
16:44:30 	at hudson.remoting.UserResponse.retrieve(UserRequest.java:221)
16:44:30 	at hudson.remoting.Channel.call(Channel.java:753)
16:44:30 	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:179)
16:44:30 	at com.sun.proxy.$Proxy68.revParse(Unknown Source)
16:44:30 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl.revParse(RemoteGitImpl.java:555)
16:44:30 	at hudson.plugins.git.RevisionParameterAction.toRevision(RevisionParameterAction.java:98)
16:44:30 	at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:985)
16:44:30 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1098)
16:44:30 	at hudson.scm.SCM.checkout(SCM.java:484)
16:44:30 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1270)
16:44:30 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:609)
16:44:30 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
16:44:30 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:531)
16:44:30 	at hudson.model.Run.execute(Run.java:1741)
16:44:30 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
16:44:30 	at hudson.model.ResourceController.execute(ResourceController.java:98)
16:44:30 	at hudson.model.Executor.run(Executor.java:374)
16:44:30 found no commit info

**Comment by tomasbjerre** [comment]
I'm not really sure what you want to do. I would probably just add a shell script build step and do something like:
```
git clone $TO_REPO  
cd *  
git reset --hard $TO_HASH  
git status  
git remote add from $FROM_REPO  
git fetch from  
git merge $FROM_HASH  

#compile command here ...
```

**Comment by tomasbjerre** [comment]
No response, closing.
