### ISSUE TITLE
Trigger button not showing up.

### ISSUE THREAD

**Issue by Dhivyaa21** [tomasbjerre/pull-request-notifier-for-bitbucket#128]
I have two notifications set. One of them has a button trigger enabled with the filter expression. In the pull request view, i can see "Actions"  in the drop down but not the button itself.

I have the visibility of the button as "Everyone".

**Comment by tomasbjerre** [comment]
What does your filter look like? Does it work if you remove it?
Den 29 jun 2016 19:09 skrev "Dhivyaa21" <notifications@github.com>:

**Comment by Dhivyaa21** [comment]
The filter reg ex was the title of the button which is "Trigger build". 
And the button doesnt show up after removing the filter either.

**Comment by Dhivyaa21** [comment]
![screenshot1](https://cloud.githubusercontent.com/assets/9375666/16462206/2d59bedc-3dfe-11e6-90ee-b893ce3dc404.png)
![screenshot2](https://cloud.githubusercontent.com/assets/9375666/16462205/2d58e1e2-3dfe-11e6-9204-7a21b4a7f139.png)

**Comment by tomasbjerre** [comment]
Happens to me also, in Bitbucket Server 4.7.1. Which version of Bitbucket Server are you using?

**Comment by Dhivyaa21** [comment]
I am using 4.7.1. Is there any fix for this?

**Comment by tomasbjerre** [comment]
You may try upgrading to version 2.27 of the plugin. Should be fixed now.

**Comment by tomasbjerre** [comment]
Open issue again if not solved

**Comment by smicallef-centralway** [comment]
Looks like this issue is re-appearing, using 2.53 of the plug-in against Bitbucket 4.6.0. Is it likely that a Bitbucket upgrade will do the trick?

**Comment by tomasbjerre** [comment]
Perhaps you problem is the same as in: https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/issues/197 ?

**Comment by smicallef-centralway** [comment]
We upgraded to 2.54 and it didn't make a difference, unfortunately. Any other suggestions before we go ahead with a Bitbucket upgrade?

**Comment by tomasbjerre** [comment]
What does you configuration look like? The button and the notification you expect to trigger.

**Comment by tomasbjerre** [comment]
Did an upgrade help?

**Comment by tomasbjerre** [comment]
Do you se any errors in Developer Tools console log?

**Comment by tomasbjerre** [comment]
See #197
