### ISSUE TITLE
Buttons do not appear [4.3.1]

### ISSUE THREAD

**Issue by vveloso** [tomasbjerre/pull-request-notifier-for-bitbucket#131]
Hi.

Our company is using the latest version of the plugin on Bitbucket 4.3.1.

Trigger buttons do not appear on the pull request view. Additionally, a Javascript error is logged by the browser:

`Uncaught ReferenceError: $buttonDropdownParent is not defined`

Is this a side effect of the recent 4.7 compatibility updates?

Thanks.

**Comment by tomasbjerre** [comment]
Yes most likely. Im out travelling but I'll try a quick fix here soon...

**Comment by tomasbjerre** [comment]
You may try version 2.30 and see if that helps. The crash should be avoided now.

If your buttons dont appear I'd like to review your configuration. And also you may check for exceptions in the Bitbucket Server logs.

**Comment by vveloso** [comment]
Our admin installed 2.30. The Javascript error went away but the button still does not appear.

I did a bit of debugging when the pull request view is loading and here are my findings:

I placed a breakpoint on the plugin/prnfb/pr-triggerbutton minified code:

![button-debug-1](https://cloud.githubusercontent.com/assets/796099/16687496/ecaa15de-4510-11e6-88b4-a10f1ca30151.png)

On the console:

```
> a
< []
> e(".triggerManualNotification")
< [button.aui-button.triggerManualNotification]
```

It appears that `$buttonArea`, minified as `$a`, does not point at a valid element?

The `loadSettingsAndShowButtons()` function, here as `$c`, is called. The HTTP GET returns the following:

```
[{"name":"Build Now","projectKey":"TPRN","repositorySlug":"bcb-test","userLevel":"EVERYONE","uuid":"bf5f0a4c-fc53-4181-a406-6a2adfd0c6b3"}]
```

So the button should appear. The code for the item is executed. However the button does not appear. Apparently there is no `ul` close to `.triggerManualNotification`?

I'm afraid that I don't have direct access to the server nor knowledge of the BitBucket APIs so experimenting is quite limited.

**Comment by tomasbjerre** [comment]
Upgrading Bitbucket Server to 4.4 or newer should work. But I guess its not as easy as it sounds in an organization...

It is definitely possible to fix the issue in the plugin. But I'm not sure when that can happen. PR:s are always welcome. Just set the version to 4.3.1 at the bottom of the pom.xml. More info is in the README.md.

**Comment by tomasbjerre** [comment]
You may try version 2.31! =)

**Comment by vveloso** [comment]
Works beautifully. Thank you. :-)
