### ISSUE TITLE
How to trigger Jenkins 2.1 with parameters

### ISSUE THREAD

**Issue by shlomipm** [tomasbjerre/pull-request-notifier-for-bitbucket#132]
Hi, I Just download this plugin with Bitbucket 4.7.1 When trying to trasfer parameters to jenkins (2.1) i'm getting nothing. e.g. "The URL to invoke when notification is triggered" - https://<my Jenkins url>/job/eventhubutils_Build_mvn/buildWithParameters?FROM_REPO=${PULL_REQUEST_FROM_REPO_NAME}&TO_REPO=${PULL_REQUEST_TO_REPO_NAME}&PULL_REQUEST_USER_DISPLAY_NAME=${PULL_REQUEST_USER_DISPLAY_NAME}&EVERYTHING_URL=${EVERYTHING_URL}  Can you advise?

PS - the 'Build with Parameters' started but all the parameters are blank.
(Bitbucket server is Windows and Jenkins is Linux)

**Comment by tomasbjerre** [comment]
What do you get when you this?
```
curl -u username:password 'http://localhost:7990/bitbucket/rest/prnfb-admin/1.0/settings/notifications' -H 'Accept: application/json, text/javascript, */*; q=0.01'
```

I would suspect its a Jenkins thing. The values are probably supplied by this plugin but not consumed by Jenkins. You may confirm that by changing the URL to, perhaps, an Apache installation and then check the logs of that to see what URL was actually invoked.

If you dont have such installation, you can change URL to:
`http://cogi.bjurr.se/?FROM_REPO=${PULL_REQUEST_FROM_REPO_NAME}&TO_REPO=${PULL_REQUEST_TO_REPO_NAME}&PULL_REQUEST_USER_DISPLAY_NAME=${PULL_REQUEST_USER_DISPLAY_NAME}&EVERYTHING_URL=${EVERYTHING_URL}`
And I will check my logs.

Also is there any stacktrace in the logs of Bitbucket Server?

**Comment by shlomipm** [comment]
I've changed it to your URL and i'm triggering it now.

**Comment by tomasbjerre** [comment]
My log contains this:
`/?FROM_REPO=eventhubutils&TO_REPO=eventhubutils&PULL_REQUEST_USER_DISPLAY_NAME=PRDAQCC1&EVERYTHING_URL=BUTTON_TRIGGER_TITLE=&INJECTION_URL_VALUE=&PULL_REQUEST_ACTION=OPENED...`

I think you should just remove **EVERYTHING_URL=** from your URL and it should work.

**Comment by shlomipm** [comment]
Thank you for your quick reply,
i just sent you another URL, can you please tell me what you got?
http://cogi.bjurr.se/?url=${PULL_REQUEST_TO_SSH_CLONE_URL}&branches=pr/${PULL_REQUEST_TO_BRANCH}&sha1=${PULL_REQUEST_FROM_HASH}&PULL_REQUEST_URL=${PULL_REQUEST_URL}&PULL_REQUEST_ID=${PULL_REQUEST_ID}

It seems that the plugin send Parameters but why Jenkins job not receiving them?
https://<my Jankins server>/job/<job name>/buildWithParameters?FROM_REPO=${PULL_REQUEST_FROM_REPO_NAME}&TO_REPO=${PULL_REQUEST_TO_REPO_NAME}&PULL_REQUEST_USER_DISPLAY_NAME=${PULL_REQUEST_USER_DISPLAY_NAME}

FROM_REPO,TO_REPO,PULL_REQUEST_USER_DISPLAY_NAME - text parameters in the job.

**Comment by tomasbjerre** [comment]
```
/?url=ssh%3A%2F%2Fgit%40bebitbucket1.cloudapp.net%3A7999%2Fop%2Feventhubutils.git&branches=pr/dev&sha1=a9f46ec306daff283f67515c2c0efbf2da6de4f6&PULL_REQUEST_URL=http%3A%2F%2Fbebitbucket1.cloudapp.net%3A7990%2Fprojects%2FOP%2Frepos%2Feventhubutils%2Fpull-requests%2F34&PULL_REQUEST_ID=34
```

If you simply browse to that URL with Chrome or something. Does that work?

**Comment by shlomipm** [comment]
No, it supposed to trigger a job in Jenkins,
What i'm trying to do is to trigger a job on Jenkins with parameters

https://{my Jankins server}/job/{job name}/buildWithParameters?FROM_REPO=${PULL_REQUEST_FROM_REPO_NAME}&TO_REPO=${PULL_REQUEST_TO_REPO_NAME}&PULL_REQUEST_USER_DISPLAY_NAME=${PULL_REQUEST_USER_DISPLAY_NAME}

The trigger is working, the variables are moving from Bitbucket (as you are getting them)  but the Parameters in the job that supposed to be set by the variables from Bitbucket stays BLANK.

**Comment by tomasbjerre** [comment]
If you add a shell script build step, and execute `env` it should printout all parameters. Does it contain your parameters?

**Comment by shlomipm** [comment]
lets make some order.
'env' is nothing to do here because those are 'Parameters' and not 'Environment Variables' so i insert a shell script to 'echo' them.

for testing i'm using the next url:
https://bejenkins1.cloudapp.net:8443/job/eventhubutils_Build_mvn/buildWithParameters?FROM_REPO=fromrepotest&TO_REPO=torepotest&PULL_REQUEST_USER_DISPLAY_NAME=myusername

when i'm inserting it directly in the browser - Jenkins is triggered and all the Parameters are in.
when i'm sending it with the plugin (post method) - Jenkins is triggered but no parameters are set.

maybe credentials issue?
(can we chat over skype to be more quick?)

**Comment by tomasbjerre** [comment]
The parameters should be exposed as environment variables, it says so [here](https://wiki.jenkins-ci.org/display/JENKINS/Parameterized+Build).

So you use POST method as request method in the plugin? If you add the parameters in the URL you must use GET. Selecting GET should be equivalent to this:
```
curl -u username:password 'https://bejenkins1.cloudapp.net:8443/job/eventhubutils_Build_mvn/buildWithParameters?FROM_REPO=fromrepotest&TO_REPO=torepotest&PULL_REQUEST_USER_DISPLAY_NAME=myusername'
```

And if you actually want to use POST method. I would try adding this to post content field and remove it from the URL:
```
FROM_REPO=${PULL_REQUEST_FROM_REPO_NAME}&TO_REPO=${PULL_REQUEST_TO_REPO_NAME}&PULL_REQUEST_USER_DISPLAY_NAME=${PULL_REQUEST_USER_DISPLAY_NAME}
```

**Comment by shlomipm** [comment]
Where do i need to run the curl command (does it matter?) and what do i supposed to get in return? 
(currently i;m getting a lot of html lines and nothing happens in the Jenkins side).

**Comment by tomasbjerre** [comment]
Im not 100% that the curl comman is correct. But something lika that should
trigger a build. It may helt troubleshooting. And did you change
username:password to a valid one?

Do you use GET method in the plugin?

Den 16 juli 2016 11:30 skrev "Shlomi Perets" <notifications@github.com>:

Where do i need to run the curl command (does it matter?) and what do i
supposed to get in return?
(currently i;m getting a lot of html lines and nothing happens in the
Jenkins side).

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/issues/132#issuecomment-233122123>,
or mute the thread

**Comment by mihirsoni** [comment]
@tomasbjerre  In my case It is not at all triggering anything from bitbucket. I am using bitbucket 4.7.1

**Comment by mihirsoni** [comment]
When I use this command 

```sh
$ curl -u username:passwd 'http://localhost:7990/bitbucket/rest/prnfb-admin/1.0/settings/notifications' -H 'Accept: application/json, text/javascript, */*; q=0.01'
```

I get response as 

```js
{"message":"null for uri: http://localhost:7990/rest/api/1.0/bitbucket/rest/prnfb-admin/1.0/settings/notifications","status-code":404}%
```

**Comment by tomasbjerre** [comment]
You should open another issue about that. This issue is not about this
plugin at all. It works as expected. Your case might be about the plugin.

Den 18 juli 2016 09:03 skrev "Mihir Soni" <notifications@github.com>:

**Comment by mihirsoni** [comment]
@tomasbjerre  As mentioned , I have created issue #133

**Comment by tomasbjerre** [comment]
I rewrote the documentation in the [README](https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/blob/master/README.md) does that help?

It took me a while but I managed to trigger Jenkins 2.2 now!

**Comment by tomasbjerre** [comment]
Open issue again if any problems.

**Comment by alinkamalinkakalinka** [comment]
Hi! I have the same issue as well. I try to trigger Jenkins job with https://jenkins/job/pull%20request_builder/buildWithParameters?FROM_REPO=${PULL_REQUEST_FROM_REPO_NAME}. I tried both POST and GET, unfortunately the job is triggered but parameters' values are blank and not listed as env variables. Could you help me please? Thank you in advance.
<img width="848" alt="screen shot 2018-10-30 at 16 58 55" src="https://user-images.githubusercontent.com/9265161/47731978-8ff7f600-dc65-11e8-9e6a-ffc8845c3d7e.png">

<img width="1100" alt="screen shot 2018-10-30 at 17 03 16" src="https://user-images.githubusercontent.com/9265161/47732077-b9188680-dc65-11e8-88b7-376afff19bdf.png">
