### ISSUE TITLE
Plugin in not Triggering on a specific event Bitbucket 4.7.1

### ISSUE THREAD

**Issue by mihirsoni** [tomasbjerre/pull-request-notifier-for-bitbucket#133]
Hi @tomasbjerre , 

After successfully installing this plugin , I have configured it on Pull Request Open event to trigger a GET url with parameters. But it never triggers any thing when you open new Pull Request.

I have executed following command to check the plugin status as mentioned [here](https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/issues/132#issuecomment-233032995)

```sh
curl -u username:passwd 'http://localhost:7990/bitbucket/rest/prnfb-admin/1.0/settings/notifications' -H 'Accept: application/json, text/javascript, */*; q=0.01'
```

Out put is 

```js
{"message":"null for uri: http://localhost:7990/rest/api/1.0/bitbucket/rest/prnfb-admin/1.0/settings/notifications","status-code":404}
```

**Comment by tomasbjerre** [comment]
I added an issues section to the *README.md*, you may check that to see if it helps.

If you get a null-response like that, then the admin page of the plugin should also fail to work. Does it?

**Comment by mihirsoni** [comment]
@tomasbjerre  No , on admin page I am able to see the page where I can setup triggers.

**Comment by tomasbjerre** [comment]
Did you solve it? Or why did you close the issue?

**Comment by mihirsoni** [comment]
@tomasbjerre  I have tried to follow whatever is mentioned on README.md and I closed it by mistake sorry,

```sh
curl -u admin:admin 'http://localhost:7990/bitbucket/rest/prnfb-admin/1.0/settings' -H 'Accept: application/json, text/javascript, */*; q=0.01'
```

Output
```
{"message":"null for uri: http://localhost:7990/rest/api/1.0/bitbucket/rest/prnfb-admin/1.0/settings","status-code":404}
```

```sh
curl -u admin:admin 'http://localhost:7990/bitbucket/rest/prnfb-admin/1.0/settings/notifications' -H 'Accept: application/json, text/javascript, */*; q=0.01'.
```
Output :- I am getting some  HTML.

Command :- 
```sh
curl -u admin:admin 'http://localhost:7990/bitbucket/rest/prnfb-admin/1.0/settings/buttons' -H 'Accept: application/json, text/javascript, */*; q=0.01'.
```

Output :- 
```js
{"message":"null for uri: http://192.168.124.91:7990/rest/api/1.0/bitbucket/rest/prnfb-admin/1.0/settings/buttons","status-code":404}%
```

**Comment by mihirsoni** [comment]
@tomasbjerre  I believe I can send it to your Jenkins server only if I get output of above commands expected correct ?

I have also tried to re-install the plugin but no luck.

**Comment by tomasbjerre** [comment]
Strange... if you use Chrome developer tools you should see the same GET
requests in the network tab. Do you?

How do you know that no URL is invoked?

Den 19 juli 2016 07:23 skrev "Mihir Soni" <notifications@github.com>:

**Comment by mihirsoni** [comment]
@tomasbjerre I know no url is triggered because the Job on jenkins is not triggering. I also copied that GET request and try to hit from the POSTMAN , but no output. What do you expect from the above curls. Are they valid response ?

**Comment by tomasbjerre** [comment]
You can try to point it to my webserver.

Den 19 juli 2016 07:26 skrev "Mihir Soni" <notifications@github.com>:

**Comment by tomasbjerre** [comment]
So it may be a Jenkins problem and not a plugin problem.

I expect to see the configuration. A json structure with your configured
values.

Den 19 juli 2016 07:30 skrev "Mihir Soni" <notifications@github.com>:

**Comment by mihirsoni** [comment]
@tomasbjerre  I agree, but I am not getting that response correctly right , nevertheless I triggered your Jenkins , let me know fi you have got any request or not.

```sh
http://cogi.bjurr.se/?FROM=${PULL_REQUEST_FROM_HASH}&TO=${PULL_REQUEST_TO_HASH}&TOSLUG=${PULL_REQUEST_TO_REPO_SLUG}&TOREPO=${PULL_REQUEST_TO_HTTP_CLONE_URL}&FROMREPO=${PULL_REQUEST_FROM_HTTP_CLONE_URL}&ID=${PULL_REQUEST_ID}&PROJECT=${PULL_REQUEST_TO_REPO_PROJECT_KEY}
```

**Comment by tomasbjerre** [comment]
I got this:
```
/?FROM=a8d16d5746475ce9c5c9d6444c5f3e0be97299d9&TO=409430647a3d74dc728fd5eba36318423d416b63&TOSLUG=testrepo&TOREPO=http%3A%2F%2Fm.soni%40192.168.124.91%3A7990%2Fscm%2Ftest%2Ftestrepo.git&FROMREPO=http%3A%2F%2Fm.soni%40192.168.124.91%3A7990%2Fscm%2Ftest%2Ftestrepo.git&ID=2&PROJECT=TEST
```

**Comment by mihirsoni** [comment]
@tomasbjerre Hmm okay but when I hit with my Jenkins URL directly from the browsers it works. I will double check this and revert back.

**Comment by tomasbjerre** [comment]
Maby this is the same issue as #132 then? So we close this one and have #132 open.

So it could be a firewall issue or something...

**Comment by mihirsoni** [comment]
@tomasbjerre They are on same IP range , I am not sure what could be issue , I am worried about curl calls output , are they wiered as we are getting 404 ?

**Comment by tomasbjerre** [comment]
Yes very strange. Dont know what that means...

You try to ssh to the bitbucket machine and do a curl call to tje jenkins
machine. To check the firewall.

I think it should also be a stacktrace in the bitbucket logs.

Den 19 juli 2016 07:49 skrev "Mihir Soni" <notifications@github.com>:

**Comment by mihirsoni** [comment]
@tomasbjerre Sure, I will try that and update you, thank you for your support , I will update the issue.

**Comment by mihirsoni** [comment]
@tomasbjerre I guess the Jenkins issue has resolved it , thanks a lot for your support. Appreciate your help.
