### ISSUE TITLE
Not able to see PR buttons

### ISSUE THREAD

**Issue by stoleas** [tomasbjerre/pull-request-notifier-for-bitbucket#134]
Hi Tomas,

We found a potential bug where if users don't have at least read access at the project level they are not able to see the buttons in the Pull Request. Users who are not specific in the project access control and are only specified in the repository are not going to be able to see the buttons despite having Read/Write permissions.

We are currently using Bitbucket v4.3.2. Checked the logs and am not seeing any related errors.

Thanks,
Edward Q.

**Comment by tomasbjerre** [comment]
Did you find this by observing stacktraces in the log or other crashes?

**Comment by tomasbjerre** [comment]
Should be fixed in 2.33. Open issue again if not fixed!
