### ISSUE TITLE
Triigger build button appears in the merged PR view too.

### ISSUE THREAD

**Issue by Dhivyaa21** [tomasbjerre/pull-request-notifier-for-bitbucket#137]
The trigger build button appears even after the PR is merged. Is there a way to disable this button for merged PRs?

**Comment by tomasbjerre** [comment]
One solution may be to add a variable, something like ${PULL_REQUEST_STATE}, and then prevent this with the filter string/regexp.

So the answer is ***no*** for now. But I'll label this as a feature request.

**Comment by tomasbjerre** [comment]
I added PULL_REQUEST_STATE variable so you can use it in the filter text/regexp to disable notifications for merged PR:s. Open issue again if any problems!

**Comment by Dhivyaa21** [comment]
Thanks! Its working!
