### ISSUE TITLE
Bitbucket - PR Button created at project level shows up for other projects in the same host

### ISSUE THREAD

**Issue by msbakya** [tomasbjerre/pull-request-notifier-for-bitbucket#139]
Bitbucket - PR Button created at project level shows up for other projects in the same host. So, All other project members are seeing one extra button. However if we assign the Button to particular repository then it shows up only for the repo.  How can i fix it?

**Comment by tomasbjerre** [comment]
Upgrade to 2.36 and this should be solved. Open issue again if still a problem.

**Comment by msbakya** [comment]
Issue has been fixed. Thank you so much for your help
