### ISSUE TITLE
Show notification when settings are saved

### ISSUE THREAD

**Issue by pmbsa** [tomasbjerre/pull-request-notifier-for-bitbucket#140]
Hi, is anybody else having issues saving settings for this plugin. I am trying to configure it based on this blog https://christiangalsterer.wordpress.com/2015/04/23/continuous-integration-for-pull-requests-with-jenkins-and-stash/. I dont get any errors when I click on save, I just get nothing. Nothing in the log either. If I then exit the config page and come back in the savings are not persisted.

thanks
Paul

**Comment by tomasbjerre** [comment]
The readme has a section about reporting issues. Did you try any of the things it suggests?

**Comment by pmbsa** [comment]
Hi Tomas, thanks, I have used the curl commands to check the configuration (apologies, I didnt fully understand that the commands would return the plugin setup, I misunderstood the intention there). From the curl commands I can see that the config has in fact been stored, the UI was simply not reporting as such. I will continue wit the blog now and see how I get on with notifiying my jenkins setup.

thanks
Paul

**Comment by tomasbjerre** [comment]
Perhaps a silly question. But did you see the dropdown there in the gui? Is it empty?

That was the problem in: https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/issues/116

**Comment by pmbsa** [comment]
:D embarrassingly it didnt dawn in me at all that that dropdown reflected the notifications that have been setup. I see it now. All working, I have saved many many configurations!... I would say that where the confusion came in was that the GUI never notified me that a save was successful. Perhaps a notification of sorts might idiot proof it for peeps like me?

**Comment by tomasbjerre** [comment]
Yes. I'll add a notification :)

**Comment by tomasbjerre** [comment]
Added a confirmation in 2.37.
