### ISSUE TITLE
Bitbucket - PR button disappears like flash for a project

### ISSUE THREAD

**Issue by msbakya** [tomasbjerre/pull-request-notifier-for-bitbucket#142]
PR button disappears like flash for a particular project in a host. It is showing up for other projects in the same host.  I could see the button for fraction of second. 

we are on 2.37 of the plugin and 4.3.2 of bitbucket

**Comment by tomasbjerre** [comment]
How did you configure it?

**Comment by msbakya** [comment]
I have tried creating PR button global as well as repo level.. Nothing works. But I do the same for other projects and its working fine

**Comment by tomasbjerre** [comment]
Did you see ***Reporting issues*** in the readme?

Anything in your server log? In developer tools console?

**Comment by msbakya** [comment]
I have checked logs and i don't see anything in the log too

**Comment by tomasbjerre** [comment]
Can you post your configuration? The response from rest resources are the
best.

Den 22 aug. 2016 16:45 skrev "msbakya" <notifications@github.com>:

**Comment by msbakya** [comment]
![rp-button-config](https://cloud.githubusercontent.com/assets/20978480/17863230/e312f03a-6866-11e6-9f63-822806e6f3d9.PNG)

**Comment by tomasbjerre** [comment]
And how did you configure the notification?

**Comment by msbakya** [comment]
![pr-notification1](https://cloud.githubusercontent.com/assets/20978480/17863900/b9090b1e-6869-11e6-8959-93de734c5760.PNG)
![pr-notification2](https://cloud.githubusercontent.com/assets/20978480/17863904/c1257652-6869-11e6-8688-bc28e8a4dacf.PNG)

**Comment by tomasbjerre** [comment]
You need the check the BUTTON_TRIGGER checkbox.

**Comment by msbakya** [comment]
Sorry.. that was my mistake.. .Thank you so much for your help
