### ISSUE TITLE
Where are the buttons supposed to appear?

### ISSUE THREAD

**Issue by mark0978** [tomasbjerre/pull-request-notifier-for-bitbucket#144]
I see no button added to the PR view
![image](https://cloud.githubusercontent.com/assets/106150/18034984/0e9e4d5e-6d11-11e6-9968-d2d2a991cf7a.png)

Even though:
![image](https://cloud.githubusercontent.com/assets/106150/18034998/518e1b3a-6d11-11e6-8316-97b4bc7a8129.png)

**Comment by tomasbjerre** [comment]
In the menu to the right of "merge". Click the dots.

**Comment by mark0978** [comment]
Here?  
Same is true for the Button form above being a drop list.

That leads me to ask, where are the button supposed to show up?
![image](https://cloud.githubusercontent.com/assets/106150/18034984/0e9e4d5e-6d11-11e6-9968-d2d2a991cf7a.png)

Even though:
![image](https://cloud.githubusercontent.com/assets/106150/18034998/518e1b3a-6d11-11e6-8316-97b4bc7a8129.png)

**Comment by tomasbjerre** [comment]
Yes, in the pull request view.

If you dont have any notification that will trigger on a pressed button. Then no button will show.

**Comment by tomasbjerre** [comment]
Yes, in the pull request view.

If you dont have any notification that will trigger on a pressed button. Then no button will show.

**Comment by mark0978** [comment]
Thanks.  Not sure why that was so hard to spot.

**Comment by tomasbjerre** [comment]
There use to be buttons at this area. In older versions of Bitbucket Server / Stash. But maby you already know that. It is the reason why I call it buttons, even if it is more like... menu links or something now.
