### ISSUE TITLE
Plugin not triggering on all configured triggers

### ISSUE THREAD

**Issue by nbppp2** [tomasbjerre/pull-request-notifier-for-bitbucket#146]
I am using Bitbucket 4.5.1. I am using plugin version 2.37. There are no messages in the browser indicating anything went wrong. I have attached a [truncated log file](https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/files/462595/atlassian-bitbucket-truncated.txt). 

<img width="1070" alt="screen shot 2016-09-08 at 4 24 07 pm" src="https://cloud.githubusercontent.com/assets/2420708/18365467/cf6e086c-75e0-11e6-9061-2fa824ae90d9.png">
<img width="1056" alt="screen shot 2016-09-08 at 4 24 19 pm" src="https://cloud.githubusercontent.com/assets/2420708/18365469/cf6f594c-75e0-11e6-9b10-759b0e22ab95.png">
<img width="1060" alt="screen shot 2016-09-08 at 4 24 35 pm" src="https://cloud.githubusercontent.com/assets/2420708/18365468/cf6f1b76-75e0-11e6-8abd-9b271be620e0.png">

<img width="433" alt="screen shot 2016-09-08 at 4 27 16 pm" src="https://cloud.githubusercontent.com/assets/2420708/18365550/288a7f7a-75e1-11e6-85b8-c373259c8a1d.png">

So ultimately my issue is that this plugin fires appropriately when I press the button I created to fire the job. I currently have my requests going to requestb.in to verify that they are being started/sent. I have attached a screenshot of the results I get when I click the button. I do not get the same result when I open a pull request. 

Starting on line 1 of the log are the events from the bitbucket code showing I opened a pull request (52). Starting on line 384 shows the log when I clicked the button for the same pull request. As you can see there are no events from se.bjurr in the lines showing the events of the PR open.

**Comment by tomasbjerre** [comment]
Its probably because of your filter string/regexp. It can only be true if a
button is pushed. A fix may be to let the regexp allow empty strings.

Den 8 sep. 2016 22:34 skrev "Daniel Weber" <notifications@github.com>:

**Comment by nbppp2** [comment]
That was it. I created 2 new triggers just for the button and removed the regex and it worked. Thanks.

**Comment by maniankara** [comment]
Perhaps this should be documented in the [blog](https://bjurr.com/continuous-integration-with-bitbucket-server-and-jenkins/) or somewhere else? Its not pretty evident. 
But keep up the good work !
