### ISSUE TITLE
In Progress Notification on build

### ISSUE THREAD

**Issue by dzonekl** [tomasbjerre/pull-request-notifier-for-bitbucket#152]
Hello, 

We are now successfully using the PR-notifier, in combination with the Jenkins StashNotifier plugin. The example on https://github.com/jenkinsci/stashnotifier-plugin shows how to notify for INPROGRESS State, which we also implemented. I however don't see the button state change, and not sure what to expect anyway. How do we show an ongoing build in the button ? 

Thanks Christophe

**Comment by tomasbjerre** [comment]
What do you mean with "the button state"?

**Comment by dzonekl** [comment]
As I say, I am not sure what to expect, should the button which I defined to trigger the build, show 'in progress' somehow? Or to rephrase, how do I visualized a build which is 'in progress' on a button or elsewhere in the PR view?

**Comment by tomasbjerre** [comment]
Stash Notifier Plugin can do that.

This shows a failed build, but it will show ongoing when it is ongoing: http://bjurr.com/content/images/2016/09/stash-notifier-in-bitbucket.png

More details here: http://bjurr.com/continuous-integration-with-bitbucket-server-and-jenkins/

**Comment by dzonekl** [comment]
mmmh I get Success and Failed, but not 'ongoing'.. Also I use pipeline, so stash notification is somewhat different. See my link above. So it should work, I will need to review all the configs then.

**Comment by tomasbjerre** [comment]
I would open an issue on Stash Notifier plugin and close this one.
