### ISSUE TITLE
PR button not appearing for a project in a Bitbucket host

### ISSUE THREAD

**Issue by msbakya** [tomasbjerre/pull-request-notifier-for-bitbucket#154]
Hi,

PR button not appearing for a project in a Bitbucket host. Users whoever has access to the project not able to see PR button except system admin. It happens with only one project and its working fine with other projects in the same host. 

I have deleted and created again and asked project admin to create it. However issue not fixed

Thanks
Bakyaraj M

**Comment by tomasbjerre** [comment]
There are some hints on reporting issues in the readme. What exactly is the config that you expect to give this result?

**Comment by msbakya** [comment]
Trying to trigger jenkins job. please find the attachment of PR notification settings

![bb-button-config](https://cloud.githubusercontent.com/assets/20978480/20275645/63db1714-aa67-11e6-8bf2-81f338cd8928.PNG)
![pr-config-part1](https://cloud.githubusercontent.com/assets/20978480/20275649/65e1c1f2-aa67-11e6-97f1-c863cc2b87bc.PNG)
![pr-config-part2](https://cloud.githubusercontent.com/assets/20978480/20275654/67a4c14c-aa67-11e6-8447-f16bf23e9fec.PNG)

**Comment by tomasbjerre** [comment]
Your filter regexp is empty. The notification will only trigger if the filter regexp matches the filter string. Perhaps you want to remove what you have in filter string field.

**Comment by msbakya** [comment]
Does the button appear only when regexp is correct? user is not able to see button itself

**Comment by tomasbjerre** [comment]
Yes. Only buttons that actually trigger any notification is shown. So if the regexp is not matching the text, then the button will not be shown. Unless some other notification is triggered by the button, then it should be shown.

**Comment by msbakya** [comment]
I have tried after adding regexp. Still no luck... Attached screen shot of latest settings


![pr-config-with-regexp](https://cloud.githubusercontent.com/assets/20978480/20284790/ba3f4416-aa8c-11e6-893e-bb3d5f2982f7.PNG)

**Comment by stoleas** [comment]
What happens if we remove the filter string and regexp completely?

**Comment by tomasbjerre** [comment]
Remove it completely to trigger for all projects.

If your project key is THUN then yes it shoukd work.

**Comment by msbakya** [comment]
The project key was THUN and it was not working. Also i have removed filter string and regexp and tried.Still it is not working

**Comment by tomasbjerre** [comment]
Can you see the buttons in the rest api? Documented in the wiki. Like `/projectKey/{projectKey}/repositorySlug/{repositorySlug}`does it give you the buttons?

**Comment by tomasbjerre** [comment]
Also, what is the version of Bitbucket Server that you use?

**Comment by msbakya** [comment]
Atlassian Bitbucket v4.8.3

**Comment by tomasbjerre** [comment]
Actually, I just saw that you are configuring it on repository level. So the buttons will only be visible in that repository and there is no need to use the filter functionality to filter the project.

**Comment by msbakya** [comment]
I have tried the same configuring at global settings and also checked by using ${PULL_REQUEST_FROM_REPO_ID} parameter. Still it not visible

**Comment by tomasbjerre** [comment]
Can you see the buttons in the rest api? Documented in the readme. Like /projectKey/{projectKey}/repositorySlug/{repositorySlug} does it give you the buttons?

**Comment by msbakya** [comment]
Yes.. it is.. PFA

[Rest-Api-output.txt](https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/files/595399/Rest-Api-output.txt)

**Comment by tomasbjerre** [comment]
Does Chrome Developer Tools show some error in console log when visiting the pull request page?  Are you sure where to look for the buttons in the gui?

**Comment by msbakya** [comment]
As i mentioned earlier I could able to see the button as i have admin access to host. Only the users unable to see the button. I have tried login as user and still i don't see the button.  It happens with only one project. It is working for other projects

**Comment by tomasbjerre** [comment]
Does Chrome Developer Tools show some error in console log when visiting the pull request page?

**Comment by msbakya** [comment]
batch.js?locale=en-US&nps-not-opted-out=true&supportedApplication=true:8485 GET https://bitbucket.test.com/bitbucket/rest/prnfb-admin/1.0/settings/buttons/repository/4382/pullrequest/78 500 (Internal Server Error)

**Comment by tomasbjerre** [comment]
Ok thats it. You have an exception in the application server running Bitbucket Server. What does it say?

**Comment by msbakya** [comment]
PFA

[exception.txt](https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/files/595900/exception.txt)

**Comment by tomasbjerre** [comment]
I made a possible fix for this. You may try 2.40. It might be that you have configured a button, then removed/renamed a repository/project. That case is now handled by ignoring buttons configured for that old repo/project.

**Comment by msbakya** [comment]
Yes.. The project has been renamed once in the past it seems. It is working fine now. Thanks for your help
