### ISSUE TITLE
Configuring against forked development

### ISSUE THREAD

**Issue by mattadamson** [tomasbjerre/pull-request-notifier-for-bitbucket#157]
Team,

Has anyone got this working successfully when using the forked workflow in Stash? In this configuration all developers will have a separate repository url which they create there branches and merge back to the central repository. 

If so how do you configure the jenkins job without having a separate job per developer fork? We have many developers so creating many jobs per developer isn't great for maintenance

https://christiangalsterer.wordpress.com/2015/04/23/continuous-integration-for-pull-requests-with-jenkins-and-stash/

Thanks

**Comment by tomasbjerre** [comment]
I do that with a shell script build step in Jenkins.

```
git clone $PULL_REQUEST_TO_HTTP_CLONE_URL  
cd *  
git reset --hard $PULL_REQUEST_TO_HASH  
git status  
git remote add from $PULL_REQUEST_FROM_HTTP_CLONE_URL  
git fetch from  
git merge $PULL_REQUEST_FROM_HASH  
git --no-pager log --max-count=10 --graph --abbrev-commit

#compile command here ...
```

What is the problem that you have?

**Comment by mattadamson** [comment]
thanks @tomasbjerre 

I'm starting to set this up however I was thinking from 

https://christiangalsterer.wordpress.com/2015/04/23/continuous-integration-for-pull-requests-with-jenkins-and-stash/

where it mentions this is used

https://wiki.jenkins-ci.org/display/JENKINS/Git+Plugin#GitPlugin-Pushnotificationfromrepository

which states

"This will scan all the jobs that:
Have Build Triggers > Poll SCM enabled.  No polling Schedule is required.
Are configured to build the repository at the specified URL
Are configured to build the optionally specified branches or commit ID"

How could this work with forks for a single jenkins job because the job can only have one GIT URL whereas each developers fork has a different URL. 


Thanks

**Comment by tomasbjerre** [comment]
I dont use the git-plugin. I dont use the option to checkout source from scm at all. I just use a simple shell script build step.

**Comment by mattadamson** [comment]
Ah I see so how does the pull request notifier plug in when calling Jenkins know to use your specific job where you configured the shell script build step?

**Comment by tomasbjerre** [comment]
There is a field for specifying the URL. See http://bjurr.com/continuous-integration-with-bitbucket-server-and-jenkins/

**Comment by mattadamson** [comment]
@tomasbjerre that's the URL for the actual jenkins server though. I meant when the URL comes to Jenkins how does it know to use your specific jenkins job configured with the shell script you mention? e.g. consider it's called GenericStashBranchBuilder. How is that job invoked from the generic URL coming to jenkins?

**Comment by tomasbjerre** [comment]
The url mentioned in the blog under the headline "Pull Request Notifier for
Bitbucket Server" is points to that job.

Den 15 nov. 2016 9:42 PM skrev "mattadamson" <notifications@github.com>:

**Comment by mattadamson** [comment]
thanks @tomasbjerre , we can close this issue now.

**Comment by mattadamson** [comment]
Hi @tomasbjerre actually on testing this script it doesn't seem to change the workspace to reflect the contents of the fork rather than the central branch $PULL_REQUEST_TO_HTTP_CLONE_URL. Can you think why this could be as the jenkins workspace also doesn't reflect this. 

I noticed the script doesn't have any git commands to change the branch too e.g. if the source of the PR is a forked with branch xxx shouldn't we also handle this in the generic script?

Many thanks

**Comment by mattadamson** [comment]
If you want me to open another ticket for this just let me know.  I know it's not ideal reopening tickets but it's also closely related to this

**Comment by tomasbjerre** [comment]
You dont need the branches. The script uses the commit hashes of the
branches.

It looks like the jenkins user does not have read access to the forks.

Den 20 nov. 2016 23:57 skrev "mattadamson" <notifications@github.com>:
