### ISSUE TITLE
Extract variables from Button Text

### ISSUE THREAD

**Issue by dzonekl** [tomasbjerre/pull-request-notifier-for-bitbucket#161]
Hi, 

I am looking for a way for Button A, to trigger pipeline with a variable var_button='A' and Button B to trigger the same pipeline with var_button='B'. 

Any way to configure this without creating multiple Notifications? 
A dialog which requires input for notification, would also do. 

Thanks!

**Comment by tomasbjerre** [comment]
Perhaps in your URL field do ...&var_button=${BUTTON_TRIGGER_TITLE}. Or is your title "Button A" and when pressed you only want "A" to be sent?

**Comment by dzonekl** [comment]
Hi Tomas, I'd like only the A, but your suggestion will work, when I strip of the string, until I get the var value. 
thx!
