### ISSUE TITLE
Provide list of email addressed for PR reviewers and participants as URL support variables 

### ISSUE THREAD

**Issue by christiangalsterer** [tomasbjerre/pull-request-notifier-for-bitbucket#162]
Provide two new variables:
PULL_REQUEST_REVIEWERS_EMAIL
PULL_REQUEST_PARTICIPANTS_EMAIL

Email addressed are separated with a comma.

Will provide a PR in the next days.

**Comment by christiangalsterer** [comment]
That was really fast, thanks very much for approving the PR.
Will be available with 2.41.

**Comment by tomasbjerre** [comment]
Its in 2.41 now!
