### ISSUE TITLE
What about pull request description ?

### ISSUE THREAD

**Issue by cosmostail** [tomasbjerre/pull-request-notifier-for-bitbucket#169]
Hi Devs,

Thanks. Good work. 
Just a question, I saw the PULL_REQUEST_TITLE, but can't find PULL_REQUEST_DESCRIPTION.. Why?

**Comment by tomasbjerre** [comment]
This is available in 2.42 now. Open issue again if any problems!

**Comment by tomasbjerre** [comment]
I removed it from EVERYTHING_URL. It may make the URL:s very big and I think it might generate alot of issues.
