### ISSUE TITLE
Add PULL_REQUEST_REVIEWERS_NEEDS_WORK_COUNT

### ISSUE THREAD

**Issue by dcsobral** [tomasbjerre/pull-request-notifier-for-bitbucket#179]
Add a variable for number of reviewers with status "NEEDS_WORK". I actually want to use this to avoid triggering builds if a reviewer thinks it needs work, which is cleared when new commits are pushed.

**Comment by tomasbjerre** [comment]
This is now in 2.48. Open issue again if any problems.
