### ISSUE TITLE
How can i copy the same webhook between Repos easily?

### ISSUE THREAD

**Issue by shlomipm** [tomasbjerre/pull-request-notifier-for-bitbucket#182]

**Comment by tomasbjerre** [comment]
There is both an admin page on repo and global level. So just use the global level admin page.

**Comment by tomasbjerre** [comment]
There is no copy feature.

Perhaps also you can use the filter text and filter regexp to avoid duplicated config.

**Comment by shlomipm** [comment]
Hi
All my webhooks are under the repo admin in the 'Pull request notifications', what is 'Global level' you are talking about?

Thanks for the quick reply.

**Comment by tomasbjerre** [comment]
This is the global admon page:
https://raw.githubusercontent.com/tomasbjerre/pull-request-notifier-for-bitbucket/master/sandbox/all.png

You can find it if you click "manage plugins".

Den 8 jan. 2017 15:58 skrev "Shlomi Perets" <notifications@github.com>:
