### ISSUE TITLE
How Do I Send Email Notifications

### ISSUE THREAD

**Issue by davemenc** [tomasbjerre/pull-request-notifier-for-bitbucket#183]
Is it possible to have the "notification" be an email? And is it possible to send digested emails? 

What we really want is a weekly digest of all the pull requests for the week. It's looking like there is no way to do that.

**Comment by itay** [comment]
@davemenc I believe you could write a Jenkins job that would do that for you, but it would all be your custom logic. Doesn't have to be Jenkins of course, you could notify any system that would coalesce the PR notifications and send out the digest on Fridays.
