### ISSUE TITLE
Include status for participants

### ISSUE THREAD

**Issue by kapinyajudit** [tomasbjerre/pull-request-notifier-for-bitbucket#192]
Currently only the count can be retrieved. It would be cool if their names and statuses could be retrieved, as well.

E.g. something like this:
Admin=NEEDS_WORK, User1=APPROVED

**Comment by tomasbjerre** [comment]
Or there can also be `*_EMAILS`, '*_SLUGS' and `*_NAMES`  variables. So there would be a `PULL_REQUEST_REVIEWERS_NEEDS_WORK_SLUGS` with all slugs of reviewers that wants more work.

**Comment by tomasbjerre** [comment]
This is now in 2.51. Open issue again if any problems!
