### ISSUE TITLE
Configuration to trigger on both button press and events

### ISSUE THREAD

**Issue by itay** [tomasbjerre/pull-request-notifier-for-bitbucket#196]
What's the right configuration to trigger on both a button press and an event (e.g. OPENED)? Additionally, how do I do this so that it will only accept that specific button and not others (and not cause others to show up)?

**Comment by tomasbjerre** [comment]
I would do it like this:
1. Add a button named "The title of the button"
2. Add a notification
2.1. Filter string: ${BUTTON_TRIGGER_TITLE}
2.2. Filter regexp: ^(The title of the button|)$
2.3 Triggers: OPENED, BUTTON_TRIGGER

**Comment by itay** [comment]
@tomasbjerre I thought that if you had the `${BUTTON_TRIGGER_TITLE}` there, it would require the button to be pressed and ignore the other events?

**Comment by tomasbjerre** [comment]
It will be resolved to an empty string for all events that are not a
pressed button.

Den 13 feb. 2017 7:57 PM skrev "Itay Neeman" <notifications@github.com>:

**Comment by itay** [comment]
Ah, I missed the `(...|)` part with the pipe. Thanks!

**Comment by tomasbjerre** [comment]
No problen :)
