### ISSUE TITLE
Add Pull Request Merg Commit Hash Variable

### ISSUE THREAD

**Issue by jogibear9988** [tomasbjerre/pull-request-notifier-for-bitbucket#198]
Is it possible to add a Varible with the Git Hash of the Resulting Merge commit?

**Comment by tomasbjerre** [comment]
There is PULL_REQUEST_MERGE_COMMIT but that is only available for merge-commits. Unless the PR is actually merged there the merge-commit hash is not available.

**Comment by nisaacson** [comment]
If you absolutely need access to the resulting merge commit, you could manually merge in your downstream build system and parse out the latest commit


See http://stackoverflow.com/questions/3216360/merge-update-and-pull-git-branches-without-using-checkouts

```sh
git checkout master
git merge origin/development
git rev-parse HEAD
# or if you need the merge commit in a variable
MERGE_COMMIT=$(git rev-parse HEAD)
```
