### ISSUE TITLE
Unable to configure Triggers to work except for BUTTON_TRIGGER

### ISSUE THREAD

**Issue by dmichaelwright** [tomasbjerre/pull-request-notifier-for-bitbucket#201]
Plugin Version : 2.55
BitBucket Server Version : v4.13.0 (localhost)

I've recently setup BitBucket Server, along with your plugin, and Jenkins. I setup a Trigger for kicking off a build as outlined in some of the well known tutorials. However, all of the triggers are not working for me except for the BUTTON_TRIGGER.

[Trigger Configurations]
![image](https://cloud.githubusercontent.com/assets/1211935/23184934/73d66340-f836-11e6-866d-2c0db985e4f9.png)

[Trigger Button Showing]
![image](https://cloud.githubusercontent.com/assets/1211935/23185161/433a0268-f837-11e6-94a6-df903cca53e8.png)

I've set the Trigger to kick off Jenkins with standard information : 
http://[JenkinsInstance]/buildByToken/buildWithParameters?job=[JenkinsJob]&token=[JenkinsToken]&PR_Title=${PULL_REQUEST_TITLE}&PR_FROM_URL=${PULL_REQUEST_TO_HTTP_CLONE_URL}&PR_FROM_REPO_NAME=${PULL_REQUEST_FROM_REPO_NAME}&PR_FROM_PROJECT_KEY=${PULL_REQUEST_FROM_REPO_PROJECT_KEY}&sha1=${PULL_REQUEST_FROM_HASH}&PR_TO_Branch=${PULL_REQUEST_TO_BRANCH}

[Result from Pushing Trigger Button]
![image](https://cloud.githubusercontent.com/assets/1211935/23186155/fb251d06-f83a-11e6-96ca-8718d17c3123.png)

[Jenkins Build]
![image](https://cloud.githubusercontent.com/assets/1211935/23186242/44ff956e-f83b-11e6-8762-af5b99db9ee6.png)

After selecting the Trigger Build button that I created, it kicks off a build to Jenkins everytime. However, new comments, new commits, etc.. are not kicking off builds. I'm also not getting any visual errors popup nor are the logs / debugging providing me any errors/stack traces. 

Let me know if you need any further information.

**Comment by dmichaelwright** [comment]
This is resolved. Removed the Button Trigger from the notification, and the rest started to work. End result, 2 Triggers, 1 for the button, and 1 for everything else. Hope this helps others.

Cheers.

**Comment by tomasbjerre** [comment]
Ok. This is because of the filter string and fulter regexp.

Your string will be empty for any trigger except for a button. So the regexp could have also been changed to also accept empty strings. Like ^(button title|)$
