### ISSUE TITLE
Pull Request Notifier for Bitbucket: project-level admin page displays objects from more than one project.

### ISSUE THREAD

**Issue by CHD-CM-Support-Users** [tomasbjerre/pull-request-notifier-for-bitbucket#202]
From: Sedlock, David 
Sent: Tuesday, 21 February, 2017 18:11
To: Tomas Bjerre <tomas.bjerre85@gmail.com>
Subject: RE: pull-request-notifier-for-bitbucket - project-level admin feature

Hi Tomas,

It provides everything to which the user has access, _not_ limited to the project. See email for an example. 

The page says it is for the SW_UGW project, but the repo belongs to a different project, SW_ARM and the button “SW_ARM cable CiCheck” was created and associated with the “cable” repo in the other project. The person using the page happens to be admin in both projects.

BTW, have you seen that the “buttons” are no longer displayed as buttons, but as entries in the “…” menu? We just upgraded to 4.13.
 
Regards,
David

From: Tomas Bjerre [mailto:tomas.bjerre85@gmail.com] 
Sent: Tuesday, 21 February, 2017 16:29
To: Sedlock, David <david.sedlock@intel.com>
Subject: Re: pull-request-notifier-for-bitbucket - project-level admin feature

The intention is to show everything within that project that the user has permission to configure.
Do you mean that it shows something that is not part of the project? Or something that the user should not have access to?

2017-02-21 16:23 GMT+01:00 Sedlock, David <david.sedlock@intel.com>:
Hi Tomas,
 
It looks to me as if the project-level configuration feature has not been implemented as I would have expected. What we have found is that in the project-level configuration, the user sees all the buttons, notifications and repos from the projects and repos in which he is admin, including his private repos. I would have expected the page to be limited to the objects defined for the given project and that only the global admin would have access to all of them.
 
Was this your intention or an accidental feature of the implementation?
 
Regards,
David

**Comment by tomasbjerre** [comment]
Should be fixed in 2.56. Open issue again if any problems.

**Comment by CHD-CM-Support-Users** [comment]
Hi Tomas,

Many thanks for the fast fix!

Regards,
David
