### ISSUE TITLE
Allow only specific users or group triggering a custom button?

### ISSUE THREAD

**Issue by SharonHart** [tomasbjerre/pull-request-notifier-for-bitbucket#204]
Is it possible to allow only users from a specific list / group, triggering a custom PR button?
The use-case is triggering a build job after one approval, and restrict some users from doing so.

**Comment by tomasbjerre** [comment]
You can use the filter string/regexp for limiting to specific users.

Groups is not possible right now.

**Comment by SharonHart** [comment]
Thanks Tomas!

**Comment by tomasbjerre** [comment]
Should be fixed in 2.56. There is now a PULL_REQUEST_USER_GROUPS variable to use in the filter.

Open issue again if any problems.
