### ISSUE TITLE
No notifications sending after install.   

### ISSUE THREAD

**Issue by brettswift** [tomasbjerre/pull-request-notifier-for-bitbucket#205]
After a fresh install I can't get any notifications or buttons appearing.  

 * Plugin version used.  v. 2.55
 * Bitbucket Server version  v4.8.6
 
I've got a configuration that I think should work.  But I'm not seeing anything sent to my requestb.in. 

To test I've also tried to configure a button to display on all conditions,  but it will never display.

I don't have admin access - I had to request our admin install this plugin.    Does the server need a reboot or something when this is installed? 

I should add that I'm trying this on a personal repo - under my profile.  If that has an impact. 

![image](https://cloud.githubusercontent.com/assets/723989/23436516/1c853ce6-fdc8-11e6-8df8-82e9ff601947.png)

![image](https://cloud.githubusercontent.com/assets/723989/23436536/2b6ae094-fdc8-11e6-8444-3416d0099022.png)

**Comment by tomasbjerre** [comment]
The picture shows BUTTON_TRIGGER not being checked. If that is not checked, a press of the button will not trigger notification and then that button will also not be shown.

If open and/or merge does not show in requestb.in then perhaps your Bitbucket Server installation does not have Internet access? Can you reach Requestb.in with curl from that server?

**Comment by brettswift** [comment]
So it's the start of a new day and I can see the button on the PR now.   Not sure what I did differently.

The network connectivity is a good thought.  I will investigate and get back to you. 

I am getting a 403 error code pop up (see below).   This implies that the 403 is being sent from pasteb.in   or if this plugin is hitting a bitbucket API and bitbucket is returning that. 

![image](https://cloud.githubusercontent.com/assets/723989/23463547/27caddf4-fe4f-11e6-86cb-3fde75f1256c.png)

**Comment by tomasbjerre** [comment]
Are you using chrome? If so you can find more details in the network tab. The response of the rest call made by the browser may include something interesting.

**Comment by brettswift** [comment]
Ya you might not have seen my comment as I updated the previous comment here.  I have the developer / network  tab open while clicking the button and it doesn't show me any 403 responses.

**Comment by tomasbjerre** [comment]
You are seeing this popup:
https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/blob/master/src/main/resources/pr-triggerbutton.js#L179

That means you got a 200 from Bitbucket Server. That includes:
https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/blob/master/src/main/java/se/bjurr/prnfb/presentation/dto/ButtonPressDTO.java#L14

That contains information about the triggered notification. That information says Bitbucket Server got a 403 when invoking its URL. There is more information about that invokation:
https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/blob/master/src/main/java/se/bjurr/prnfb/presentation/dto/NotificationResponseDTO.java

Also that is returned to the browser. But you have to check the network tab to see it.

**Comment by brettswift** [comment]
Awesome info.. thanks.   However, if you mean a network tab other than the one in the developer tools then I'm in the wrong spot.   This is all I see here: 

![image](https://cloud.githubusercontent.com/assets/723989/23464619/e684c284-fe52-11e6-9b97-26cda419adc4.png)

**Comment by tomasbjerre** [comment]
Yes this is it!

If you click on the "8" there. You should be see the response appear to the right. There you have a "preview" tab and you can see the json content.

**Comment by brettswift** [comment]
Gotcha, i was clicking the other link in that row.  It is showing a 403 to the pasteb.in. 

Which is kind of strange.   A 403 implies it hit the server and was forcibly rejected due to any reason, but does indicate the server was reached. 

So either pasteb.in is having an issue,  or something in between is issuing this 403.    I can curl my pasteb.in from my desktop.   I will have the gatekeepers of bitbucket try when they get to the office.

Thanks Tomas

**Comment by tomasbjerre** [comment]
Ok. Perhaps you need to specify a proxy, its supported in the plugin. Good luck!
