### ISSUE TITLE
Duplicate menu entries when using "Needs Work"

### ISSUE THREAD

**Issue by christiangalsterer** [tomasbjerre/pull-request-notifier-for-bitbucket#206]
When ever you switch between "Needs Work" and "Approve" an additional menu entry is created for the specified button action see screenshot

![duplicate](https://cloud.githubusercontent.com/assets/4999431/23578956/96957d44-00e2-11e7-9b9d-7b6bf6b6ea36.png)

The action is defined in the global configuration.
We use Bitbucket 4.13.0
Plugin version 2.56

**Comment by tomasbjerre** [comment]
Should be fixed in 2.57. Open issue again if any problems!

**Comment by christiangalsterer** [comment]
Ok, will test it tomorrow. Thanks for the quick fix.

**Comment by christiangalsterer** [comment]
Work like a charm, thanks for the quick fix.
