### ISSUE TITLE
Trigger button is not displayed in Pull Request?

### ISSUE THREAD

**Issue by aepfli** [tomasbjerre/pull-request-notifier-for-bitbucket#207]
Well we are curious because we did not change the config, just updated from 2.55 to 2.57! And now we do not have the trigger button anymore!

I tried recreating the button, changing some configuration, resaving! without any success!

# Informations
- Plugin-Version: 2.57
- Bitbucket-Version: 4.6.2
- Stacktrace: nothing special in there! (No exception or anything)

- Erros in Dev console: ( But i do not think they are related to this issue)
1. batch.js?hasADMINPermission=true&locale=en-US&nps-not-opted-out=true&supportedApplication=true:6105 Warning: It looks like you're using a minified copy of the development build of React. When deploying React apps to production, make sure to use the production build which skips development warnings and is faster. See https://fb.me/react-minification for more details.
o @ batch.js?hasADMINPermission=true&locale=en-US&nps-not-opted-out=true&supportedApplication=true:6105
2. batch.js?hasADMINPermission=true&locale=en-US&nps-not-opted-out=true&supportedApplication=true:6128 You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) to ensure you have the correct code for your production build.

# Button Config
Visibility: Everyone
Title: trigger FeatureBuild
Confirmation: yes
Confirmation message: Build has been Triggered! dont hit the button twice
Button Form: []

Button Form is always populated with [] on save!

**Comment by tomasbjerre** [comment]
This is also reported in #128, #197.

Very hard to troubleshoot. 

If you can debug pr-triggerbutton.js as suggested in #197 that would help alot!

**Comment by tomasbjerre** [comment]
Continue this discussion in #197
