### ISSUE TITLE
Unable to get the build status icon in the PR view

### ISSUE THREAD

**Issue by maniankara** [tomasbjerre/pull-request-notifier-for-bitbucket#209]
Plugin version: Version: 2.61
This is more of a question.
With the given instructions I managed to get the Button and Jenkins integration working. Great!
However, I am missing the build status icon (the green tick mark and others) near the *Learn more* link in my PR view.
Screenshot attached.
![screen shot 2017-03-27 at 16 36 34](https://cloud.githubusercontent.com/assets/1522438/24359786/0d701a18-130e-11e7-9ebb-4803ba371f7e.png)

**Comment by tomasbjerre** [comment]
That is part of the stash notifier plugin so not something to report here.

Den 27 mars 2017 15:54 skrev "Anoop Vijayan Maniankara" <
notifications@github.com>:

**Comment by maniankara** [comment]
Alright, got to know more. Thanks !
