### ISSUE TITLE
After Bitbucket migration from 4.0.3 to 4.13.0, the pull-request-notifier configurations disappeared

### ISSUE THREAD

**Issue by s-afroz** [tomasbjerre/pull-request-notifier-for-bitbucket#212]
We recently upgraded our BitBucket server from 4.0.3 to 4.13.0. Before upgrade, there were a number of PR build configurations for different repos using this plugin. And, they seem to be working fine after the migration....until we needed to take a look at one of the existing configurations. These configurations are nowhere to be found!!!

I understand that, with the latest version of this plugin, it is possible to configure the PR builds from repo or project level, as opposed to Bitbucket level, which was the case with our old configurations.

We checked that the projects/repos that the builds were configured for don't show the existing configurations either. But, they have to be somewhere, since the automated builds are working.

Please, let us know how we can access the existing PR build configurations after the upgrade.

**Comment by tomasbjerre** [comment]
Dont you see any notifications on the global admin page when you logon as a
system admin?

Den 18 apr. 2017 4:40 em skrev "s-afroz" <notifications@github.com>:

**Comment by s-afroz** [comment]
Hello Thomas,
I am always logged on as an admin. Where should I look for the
notifications? Don't see anything on the admin page.
I did look into the global configuration page for this plugin via 'Manage
Add-Ons' as before. There is no configuration there.

**Comment by s-afroz** [comment]
The only notification for this plugin is to upgrade it to the newest
version 2.62. Current version is: 2.61.

**Comment by tomasbjerre** [comment]
Are you logged in as admin or system admin?

**Comment by s-afroz** [comment]
I have both system admin and admin access. Logged on as a system admin.

**Comment by tomasbjerre** [comment]
If you browse to `/bitbucket/rest/prnfb-admin/1.0/settings/notifications` (perhaps without the `/bitbucket`) you just get an empty list back?

**Comment by s-afroz** [comment]
Yes. I get this, when tried on Chrome:

<status>
<status-code>404</status-code>
<message>
null for uri: http://xxxxbucket.xxxxxxx.com:xxxx
/rest/prnfb-admin/1.0/settings/notification
</message>
</status>

**Comment by s-afroz** [comment]
I think I missed the s at the end.
I do see a lot of data in the xml file with this URI:
http://xxxxbucket.xxxxxxx.com:xxxx/rest/prnfb-admin/1.0/
settings/notifications

**Comment by tomasbjerre** [comment]
You dont see any errors in Developer Tools console when you browse to
/plugins/servlet/prnfb/admin
?

In the network tab you should see this exact same rest-call. It does return a json-list right?

**Comment by s-afroz** [comment]
Yes, it was a json list, not xml.
Could you provide the exact URI or steps to trigger the call to
/plugins/servlet/prnfb/admin?

**Comment by tomasbjerre** [comment]
It the global admin page, in your case I guess it's: http://xxxxbucket.xxxxxxx.com:xxxx/plugins/servlet/prnfb/admin

**Comment by s-afroz** [comment]
Ok, got it.
I can see the http response header corresponding to the call:
http://xxxxxxxxxxx.xxxxxxxxx.com:xxxx/plugins/servlet/prnfb/admin
Its an xml. and the section for the configuration has default values.

**Comment by s-afroz** [comment]
I mean, html, not xml. Sorry about the mixups. Working on multiple issues.

**Comment by tomasbjerre** [comment]
You don't see any errors in Developer Tools console?
In the network tab you should see this exact same rest-call. It does return a json-list right?

**Comment by s-afroz** [comment]
The only rest call I see in the console tab is this one:

plugin-icon:1 GET http://xxxxx.xxxxx.com:xxxx
/rest/plugins/1.0/ch.mibex.stash.cra-key/media/plugin-icon 404 (Not Found)

**Comment by tomasbjerre** [comment]
You don't see any errors in Developer Tools console?

**Comment by s-afroz** [comment]
Just the above one about the plugin-icon not being found.

**Comment by s-afroz** [comment]
Also, 4 warnings about deprecated JS, and 1 warning as below:
"This page includes a password or credit card input in a non-secure
context. A warning has been added to the URL bar. For more information, see
https://goo.gl/zmWq3m."

**Comment by s-afroz** [comment]
Under the network tab, I did find a call to 'notifications' with following
URL:
"http://xxxxxxxxxxxxx.xxxxxxx.com:xxxx
/rest/prnfb-admin/1.0/settings/notifications

And, that response header has the jason list of triggers.

[image: Inline image 1]

**Comment by tomasbjerre** [comment]
And still when you click the notifications dropdown, you cannot select any notifications at all?

**Comment by tomasbjerre** [comment]
![dropdown-not](https://cloud.githubusercontent.com/assets/439571/25146353/dfca87c0-2473-11e7-978e-ceccd3fb910f.png)

**Comment by s-afroz** [comment]
Ah, I see them. So, they were hiding under the notifications drop-down list
this whole time !!!
I checked notifications list for projects and repos. But, missed it in the
admin settings page.
Thank you so much.
You can close this issue as resolved.

**Comment by tomasbjerre** [comment]
Great, np =)
