### ISSUE TITLE
Build trigger buttons are visible to end user even though they are marked for system admins only

### ISSUE THREAD

**Issue by s-afroz** [tomasbjerre/pull-request-notifier-for-bitbucket#213]
This is another symptom we are observing after migrating Bitbucket from 4.03 to 4.13.
The buttons appear in the pull-down list under '...' tab for the originator of the pull request.
But, the button does not show the text that was supposed to be associated with it (e.g. instead of "Build Product", it shows pr_triggerbutton). The build, however, does not get triggered even if selected by the originator.

For system admins, the options show up as expected (e.g. "Build Product" in the above case) and the build is triggered when selected.

**Comment by tomasbjerre** [comment]
This might be related to: https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/issues/197

I'll have a look later.

**Comment by tomasbjerre** [comment]
I tried to reproduce this but cannot do it.

It is most likely same as #197. The `pr-triggerbutton` that you see is just a placeholder that is always added by this plugin, and quickly replaced by any buttons that should be displayed.

So I'll close it and refer to #197.
