### ISSUE TITLE
Event trigger not working

### ISSUE THREAD

**Issue by lykabernardo** [tomasbjerre/pull-request-notifier-for-bitbucket#214]
Hello,

I need some help. Not sure what is wrong with my configuration. I am able to trigger the job using the button trigger BUTTON_TRIGGER but if i select the OPENED trigger and create a PR, it's not triggering the job.

 * Plugin version used: 2.62
 * Bitbucket Server version used: Atlassian Bitbucket v4.8.0
 * Your configuration: Please see attached screenshot

![1](https://cloud.githubusercontent.com/assets/20415900/25276387/e7a7db26-2691-11e7-9b01-14122776851f.JPG)
![2](https://cloud.githubusercontent.com/assets/20415900/25276388/e7a8255e-2691-11e7-8732-af519f6805d7.JPG)
![3](https://cloud.githubusercontent.com/assets/20415900/25276389/e7a8b2e4-2691-11e7-9bbb-50ea2a2b481e.JPG)

Regards,
Lyka

**Comment by tomasbjerre** [comment]
Looks ok. Nothing in the server log?

**Comment by lykabernardo** [comment]
I just checked the log file but there is nothing related to this.

**Comment by tomasbjerre** [comment]
If you ssh to the jenkins server and run same url with curl. Does that
trigger the job?

Also looks like you added something strange to the basic authentication
fields.

Den 21 apr. 2017 3:21 em skrev "lykabernardo" <notifications@github.com>:

I just checked the log file but there is nothing related to this.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/issues/214#issuecomment-296188870>,
or mute the thread

**Comment by lykabernardo** [comment]
I used ssh command below and it triggered the job.

curl -u <username>:<password> -X POST https://<jenkins base url>/job/LB_Test/job/pull_request/buildWithParameters?${EVERYTHING_URL}

As for the basic authentication, i just replaced my username with <enter username here> for the screenshot but i am using correct username and password.

**Comment by tomasbjerre** [comment]
You are openinga new PR? Not just re-opening an old one?

Den 21 apr. 2017 3:35 em skrev "lykabernardo" <notifications@github.com>:

I used ssh command below and it triggered the job.

curl -u : -X POST https:///job/LB_Test/job/pull_
request/buildWithParameters?${EVERYTHING_URL}

As for the basic authentication, i just replaced my username with for the
screenshot but i am using correct username and password.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/issues/214#issuecomment-296192271>,
or mute the thread

**Comment by lykabernardo** [comment]
Yes a new PR. I also tried to use the REOPENED trigger and reopen a declined PR but it's also not triggering the job.

**Comment by tomasbjerre** [comment]
Are you able to invoke https://requestb.in instead of Jenkins? Just to make sure its not a Jenkins thing.

**Comment by tomasbjerre** [comment]
You may browse to these URL:s to inspect exactly what has been persisted:

* http://localhost:7990/bitbucket/rest/prnfb-admin/1.0/settings
* http://localhost:7990/bitbucket/rest/prnfb-admin/1.0/settings/notifications

Nothing strange there?

**Comment by lykabernardo** [comment]
I tried accessing https://requestb.in and used the provided url to the url textbox of the pull request notification config but it didn't receive the request. I was able to invoke the requestb.in url from my laptop using the curl command.

As for the urls provided, i am not sure if the below result are expected.

http://localhost:7990/bitbucket/rest/prnfb-admin/1.0/settings
Page content: {"adminRestriction":"ADMIN","keyStoreType":"","shouldAcceptAnyCertificate":false}

http://localhost:7990/bitbucket/rest/prnfb-admin/1.0/settings/notifications
Page content: JSON format of the config. Nothing is strange

**Comment by tomasbjerre** [comment]
What if you try without the EVERYTHING_URL variable. Or just add whatever values you need.

Perhaps some variable causes a crash on resolve...

**Comment by lykabernardo** [comment]
I tried using below url but still not working for the other triggers.
https://<jenkins url>/job/LB_Test/job/pull_request/buildWithParameters?${PULL_REQUEST_ID}

For the button trigger it is still triggering the job.

**Comment by lykabernardo** [comment]
It seems that the issue is on the trigger as the button trigger is working. How do i check if it is really invoking the url when i create a pull request?

**Comment by tomasbjerre** [comment]
That is what https://requestb.in/ would tell you right?
There is also info-logging in the plugin: https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/blob/master/src/main/java/se/bjurr/prnfb/http/UrlInvoker.java#L159

**Comment by tomasbjerre** [comment]
The pull-requests, are they within the same repo or from forked repos?

**Comment by lykabernardo** [comment]
hello tomas, the pull requests are within the same repo. making pull request from different branch to the master branch.

**Comment by lykabernardo** [comment]
Hi tomas, thanks for all the help. This is working now. The configuration got messed up - didn't realize that notification config can be deleted. After deleting all the existing notification config and setup the only config i need, auto trigger is now working.

**Comment by amitme0014** [comment]
@lykabernardo thank u so much, i had a same issue... struggled for a week, without any clue. This solved my problem.,, thanks again .

**Comment by keshav-12** [comment]
Hi,

We are using bitbucket server as (scm)  and jenkins as (ci).
Here i am facing a issue with "pull request notifer plugin"
My basic intention is i want to create a new pr with "pull request notifier plugin" but i am unable to create a new PR

But i am able to run with existing triggered build link in pull request notifer plugin in url
"http://JENKINS URL/job/JOB NAME/job/kbirla%252FJenkinsf1/build?delay=0sec"

in url it should be generic for all pull request as same and it should use the same as for creating new "PR"

Thanks in Advance

**Comment by lykabernardo** [comment]
Hello @keshav-12 - I am not sure if you will be able to create a pull request using "pull request notifier plugin". I think this plugin will only invoke urls and not actually create a new PR.

**Comment by wynsoft** [comment]
Can you explain how you got this working? I only have one notification setup and it just doesn't trigger.
