### ISSUE TITLE
Bitbucket Server 5.0 support

### ISSUE THREAD

**Issue by ar613** [tomasbjerre/pull-request-notifier-for-bitbucket#215]
Bitbucket Server 5.0 has been released and an update is needed to support the new API.

**Comment by tomasbjerre** [comment]
I'm on it https://community.atlassian.com/t5/Bitbucket-questions/404-when-migrating-plugin-from-Bitbucket-4-to-5/qaq-p/586806#M16437

**Comment by tomasbjerre** [comment]
https://ecosystem.atlassian.net/servicedesk/customer/portal/14/DEVHELP-557

**Comment by tomasbjerre** [comment]
3.0 Released now!

**Comment by ramamyadam** [comment]
does 3.0 work for BB 5.16
