### ISSUE TITLE
Feature: add PREVIOUS_FROM_HASH and PREVIOUS_TO_HASH to variables

### ISSUE THREAD

**Issue by itay** [tomasbjerre/pull-request-notifier-for-bitbucket#220]
It would be very useful to be able to access the old hashes as well (what you're already using to compute "rescoped from/to" here: https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/blob/master/src/main/java/se/bjurr/prnfb/listener/PrnfbPullRequestAction.java), so that one can do comparisons on the content.

**Comment by tomasbjerre** [comment]
Released now. Open issue if any problems.
