### ISSUE TITLE
Pull Request Notifier Plugin does not trigger build on Jenkins

### ISSUE THREAD

**Issue by mochocki** [tomasbjerre/pull-request-notifier-for-bitbucket#224]
I have added custom button that is supposed to schedule a build on Jenkins.
However after clicking the button I receive an error message:

0 undefined
You may check network tab in web browser for exact URL and response.

In the network tab I see a request (ending HTTP 200):
https://bitbucketserver/rest/prnfb-admin/1.0/settings/buttons/a9db9f2a-e98c-48fd-9ec8-3f381395ea70/press/repository/203/pullrequest/1

and result:
{"confirmation":"on","notificationResponses":[{"notification":"95e67200-7149-4d48-b8ea-7d6be17d8c5c","notificationName":"review","status":0}]}

Nothing is logged in bitbucket log file.

 * Plugin version used. - 3.1
 * Bitbucket Server version used. - v4.8.1
 * Stack traces in Bitbucket Server log file. - none

**Comment by tomasbjerre** [comment]
I think there is logging from this line in the server log:
https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/blob/master/src/main/java/se/bjurr/prnfb/http/UrlInvoker.java#L374

And I would suggest reading the issue template and more specifically:
* Try to SSH to the Bitbucket Server machine and run same URL with Curl to make sure it's not a firewall issue.

**Comment by katke** [comment]
@mochocki Did you ever figure this out? I'm seeing the exact same issue, with the exact same response. I've just been using a RequestBin url, but it's never getting invoked even though the ajax request status code comes back as 200.

**Comment by CaraleeACN** [comment]
Any updates on this? I'm getting the same issue. I tested it on a Jenkins install that didn't use SSL and it worked fine, but the production install with SSL is failing. When I paste the URL in a browser on the server it triggers the job just fine and I've verified the Bitbucket application settings are correct. I'm on Bitbucket 4.12, we're prepping to upgrade to 5.12.

server.xml connector settings:
```xml
<Connector port="7990" protocol="HTTP/1.1"
                   connectionTimeout="20000"
                   useBodyEncodingForURI="true"
                   redirectPort="8443"
                   compression="on"
compressableMimeType="text/html,text/xml,text/plain,text/css,application/json,application/javascript,application/x-javascript" />
<Connector port="8443" maxHttpHeaderSize="8192" maxThreads="150" minSpareThreads="25" maxSpareThreads="75" 
	enableLookups="false" disableUploadTimeout="true" acceptCount="100" 
	scheme="https" secure="true" SSLEnabled="true" 
	clientAuth="false" 
	sslProtocol="TLS" 
	keystoreFile=<cert file> 
	keystorePass=<password> 
	keystoreType="PKCS12"/>
```
bitbucket.properties settings
```
server.port=8443
server.scheme=https
server.ssl.protocol=TLSv1.2
server.ssl.enabled=true
server.ssl.ciphers=HIGH:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!kRSA:!3DES:!DHE
```

**Comment by tomasbjerre** [comment]
Closing this issue because @mochocki is not responding.

@CaraleeACN  You should open a new issue and pay attention to the suggestions in the issue template.
