### ISSUE TITLE
Is it possible to stop two users triggering the build for the same PR?

### ISSUE THREAD

**Issue by Dhivyaa21** [tomasbjerre/pull-request-notifier-for-bitbucket#225]
We use this plugin to trigger Jenkins. We have a job that merges the PR branch into the upstream repo once the tests pass. The issue is when another user tries to build the same PR when the build for this PR is in progress. Is it possible to disable the trigger button when the build for a PR is in progress?

**Comment by tomasbjerre** [comment]
See: https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/issues/104

I'll close this one and refer to #104
