### ISSUE TITLE
Merge conflict trigger settings for events with PULL_REQUEST_ACTION = "MERGED"

### ISSUE THREAD

**Issue by johntconklin** [tomasbjerre/pull-request-notifier-for-bitbucket#228]
I don't know whether this is a bug, or simply my misunderstanding of how merge conflict triggers should work.

As I mentioned in issue #222, I use two PRNFB configuration definitions.  One definition is triggered when the merge is conflicting; the other definition is triggered when the merge is not conflicting. This allows me to pass either PULL_REQUEST_CONFLICTING=0 or PULL_REQUEST_CONFLICTING=1 (in addition to ${EVERYTHING_URL}) to my webhook handler.

While looking at my webook handler's logs, I saw some events for PULL_REQUEST_ACTION = "MERGED" with PULL_REQUEST_CONFLICTING=0 and others with PULL_REQUEST_CONFLICTING=1.  Fortunately, my downstream handlers for the "MERGED" action do not use the CONFLICTING variable,  so this issue is not currently causing any harm.  

I'm raising this issue as I expected "MERGED" actions would be by definition non-conflicting, and perhaps others who filter out merge conflicts may miss important events.

**Comment by tomasbjerre** [comment]
Sounds strange. Perhaps it happens when someone performs the merge locally,
resolving merge conflicts, and pushing the merge.

Den 1 juli 2017 04:09 skrev "J.T. Conklin" <notifications@github.com>:

**Comment by johntconklin** [comment]
Yes, it's odd.  Almost all of our pull request merges are handled by the "Workzone" plugin, so one would think all the pull request events would have the same CONFLICTING state.  It's a holiday week for me, so I won't be able to provide any additional information until next.

**Comment by johntconklin** [comment]
Is it possible that the event for PULL_REQUEST_ACTION = "MERGED" is being sent regardless of the merge conflict trigger filter?  After reviewing logs, it seems that one event is being sent from each of my PRNFB configurations for each MERGED action; thus the two events, one with CONFLICTING=0 the other with CONFLICTING=1

**Comment by tomasbjerre** [comment]
And both have action **MERGED** and the same commit hash:es in the hash-variables?

**Comment by johntconklin** [comment]
Yes.  All values in ${EVERYTHING_URL} are exactly the same.  The only difference between the two events is my PULL_REQUEST_CONFLICTING variable that I append to the URL query string.

**Comment by tomasbjerre** [comment]
Should be fixed in 3.2. Open issue again if any problems!
