### ISSUE TITLE
Configuration screen (GUI) not showing current config (always clean)

### ISSUE THREAD

**Issue by dpgaspar** [tomasbjerre/pull-request-notifier-for-bitbucket#230]
If things don't work as you expect, perhaps you should file an issue. But first, try troubleshooting it and provide as much info as possible. Here are some things that may help if added to an issue.

 * Plugin version used.
2.63
 * Bitbucket Server version used.
4.14.1
 * Stack traces in Bitbucket Server log file.
-
 * Any browser console log messages, you can find it in Developer Tools in Chome by pressing F12.

batch.js:57 DEPRECATED JS - Inline dialog constructor has been deprecated and will be removed in a future release. Use inline dialog 2 instead.   
     at HTMLDocument.<anonymous> (https://stag-stash.miniclip.com/s/df8ccf2725036ddbd3c274966b34037a-T/204910…rue&locale=en-US&nps-not-opted-out=true&supportedApplication=true:1227:216)
k @ batch.js:57
batch.js:57 DEPRECATED JS - Inline dialog constructor has been deprecated and will be removed in a future release. Use inline dialog 2 instead.   
     at HTMLDocument.<anonymous> (https://stag-stash.miniclip.com/s/df8ccf2725036ddbd3c274966b34037a-T/204910…rue&locale=en-US&nps-not-opted-out=true&supportedApplication=true:1283:316)

 * Screenshot of plugin configuration in your issue. Or the actual persisted settings:
If I go to the configuration of the plugin (at the repo level, after configuring everything), the configuration is displayed cleared, like it is the first time it is being configured.

I also noticed that, is i configured it again, a new bottom is displayed, are it will keep staking the configs.

I also noticed that if i uninstall the plugin, and then install it again, the previous PR trigger bottoms will still be displayed.

**Comment by tomasbjerre** [comment]
The things you see in the console log are from Bitbucket Server itself, not the plugin.

You may just be confused about how to find the saved config, see: https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/issues/116

Settings are not deletet on uninstall, that is intended.

**Comment by dpgaspar** [comment]
"The things you see in the console log are from Bitbucket Server itself, not the plugin."
Right

Is it supposed that after configuring the add-on, the same config page is empty? And if i configure it again i get a second bottom on the PR (double configs)?

A call to /rest/prnfb-admin/1.0/settings/notifications returns:

[{"headers":[],"method":"GET","name":"Jenkins","projectKey":"AGM","repositorySlug":"agar.io.mobile","triggerIfCanMerge":"ALWAYS","triggerIgnoreStateList":[],"triggers":["OPENED","BUTTON_TRIGGER","REOPENED","RESCOPED_FROM"],"url":"http://jenkinsmaster.miniclip.com/jenkins/git/notifyCommit?url=${PULL_REQUEST_TO_SSH_CLONE_URL}&branches=pr/${PULL_REQUEST_TO_BRANCH}&sha1=${PULL_REQUEST_FROM_HASH}&PULL_REQUEST_URL=${PULL_REQUEST_URL}&PULL_REQUEST_ID=${PULL_REQUEST_ID}","uuid":"3793acb1-cfbb-458d-af94-1229c06af935","postContentEncoding":"NONE"},{"headers":[],"method":"GET","name":"Notification","password":"XXXXXXX","projectKey":"DEVOPS","repositorySlug":"deploy_lib","triggerIfCanMerge":"ALWAYS","triggerIgnoreStateList":[],"triggers":["OPENED","BUTTON_TRIGGER","REOPENED","UPDATED"],"url":" http://localhost:8080/jenkins/git/notifyCommit?url=${PULL_REQUEST_TO_SSH_CLONE_URL}&branches=pr/${PULL_REQUEST_TO_BRANCH}&sha1=${PULL_REQUEST_FROM_HASH}&PULL_REQUEST_URL=${PULL_REQUEST_URL}&PULL_REQUEST_ID=${PULL_REQUEST_ID}","user":"XXXXXX@miniclip.com","uuid":"d8d47358-da65-4bd0-8d20-9bda5d8f0c94","postContentEncoding":"NONE"},{"headers":[],"method":"GET","name":"jenkinsserver-pull-request-trigger","triggerIfCanMerge":"ALWAYS","triggerIgnoreStateList":[],"triggers":["OPENED","BUTTON_TRIGGER","REOPENED","RESCOPED_FROM","UPDATED"],"url":" http://localhost:8080/jenkins/git/notifyCommit?url=${PULL_REQUEST_TO_SSH_CLONE_URL}&branches=pr/${PULL_REQUEST_TO_BRANCH}&sha1=${PULL_REQUEST_FROM_HASH}&PULL_REQUEST_URL=${PULL_REQUEST_URL}&PULL_REQUEST_ID=${PULL_REQUEST_ID}","uuid":"6f4007e9-dbd3-4ad7-8d3f-295ef6012273","postContentEncoding":"NONE"}]

The PR shows multiple bottoms:

<img width="277" alt="screen shot 2017-07-06 at 17 54 04" src="https://user-images.githubusercontent.com/4025227/27922827-42d88b58-6274-11e7-8bc8-aa9d379239cb.png">

**Comment by tomasbjerre** [comment]
You may just be confused about how to find the saved config, see: #116

**Comment by dpgaspar** [comment]
Ah! I got it, it's the dropdown i need to select it, thanks.
