### ISSUE TITLE
Project and Repo not shown correctly in dropboxes in global admin GUI

### ISSUE THREAD

**Issue by BrianKrohn** [tomasbjerre/pull-request-notifier-for-bitbucket#238]
After upgrading to 3.6 from 3.1 of the add-on, all settings were lost and saving settings doesn't actually save anything.  On Bitbucket 5.1.1.

**Comment by tomasbjerre** [comment]
Have a look at #116 . Some users are confused about having to press the dropdown to see the notifications.

**Comment by BrianKrohn** [comment]
I got some clarification from the devs that reported this too me.  In the Notification section, under Trigger, the Project and Repository dropdowns always say "Any".  When you change them and click Save, they revert to "Any".

**Comment by tomasbjerre** [comment]
This is impossible to work with without you following the issue template.

Den 30 juli 2017 18:45 skrev "Brian Krohn" <notifications@github.com>:

**Comment by BrianKrohn** [comment]
Sorry.  I am new to this.  Where is the template?

**Comment by tomasbjerre** [comment]
https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/blob/master/ISSUE_TEMPLATE

**Comment by tomasbjerre** [comment]
Upgrading from Stash to BBS is not something that I will spend time on fixing. And probably not accept a PR for. There are very few users doing that now.

I cannot confirm that "saving settings doesn't actually save anything". I can confirm that the project and repo dropboxes dont get populated correctly. I also see an extra notification being created when I change the project.

**Comment by BrianKrohn** [comment]
I'm not upgrading from Stash (going from BBS 4.8.4 to 5.1.1) so that's fine.  The Project and Repo dropdowns change to "Any" when you attempt to update an existing Notification, so I think that fits your description.

There are no error messages or exceptions in the logs that I could find.  I'd be happy to share anything you need.  I can also replicate this on my test server, so if there's anything you want me to try, let me know.

**Comment by tomasbjerre** [comment]
I think this was introduced in 3.5. You may try 3.4 by downloading it from here: https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/releases I think that is the most recent version without this problem.

**Comment by tomasbjerre** [comment]
The project and repo settings should now be saved correctly. Released in 3.7. Was that all here or are you actually not able to save anything at all?

**Comment by BrianKrohn** [comment]
My original issue was solved with your note about 116.  That's when we found the Project and Repo dropdowns weren't saving when a Notification was updated.  I just verified that your change fixed it.  Thanks for the quick response and fix.  I was not expecting it.  I will try to follow your template next time, if we ever come across an issue.  Thanks again.

**Comment by tomasbjerre** [comment]
Great no problem!

**Comment by annmcd** [comment]
Could you attach an example of saving a new or exsting notificaiton via rest api
