### ISSUE TITLE
PULL_REQUEST_MERGE_COMMIT variable is empty

### ISSUE THREAD

**Issue by Dmitriyev** [tomasbjerre/pull-request-notifier-for-bitbucket#244]
Hey, @tomasbjerre!
I'm using plugin v3.13 with Bitbucket v5.2.1.

I'm trying to configure jenkins notification after PR has merged.
![untitled](https://user-images.githubusercontent.com/14370767/29605867-19b08cc0-87f5-11e7-86e5-bab0c17375a1.png)
I need to pass merged commit to jenkins job. But it doesn't works.
![untitled](https://user-images.githubusercontent.com/14370767/29606085-cb5ea420-87f5-11e7-82e2-96304cdc4b4b.png)
Job URL triggering works correctly, when i'm doing it from browser, but stash passes empty string.
Build started by plugin:
![untitled](https://user-images.githubusercontent.com/14370767/29606323-9193e1a0-87f6-11e7-938a-e51ab7c3a3b7.png)
From browser:
![untitled](https://user-images.githubusercontent.com/14370767/29606266-647afe42-87f6-11e7-8576-ae794e9a098a.png)

**Comment by tomasbjerre** [comment]
If you also check *comment* and add a comment to a merged PR. Then do you get the commit hash of the merge commit?

**Comment by Dmitriyev** [comment]
No. If I check or add comment to  a merged PR, jenkins build doesn't makes triggered.

**Comment by tomasbjerre** [comment]
Just tried it on https://requestb.in/ and it works for me. When PR is merged the commit hash is there.

I would suggest it is something with your Jenkins.
Can you trigger a build from a curl command?
See also: https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/blob/master/README_jenkins.md

**Comment by Dmitriyev** [comment]
I tried to trigger job from a curl and it doesn't works. Apparently you was right about problem in my Jenkins.
Thanks.

**Comment by Dmitriyev** [comment]
I have fixed the problem. It had two causes:
1) There was a white space in job's name;
2) Some Jenkins's security settings.

Thanks.
