### ISSUE TITLE
Provide link to Issues to Atlassian Marketplace?

### ISSUE THREAD

**Issue by hdohlmann** [tomasbjerre/pull-request-notifier-for-bitbucket#246]
We would like to use your plugin. Unfortunately our company has a policy of not installing plugins from Atlassian Marketplace that are marked Unsupported.

All it requires for a plugin to be marked Supported, is that the Vendor (developer) provides a link to a support page. Read this [Atlassian Marketplace FAQ entry](https://www.atlassian.com/licensing/marketplace?_ga=2.16237237.228281603.1504086339-626609563.1488362238#generalmarketplacequestions-9) for description of when Atlassian marks a plugin Supported.

Looking at other plugins that are supported, for instance the "[Webhook to Jenkins for Bitbucket](https://marketplace.atlassian.com/plugins/com.nerdwin15.stash-stash-webhook-jenkins/server/support)", a link to the Issues page here at Github seems to be enough.

Could you please be bothered to tell Atlassian that the support link for your plugin should point at the Issues page?

**Comment by tomasbjerre** [comment]
I changed it now!

**Comment by hdohlmann** [comment]
That was quick! Thanks a lot :-)
