### ISSUE TITLE
Using approved trigger generates several build requests

### ISSUE THREAD

**Issue by pemercer** [tomasbjerre/pull-request-notifier-for-bitbucket#248]
* Plugin version used. 2.67 
 * Bitbucket Server version used. 4.14.5

If I have specified a PR needs X users to approve before merge PR Notifier needs to use that value and only send notification when final approval is given. Currently if I saw 3 approvals are needed to merge each person who approves generates a notification and a build is started.

**Comment by tomasbjerre** [comment]
You can probably solve that with PULL_REQUEST_REVIEWERS_APPROVED_COUNT in the filter string and the number of approvals in the filter regexp.

**Comment by pemercer** [comment]
Thanks, knew there had to be an easy answer.
