### ISSUE TITLE
Trigger merged does not work

### ISSUE THREAD

**Issue by hubertli** [tomasbjerre/pull-request-notifier-for-bitbucket#253]
Bitbucket v4.11.0
pull-request-notifier-for-bitbucket 2.67 

I configured a notification. It works well to trigger a Jenkins job when the pull request is opened and updated for all projects and repositories, but it does not work for merged event when I added "MERGED" in the triggers, but it sill works on the opened and updated events. 

I configured another notification for the merged event only, it does not work. I also copied the working notification to a new one, and only updated the Jenkins job name, this new notification still does not work. I ran `tail -f /var/log/syslog` in the Bitbucket server, and could only find the logs for the old working notification, but no logs for all new notifications.

**Comment by tomasbjerre** [comment]
I was able to invoke a URL with merge event configured:
https://requestb.in/wkrr9twk?inspect

I added a notification with URL like:
https://requestb.in/wkrr9twk?${EVERYTHING_URL}

And GET method.

**Comment by hubertli** [comment]
Hi Tomas,

Thank you for your test. I still can't fix the issue. Could you please let me know what I can do for the issue? e.g. what is the logs? possible conflicts? I recalled I can add multiple notifications before, including merged event, but now only the old notification works. In the meantime, nothing was changed in the Bitbucket.

Thank you,
Hubert

**Comment by hubertli** [comment]
Hi Tomas,

I fixed the problem by configured username and password in "Basic authentication". I didn't configured it before because the comments confused me: KEEP_THIS_TO_LEAVE_UNCHANGED.

Thank you,
Hubert

**Comment by tomasbjerre** [comment]
ok great!
