### ISSUE TITLE
Trigger for pull request DELETE

### ISSUE THREAD

**Issue by ggrierson** [tomasbjerre/pull-request-notifier-for-bitbucket#259]
Plugin version : 3.13
BB Server: 5.3.1

Please can you add a trigger for pull request "DELETE". I need to do some clean up in Bamboo if the PR is deleted, not just declined and it seems this trigger is missing from the list.

It seems this event is available [as per docs here](https://developer.atlassian.com/static/javadoc/bitbucket-server/5.5.1/api/reference/com/atlassian/bitbucket/event/pull/PullRequestDeletedEvent.html).
Thanks.

**Comment by tomasbjerre** [comment]
Released in 3.18. Open issue again if not working.
