### ISSUE TITLE
Option to ignore PR if status is NEEDS WORK

### ISSUE THREAD

**Issue by asgerjensen** [tomasbjerre/pull-request-notifier-for-bitbucket#260]
Hi,

Maybe I am just not looking hard enough, but it would be nice if I could filter out PRs for build, if they have the status NEEDS WORK.

Ideally, if I have reviewed something, and want the author to push some fixes before I merge it, I dont need the build server to rebuild this branch when one of the other PRs are merged to `develop`

Is it already there under some other name, perhaps?

**Comment by tomasbjerre** [comment]
Should be possible with the filter text and regexp. The text would be `${PULL_REQUEST_REVIEWERS_NEEDS_WORK_COUNT}` and the regexp `0`

**Comment by asgerjensen** [comment]
Worked like a charm, btw. Thanks.
