### ISSUE TITLE
Two Jenkins jobs run when PR created

### ISSUE THREAD

**Issue by hax0rdlux3** [tomasbjerre/pull-request-notifier-for-bitbucket#265]
SonarQube 6.5, on prem

Jenkins (latest), running locally/on prem

BitBucket v 4.14.5

I have the following workflow:

Two jobs in Jenkins - one handles the PR scan and the other handles the scans for merging of branches into 'master' for baseline scan

First job in Jenkins is for scans on PR creation - it is getting called (or at least running) twice for each PR creation - not sure why, just began happening - configuration is:

Merge condition  trigger for any merge condition -- selected

Triggers - Opened (only one selected)

URL config "JENKINSSERVER/job/SonarQubeStaticAnalysis/buildWithParameters?PR_ID=${PULL_REQUEST_ID}"

Calls Parameterized Job, sending in PR

Branch specifier is: origin/feature/*

Don't encode Params in URL

Again, two of the PR scan jobs are running on PR creation - insights appreciated.

**Comment by tomasbjerre** [comment]
Why `origin/feature/*` ? I would pass the variable `PULL_REQUEST_FROM_BRANCH`. Not sure how Jenkins treats that `*`.

Also, as a system admin, browse to `/bitbucket/rest/prnfb-admin/1.0/settings/notifications` to inspect all configured notifications. To make sure there are not a duplicate for this job.

Another suggestion would be to change your notification to pass some dummy string, and maby print that string in the job. To determine if it is the same notification that triggers the job twice or if only one of the triggered runs are from that notification.

I would also not use SonarQube as I believe it just adds complexity to the infrastructure. I would report the violations directly to the PR from Bitbucket using this one: https://wiki.jenkins.io/display/JENKINS/Violation+Comments+to+Bitbucket+Server+Plugin

**Comment by hax0rdlux3** [comment]
fantastic advice - I will start on those changes shortly! thx
