### ISSUE TITLE
How to get trigger "UPDATED" to work?

### ISSUE THREAD

**Issue by cantSleepNow** [tomasbjerre/pull-request-notifier-for-bitbucket#266]
Hi,
first let me just thank you for the work on the plugin!

* Plugin version 3.18
* Bitbucket Server version 5.6.2

The "UPDATED" trigger doesn't work. If I only add for example "COMMENTED" and make a comment on the pull request, the jenkins job get's triggered, so I think it's safe to assume that the rest of the config(url,crumb,etc) is correct. (also works on "OPENED" for example)

Could it be that the bitbucket is not emitting an event or something? I do see the "updated" highlighted text in the PR overview..

After I do git push (to the branch for which a PR is already created) I see the following  entries in bitbucket log
```
127.0.0.1 | http | i@1TR6DVFx675x434x0 | - | 2017-12-29 11:15:12,024 | "POST /scm/proj/repoxz.git/git-receive-pack HTTP/1.1" | "" "git/2.11.0" | - | - | - | - | - | - | 
127.0.0.1 | http | o@1TR6DVFx675x434x0 | vlada | 2017-12-29 11:15:12,252 | "POST /scm/proj/repoxz.git/git-receive-pack HTTP/1.1" | "" "git/2.11.0" | 200 | 536 | 164 | push | 228 | - | 
```

**Comment by tomasbjerre** [comment]
Maby you want the *rescoped* events? Rescope is what happens when commits are pushed.

**Comment by cantSleepNow** [comment]
Yup, that works - thanks a lot! Can't believe I missed that one. Please close this issue.

And keep up the great work !

**Comment by cuzkey** [comment]
What is updated use for then?

**Comment by tomasbjerre** [comment]
It is "Event that is raised when the pull request title or description are updated.".
