### ISSUE TITLE
PRs not triggering build. Manually Clicking the button is not working too.

### ISSUE THREAD

**Issue by ashishyadav13237** [tomasbjerre/pull-request-notifier-for-bitbucket#283]
If things don't work as you expect, perhaps you should file an issue. But first, try troubleshooting it and provide as much info as possible. Here are some things that may help if added to an issue.

 * Plugin version used. Installed version: 3.18
 * Bitbucket Server version used. v5.5.1 
 * Stack traces in Bitbucket Server log file.

What is 'KEEP_THIS_TO_LEAVE_UNCHANGED'?

**Comment by ashishyadav13237** [comment]
![screen shot 2018-04-20 at 2 23 24 pm](https://user-images.githubusercontent.com/32548437/39069819-b3df033a-44a6-11e8-88ab-006d27f6a5d1.png)
![screen shot 2018-04-20 at 2 23 18 pm](https://user-images.githubusercontent.com/32548437/39069820-b3f7e5b2-44a6-11e8-984d-14b3f25a61d1.png)
![screen shot 2018-04-20 at 2 23 11 pm](https://user-images.githubusercontent.com/32548437/39069821-b40f79c0-44a6-11e8-9aab-97fd88ae832d.png)
![screen shot 2018-04-20 at 2 23 06 pm](https://user-images.githubusercontent.com/32548437/39069822-b42e139e-44a6-11e8-9772-281d656c6939.png)
![screen shot 2018-04-20 at 2 23 01 pm](https://user-images.githubusercontent.com/32548437/39069823-b4445348-44a6-11e8-95da-96befb7269a0.png)
![screen shot 2018-04-20 at 2 22 47 pm](https://user-images.githubusercontent.com/32548437/39069824-b4622c6a-44a6-11e8-9f12-6785f45c3d19.png)
![screen shot 2018-04-20 at 2 22 37 pm](https://user-images.githubusercontent.com/32548437/39069825-b47cfac2-44a6-11e8-846e-c417584607fd.png)

**Comment by ashishyadav13237** [comment]
The 'button' stopped working this morning and no changes have been made on our internal bitbucket-server

**Comment by tomasbjerre** [comment]
If you do not have access to the server log files, one idea is to:

 * Also trigger on button pressed, and add a button
 * Open a PR
 * Open Chrome developer tools, F12
 * Press the button in the PR
 * Check the response in the network tab in Chrome. See if it contains something interesting

**Comment by ashishyadav13237** [comment]
When I enable the confirmation button, I am getting a 401. Where is this coming from?
Integration Button
 
401 http://ci-webui.fm.com/job/component/job/integration/job/fm-navigation/buildWithParameters?token=ZURDFwx7&pullRequestDescription=Limit+primary+header+length%2C+and+truncate+where+applicable.%0D%0A%0D%0AResolves%3A+SIP-14885&BUTTON_FORM_DATA=&BUTTON_TRIGGER_TITLE=Trigger+Integration+Testing&INJECTION_URL_VALUE=&PULL_REQUEST_ACTION=BUTTON_TRIGGER&PULL_REQUEST_AUTHOR_DISPLAY_NAME=Sean+McNamara&PULL_REQUEST_AUTHOR_EMAIL=sean.mcnamara%40fm.com&PULL_REQUEST_AUTHOR_ID=1355&PULL_REQUEST_AUTHOR_NAME=smcnamara&PULL_REQUEST_AUTHOR_SLUG=smcnamara&PULL_REQUEST_COMMENT_ACTION=&PULL_REQUEST_COMMENT_ID=&PULL_REQUEST_COMMENT_TEXT=&PULL_REQUEST_FROM_BRANCH=bugfix%2FSIP-14885&PULL_REQUEST_FROM_HASH=abfb9d3e&PULL_REQUEST_FROM_HTTP_CLONE_URL=https%3A%2F%2Fashishyadav%40bb.fm.com%2Fscm%2Fwebc%2Ffm-navigation.git&PULL_REQUEST_FROM_ID=refs%2Fheads%2Fbugfix%2FSIP-14885&PULL_REQUEST_FROM_REPO_ID=441&PULL_REQUEST_FROM_REPO_NAME=fm-navigation&PULL_REQUEST_FROM_REPO_PROJECT_ID=401&PULL_REQUEST_FROM_REPO_PROJECT_KEY=WEBC&PULL_REQUEST_FROM_REPO_SLUG=fm-navigation&PULL_REQUEST_FROM_SSH_CLONE_URL=ssh%3A%2F%2Fgit%40bb.fm.com%2Fwebc%2Ffm-navigation.git&PULL_REQUEST_ID=140&PULL_REQUEST_MERGE_COMMIT=&PULL_REQUEST_PARTICIPANTS_APPROVED_COUNT=0&PULL_REQUEST_PARTICIPANTS_EMAIL=&PULL_REQUEST_PREVIOUS_FROM_HASH=&PULL_REQUEST_PREVIOUS_TO_HASH=&PULL_REQUEST_REVIEWERS=Bill+Vochatzer%2CCaleb+Kniffen%2CCharles+Coleman%2CCharlie+Mehrer%2CJesse+D%27Angelo%2CJustin+Wright%2CWill+Pracht&PULL_REQUEST_REVIEWERS_APPROVED_COUNT=2&PULL_REQUEST_REVIEWERS_APPROVED_DISPLAY_NAME=Caleb+Kniffen%2CJustin+Wright&PULL_REQUEST_REVIEWERS_APPROVED_EMAIL=caleb.kniffen%40fm.com%2Cjustin.wright%40fm.com&PULL_REQUEST_REVIEWERS_APPROVED_NAME=ckniffen%2Cjwright&PULL_REQUEST_REVIEWERS_APPROVED_SLUG=ckniffen%2Cjwright&PULL_REQUEST_REVIEWERS_EMAIL=bill.vochatzer%40fm.com%2Ccaleb.kniffen%40fm.com%2Ccharles.coleman%40fm.com%2Ccharlie.mehrer%40fm.com%2Cjesse.dangelo%40fm.com%2Cjustin.wright%40fm.com%2Cwill.pracht%40fm.com&PULL_REQUEST_REVIEWERS_ID=1253%2C1460%2C1484%2C1512%2C1817%2C63%2C651&PULL_REQUEST_REVIEWERS_NEEDS_WORK_COUNT=0&PULL_REQUEST_REVIEWERS_NEEDS_WORK_DISPLAY_NAME=&PULL_REQUEST_REVIEWERS_NEEDS_WORK_EMAIL=&PULL_REQUEST_REVIEWERS_NEEDS_WORK_NAME=&PULL_REQUEST_REVIEWERS_NEEDS_WORK_SLUG=&PULL_REQUEST_REVIEWERS_SLUG=bvochatzer%2Cccoleman%2Cckniffen%2Ccmehrer%2Cjdangelo%2Cjwright%2Cwpracht&PULL_REQUEST_REVIEWERS_UNAPPROVED_COUNT=5&PULL_REQUEST_REVIEWERS_UNAPPROVED_DISPLAY_NAME=Bill+Vochatzer%2CCharles+Coleman%2CCharlie+Mehrer%2CJesse+D%27Angelo%2CWill+Pracht&PULL_REQUEST_REVIEWERS_UNAPPROVED_EMAIL=bill.vochatzer%40fm.com%2Ccharles.coleman%40fm.com%2Ccharlie.mehrer%40fm.com%2Cjesse.dangelo%40fm.com%2Cwill.pracht%40fm.com&PULL_REQUEST_REVIEWERS_UNAPPROVED_NAME=bvochatzer%2Cccoleman%2Ccmehrer%2Cjdangelo%2Cwpracht&PULL_REQUEST_REVIEWERS_UNAPPROVED_SLUG=bvochatzer%2Cccoleman%2Ccmehrer%2Cjdangelo%2Cwpracht&PULL_REQUEST_STATE=OPEN&PULL_REQUEST_TITLE=Limit+Primary+Header+Length&PULL_REQUEST_TO_BRANCH=master&PULL_REQUEST_TO_HASH=773ee7f0ec2&PULL_REQUEST_TO_HTTP_CLONE_URL=https%3A%2F%2Fashishyadav%40bb.fm.com%2Fscm%2Fwebc%2Ffm-navigation.git&PULL_REQUEST_TO_ID=refs%2Fheads%2Fmaster&PULL_REQUEST_TO_REPO_ID=441&PULL_REQUEST_TO_REPO_NAME=fm-navigation&PULL_REQUEST_TO_REPO_PROJECT_ID=401&PULL_REQUEST_TO_REPO_PROJECT_KEY=WEBC&PULL_REQUEST_TO_REPO_SLUG=fm-navigation&PULL_REQUEST_TO_SSH_CLONE_URL=ssh%3A%2F%2Fgit%40bb.fm.com%2Fwebc%2Ffm-navigation.git&PULL_REQUEST_URL=https%3A%2F%2Fbb.fm.com%2Fprojects%2FWEBC%2Frepos%2Ffm-navigation%2Fpull-requests%2F140&PULL_REQUEST_USER_DISPLAY_NAME=Ashish+Yadav&PULL_REQUEST_USER_EMAIL_ADDRESS=ashish.yadav%40fm.com&PULL_REQUEST_USER_GROUPS=&PULL_REQUEST_USER_ID=804&PULL_REQUEST_USER_NAME=ashishyadav&PULL_REQUEST_USER_SLUG=ashishyadav&PULL_REQUEST_VERSION=0
 
You may check network tab in web browser for exact URL and response.

**Comment by ashishyadav13237** [comment]
<img width="739" alt="screen shot 2018-04-20 at 7 35 22 pm" src="https://user-images.githubusercontent.com/32548437/39085272-d94624c4-4545-11e8-8823-86f085dfd698.png">

**Comment by tomasbjerre** [comment]
https://httpstatuses.com/401

So the credentials you have in "Basic authentication" or in "Proxy" are wrong.

**Comment by ashishyadav13237** [comment]
Thanks. Why is it using the credentials in "Basic authentication" or in "Proxy" if we have a token? As for the auth, why does it state "KEEP_THIS_TO_LEAVE_UNCHANGED"?

**Comment by ashishyadav13237** [comment]
Lastly, we didn't change the id/pwd so why are we getting a 401 now :)

**Comment by tomasbjerre** [comment]
Remove it, save it again, try again.

Perhaps your browser recognized it as a login form and added some password...

**Comment by haroonzone** [comment]
Bitbucket server: v5.11.1
Bitbucket server notifier: v2.62

We are consistently seeing that for any new Jenkins pipeline for a specific branch, a PR job is not being triggered. We get the following response when trying to trigger a job by clicking the button.

content":"No git jobs using repository: ssh://git@git.host.com/tstau/test-data.git and branches: pr_master\nNo Git consumers using SCM API plugin for: ssh://git@git.host.com/tstau/test-data.git\

**Comment by tomasbjerre** [comment]
@haroonzone that should be reported in its own issue.

**Comment by haroonzone** [comment]
This was already open and looked similar. anyway reporting a new issue.

**Comment by tomasbjerre** [comment]
Closing this one since there has been no response to my suggested fix posted 21 april.
