### ISSUE TITLE
Post request not working in pull request notification

### ISSUE THREAD

**Issue by ivy67941842** [tomasbjerre/pull-request-notifier-for-bitbucket#291]
* Plugin version : don't konw how to get 
 * Bitbucket Server version : Atlassian Bitbucket v4.14.12
 * Stack traces in Bitbucket Server log file: have no access to bitbucket server 
 * Any browser console log messages: 
{"notificationResponses":[{"content":"{\"timestamp\":1532068297440,\"status\":500,\"error\":\"Internal Server Error\",\"exception\":\"com.netflix.zuul.exception.ZuulException\",\"message\":\"GENERAL\"}","notification":"7c231129-2ab8-46d3-9983-b19cb7da7962","notificationName":"Update Status to DevOps status service","status":500,"uri":"https://XXXXXXXX/task/status"}]}
 * Your configuration:
   URL: https://XXXXXXXX/task/status
   Post content: {  \"type\":  \"bitbucket\",  \"TASK_ID\":  \"123\",  \"status\":  \"Merged\"}
  Headers:  accept   */*
                   Content-Type   application/json
 * If the system you are trying to notify does not seem to get notified:
Failed

The event can trigger this notification but http request returned 500 error. We can trigger successfully with curl command on my own laptop. But it doesn't work in bitbucket.
How can I verify the request bitbucket really send out to is correct?
Any other suggestion?Thanks!

**Comment by tomasbjerre** [comment]
Perhaps you can let the plugin post to: https://requestbin.fullcontact.com/

Are you using a proxy? Perhaps it is a proxy returning 500 and not the actual target system.

**Comment by tomasbjerre** [comment]
No response, closing.
