### ISSUE TITLE
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job

### ISSUE THREAD

**Issue by prrichard** [tomasbjerre/pull-request-notifier-for-bitbucket#292]
We are using v3.22 in our Bitbucket instance, for cross-repo PRs we would like to have the plugin trigger build in Jenkins when commits are made in the source branch of the PR.

This is happening inconsistently. It is working sometimes, and for few occasions getting the below error - 

git fetch --tags --progress https://xxx.com/scm/xxx/ds.git +refs/heads/*:refs/remotes/origin/* # timeout=30
08:46:09  > git rev-parse "a942a093528847a2c8e6c9823779e506762f686a^{commit}" # timeout=120
08:46:09  > git rev-parse "origin/a942a093528847a2c8e6c9823779e506762f686a^{commit}" # timeout=120
08:46:09  > git rev-parse "a942a093528847a2c8e6c9823779e506762f686a^{commit}" # timeout=120
08:46:09 ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.

The refspec: is set to +refs/pull-requests/*/from:refs/remotes/* in the Jenkins Job, but we find that the 

git fetch --tags --progress https://xxx.com/scm/xxx/ds.git +refs/heads/*:refs/remotes/origin/* # timeout=30

is using a different refspec.

How is this possible?

Please how to ensure Jenkins job is triggered without fail consistently when changes happen in the source branch.

Regards,
Prince

**Comment by tomasbjerre** [comment]
I would create an ordinary pipeline job in Jenkins. Have it triggered remotely. Make it parameterized. Have a simple pipeline step that does the git stuff. As described here: https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/blob/master/README_jenkins.md

It looks like you are using the git plugin and in my experience that is just making things complex and hard to troubleshoot.

In anyway, this does not sound like a problem with the plugin. Rather a problem in Jenkins. And you can ask such questions on Stackoverflow.
