### ISSUE TITLE
Pull request build is not triggered on Jenkins when setting up a pipeline for a new branch.

### ISSUE THREAD

**Issue by haroonzone** [tomasbjerre/pull-request-notifier-for-bitbucket#293]
* Bitbucket server: v5.11.1
* Bitbucket server notifier: v2.62

We are consistently seeing that for any new Jenkins pipeline for a specific branch, a PR job is not being triggered. We get the following response when trying to trigger a job by clicking the button.

content":"No git jobs using repository: ssh://git@git.host.com/tstau/test-data.git and branches: pr_master\nNo Git consumers using SCM API plugin for: ssh://git@git.host.com/tstau/test-data.git\

**Comment by tomasbjerre** [comment]
So Jenkins is being invoked. Nothing in your description suggests there is anything wrong with this plugin. Nothing describing what you expect it to do and what it did.

**Comment by haroonzone** [comment]
Title of the bug says that Jenkins is not being invoked and the response is also in the defect description.

**Comment by tomasbjerre** [comment]
No title says `Pull request build is not triggered on Jenkins`. It might be invoked but still the job is not triggered.

The response is coming from Jenkins. Which also shows that this is not an issue with the plugin, but an issue with how you are using Jenkins.

**Comment by haroonzone** [comment]
Thank you for making the distinction between invoking and triggering. I can see that the notification is being sent to Jenkins but the job is not triggered. This certainly means the issue is with the Jenkins configuration. We are using SCM checkout step in the pipeline and configuration of the step is as follows.

`checkout changelog: false, poll: false, scm: [$class: 'GitSCM', branches: [[name: '*/pr_master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'CloneOption', depth: 0, noTags: false, reference: '', shallow: false, timeout: 180], [$class: 'PreBuildMerge', options: [mergeRemote: 'origin', mergeTarget: 'master']], [$class: 'CleanBeforeCheckout']], submoduleCfg: [], userRemoteConfigs: [[name: 'origin', refspec: '+refs/heads/*:refs/remotes/origin/*', url: 'ssh://git@git.host.com/tstau/test-data-builders.git']]]`

and the job is not being triggered. is this something that you have noticed before and can help out?

**Comment by tomasbjerre** [comment]
I would replace the `url`, `mergeRemote` and `branches` with parameters and let this plugin provide those variables. But this is not the place for Jenkins support.

**Comment by haroonzone** [comment]
thank you for the pointers. 👍
