### ISSUE TITLE
Pull request notifier plugin for creating new PR

### ISSUE THREAD

**Issue by keshav-12** [tomasbjerre/pull-request-notifier-for-bitbucket#298]
Hi,

We are using bitbucket server as (scm) and jenkins as (ci).
Here i am facing a issue with "pull request notifer plugin"
My basic intention is i want to create a new pr with "pull request notifier plugin" but i am unable to create a new PR

But i am able to run with existing triggered build link in pull request notifer plugin in url
URL-
"http://JENKINS URL/job/JOB NAME/job/kbirla%252FJenkinsf1/build?delay=0sec"

in url it should be generic for all pull request as same and it should use the same as for creating new "PR"

Thanks in Advance

**Comment by tomasbjerre** [comment]
There are a bunch of hints in the issue template: https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/blob/master/ISSUE_TEMPLATE

I'm closing this issue as there is nothing in it that can be investigated.
