### ISSUE TITLE
PRN fires on button trigger, but not OPENED or UPDATED

### ISSUE THREAD

**Issue by davidmichaelkarr** [tomasbjerre/pull-request-notifier-for-bitbucket#305]
I've been using PRNs in BitBucket Server v5.10.1 for quite a while with reasonable success.  They are always hard to get set up for new projects, but they run fine once I get all the issues fixed.

In a new project, I've defined a PRN exactly like I've done in many other projects, which is supposed to fire on the following events:
* OPENED
* BUTTON_TRIGGER
* REOPENED
* RESCOPED_FROM
* UPDATED 

I've verified that it fires on BUTTON_TRIGGER.  It does NOT fire on OPENED, RESCOPED_FROM, and UPDATED.  That is, I'm performing actions which I assume will fire those events, but it's not doing anything.  I created a pull request, pushed a commit to it, and edited the description field and saved it.  In other projects with the same PRN configuration, each of those actions would cause the PRN to fire.

Note that if you remember my issues from the past, I'm still in the same situation where I don't have server administrative rights, or even server inspection rights, I can just make "user-level" configuration changes to this repository, and getting access to the people who have server admin rights has always been a struggle.  If they ever respond to the ticket I filed for this, I can get you connected with them, to try to get the diagnostics you need to tell us what to adjust to get this working.

**Comment by davidmichaelkarr** [comment]
This is a major problem for us.  All PRNS in multiple repositories are failing to fire on OPENED and RESCOPED_FROM.  My entire pull request build process is severely handicapped now.

**Comment by tomasbjerre** [comment]
Nothing in this issue that I can investigate.

I would suggest getting the configuration as json from the rest API. As described in the readme.

Pretty print the json with some tool.

Diff the working config with the one not working.

**Comment by davidmichaelkarr** [comment]
I don't HAVE one that is working.  All repositories that I've configured this for are doing the same thing.

Here's the block from one repository that we have the issue with (with the host elided):
`  {
    "filterRegexp": "Rebuild",
    "filterString": "${BUTTON_TRIGGER_TITLE}",
    "headers": [],
    "method": "POST",
    "name": "Pull Request Creation",
    "password": "KEEP_THIS_TO_LEAVE_UNCHANGED",
    "projectKey": "ST_IDSE",
    "proxyPassword": "KEEP_THIS_TO_LEAVE_UNCHANGED",
    "proxyUser": "KEEP_THIS_TO_LEAVE_UNCHANGED",
    "repositorySlug": "checkoutms",
    "triggerIfCanMerge": "ALWAYS",
    "triggerIgnoreStateList": [],
    "triggers": [
      "OPENED",
      "BUTTON_TRIGGER",
      "REOPENED",
      "RESCOPED_FROM"
    ],
    "updatePullRequestRefs": false,
    "url": "http://..../jenkins/job/com.att.idp/job/checkoutms-pullrequest/buildWithParameters?PRCause=prn-create&PRTitle=${PULL_REQUEST_TITLE}&PRBranch=${PULL_REQUEST_FROM_BRANCH}&PRURL=${PULL_REQUEST_URL}&PRCloneURL=${PULL_REQUEST_FROM_HTTP_CLONE_URL}&PRFromHash=${PULL_REQUEST_FROM_HASH}",
    "user": "KEEP_THIS_TO_LEAVE_UNCHANGED",
    "uuid": "d9284f89-fe05-4695-94de-df444e67e5f0",
    "postContentEncoding": "NONE"
  },
`

**Comment by davidmichaelkarr** [comment]
So would the regexp have to "(Rebuild|)" then?  I'll try this, although I have other repositories with this set up in that I don't have a button configured here.  On the other hand, the developers I work with are singularly uncommunicative, so I'm not certain whether devs using that other repo are having this problem or not.  I'll try that modified regexp.

**Comment by davidmichaelkarr** [comment]
After that change, my PRN is firing on all the expected events.
