### ISSUE TITLE
buttons disappeared in PRs

### ISSUE THREAD

**Issue by senaraya** [tomasbjerre/pull-request-notifier-for-bitbucket#314]
The buttons that were working disappeared all of a sudden. i can see all the buttons when i click on Configure button in the plugin but not when i go to PR notifications within the repo settings. The only error i can spot was in Developer tools but i couldnt figure out why that error is showing up all of a sudden. 

 * Plugin version used - 3.24
 * Bitbucket Server version used - 5.14.1
 * Stack traces in Bitbucket Server log file - No errors in BB server log file
 
* Any browser console log messages, you can find it in Developer Tools in Chome by pressing F12 - Unable to build keystore from /local/home/atlasian/senaraya

 * Your configuration:
   * http://localhost:7990/bitbucket/rest/prnfb-admin/1.0/settings - {"adminRestriction":"EVERYONE","keyStore":"senaraya","keyStorePassword":"KEEP_THIS_TO_LEAVE_UNCHANGED","keyStoreType":"","shouldAcceptAnyCertificate":true}

   * http://localhost:7990/bitbucket/rest/prnfb-admin/1.0/settings/buttons - [{"buttonFormList":[],"buttonFormListString":"[]","name":"Test Branch","userLevel":"EVERYONE","uuid":"64d9d5a5-a19c-4354-a4c6-43bb71682e5c"},{"buttonFormList":[],"buttonFormListString":"[]","name":"Test Branch FullPipe","userLevel":"EVERYONE","uuid":"95150448-54f6-470d-b904-7c45015d4cf1"},{"buttonFormList":[],"buttonFormListString":"[]","name":"Test Branch Webui","userLevel":"EVERYONE","uuid":"f4ee0363-0708-4c98-9d6b-d5f248e7b17f"},{"buttonFormList":[],"buttonFormListString":"[]","name":"Test Merge","userLevel":"EVERYONE","uuid":"e462e8b9-0be4-4cce-ac9e-6f07d92274e0"},{"buttonFormList":[],"buttonFormListString":"[]","name":"Test Merge All","userLevel":"EVERYONE","uuid":"a00ee40e-184e-46a2-8116-eed3ccb350d1"},{"buttonFormList":[],"buttonFormListString":"[]","name":"Test Merge FullPipe","userLevel":"EVERYONE","uuid":"a4129cf6-4668-49fe-a330-32b3533d4251"},{"buttonFormList":[],"buttonFormListString":"[]","name":"Test Merge Webui","userLevel":"EVERYONE","uuid":"d84d97ff-a751-4481-83ce-5ba7c87e1043"},{"buttonFormList":[],"buttonFormListString":"[]","name":"Trigger Notification","userLevel":"SYSTEM_ADMIN","uuid":"31083610-6840-47af-b07b-97b4867d1b63"},{"buttonFormList":[],"buttonFormListString":"[]","confirmation":"on","name":"test_button","projectKey":"CORE","repositorySlug":"tailf","userLevel":"EVERYONE","uuid":"a2a807de-f0c3-4862-a8af-ae224be3832c"}]

   * http://localhost:7990/bitbucket/rest/prnfb-admin/1.0/settings/notifications - [{"filterRegexp":"^CORE/tailf###Test Branch$","filterString":"${PULL_REQUEST_TO_REPO_PROJECT_KEY}/${PULL_REQUEST_TO_REPO_NAME}###${BUTTON_TRIGGER_TITLE}","headers":[],"method":"GET","name":"CORE/tailf.git: Test Branch","password":"KEEP_THIS_TO_LEAVE_UNCHANGED","proxyPassword":"KEEP_THIS_TO_LEAVE_UNCHANGED","proxyPort":-1,"proxyUser":"KEEP_THIS_TO_LEAVE_UNCHANGED","triggerIfCanMerge":"ALWAYS","triggerIgnoreStateList":["DECLINED","MERGED"],"triggers":["BUTTON_TRIGGER"],"updatePullRequestRefs":false,"url":"https://jenkins3.lab.tail-f.com/git/notifyCommit?url=${PULL_REQUEST_TO_SSH_CLONE_URL}&branches=pr/${PULL_REQUEST_TO_BRANCH}&sha1=${PULL_REQUEST_FROM_HASH}&STASH_PULL_REQUEST_FROM_BRANCH=${PULL_REQUEST_FROM_BRANCH}&STASH_PULL_REQUEST_ID=${PULL_REQUEST_ID}&STASH_PULL_REQUEST_ACTION=${PULL_REQUEST_ACTION}&STASH_BUTTON_TRIGGER_TITLE=${BUTTON_TRIGGER_TITLE}&STASH_PULL_REQUEST_URL=${PULL_REQUEST_URL}&STASH_PULL_REQUEST_VERSION=${PULL_REQUEST_VERSION}&STASH_PULL_REQUEST_USER_NAME=${PULL_REQUEST_USER_NAME}&STASH_REPORT_BUILD_STATUS=false","user":"KEEP_THIS_TO_LEAVE_UNCHANGED","uuid":"cfc358dd-1fd1-46d1-8aaa-40dcc70862f2","postContentEncoding":"NONE"},{"filterRegexp":"^CORE/tailf###Test Branch FullPipe$","filterString":"${PULL_REQUEST_TO_REPO_PROJECT_KEY}/${PULL_REQUEST_TO_REPO_NAME}###${BUTTON_TRIGGER_TITLE}","headers":[],"method":"GET","name":"CORE/tailf.git: Test Branch FullPipe","password":"KEEP_THIS_TO_LEAVE_UNCHANGED","proxyPassword":"KEEP_THIS_TO_LEAVE_UNCHANGED","proxyUser":"KEEP_THIS_TO_LEAVE_UNCHANGED","triggerIfCanMerge":"ALWAYS","triggerIgnoreStateList":["DECLINED","MERGED"],"triggers":["BUTTON_TRIGGER"],"updatePullRequestRefs":false,"url":"https://jenkins3.lab.tail-f.com/git/notifyCommit?url=${PULL_REQUEST_TO_SSH_CLONE_URL}&branches=pr-full/${PULL_REQUEST_TO_BRANCH}&sha1=${PULL_REQUEST_FROM_HASH}&STASH_PULL_REQUEST_FROM_BRANCH=${PULL_REQUEST_FROM_BRANCH}&STASH_PULL_REQUEST_ID=${PULL_REQUEST_ID}&STASH_PULL_REQUEST_ACTION=${PULL_REQUEST_ACTION}&STASH_BUTTON_TRIGGER_TITLE=${BUTTON_TRIGGER_TITLE}&STASH_PULL_REQUEST_URL=${PULL_REQUEST_URL}&STASH_PULL_REQUEST_VERSION=${PULL_REQUEST_VERSION}&STASH_PULL_REQUEST_USER_NAME=${PULL_REQUEST_USER_NAME}&STASH_REPORT_BUILD_STATUS=false","user":"KEEP_THIS_TO_LEAVE_UNCHANGED","uuid":"129e3bbd-c9e2-41c6-99ac-cfae524d15a3","postContentEncoding":"NONE"},{"filterRegexp":"^CORE/tailf###Test Branch Webui$","filterString":"${PULL_REQUEST_TO_REPO_PROJECT_KEY}/${PULL_REQUEST_TO_REPO_NAME}###${BUTTON_TRIGGER_TITLE}","headers":[],"method":"GET","name":"CORE/tailf.git: Test Branch Webui","password":"KEEP_THIS_TO_LEAVE_UNCHANGED","proxyPassword":"KEEP_THIS_TO_LEAVE_UNCHANGED","proxyUser":"KEEP_THIS_TO_LEAVE_UNCHANGED","triggerIfCanMerge":"ALWAYS","triggerIgnoreStateList":["DECLINED","MERGED"],"triggers":["BUTTON_TRIGGER"],"updatePullRequestRefs":false,"url":"https://jenkins3.lab.tail-f.com/git/notifyCommit?url=${PULL_REQUEST_TO_SSH_CLONE_URL}&branches=pr-one/${PULL_REQUEST_TO_BRANCH}&sha1=${PULL_REQUEST_FROM_HASH}&STASH_PULL_REQUEST_ID=${PULL_REQUEST_ID}&STASH_PULL_REQUEST_ACTION=${PULL_REQUEST_ACTION}&STASH_BUTTON_TRIGGER_TITLE=${BUTTON_TRIGGER_TITLE}&STASH_PULL_REQUEST_URL=${PULL_REQUEST_URL}&STASH_PULL_REQUEST_VERSION=${PULL_REQUEST_VERSION}&STASH_PULL_REQUEST_USER_NAME=${PULL_REQUEST_USER_NAME}&STASH_REPORT_BUILD_STATUS=false","user":"KEEP_THIS_TO_LEAVE_UNCHANGED","uuid":"d9d7dd4a-e51e-4dbb-9631-b8afcb3a679f","postContentEncoding":"NONE"},{"filterRegexp":"^CORE/tailf###Test Merge$","filterString":"${PULL_REQUEST_TO_REPO_PROJECT_KEY}/${PULL_REQUEST_TO_REPO_NAME}###${BUTTON_TRIGGER_TITLE}","headers":[],"method":"GET","name":"CORE/tailf.git: Test Merge","password":"KEEP_THIS_TO_LEAVE_UNCHANGED","proxyPassword":"KEEP_THIS_TO_LEAVE_UNCHANGED","proxyPort":-1,"proxyUser":"KEEP_THIS_TO_LEAVE_UNCHANGED","triggerIfCanMerge":"ALWAYS","triggerIgnoreStateList":["DECLINED","MERGED"],"triggers":["BUTTON_TRIGGER"],"updatePullRequestRefs":false,"url":"https://jenkins3.lab.tail-f.com/git/notifyCommit?url=${PULL_REQUEST_TO_SSH_CLONE_URL}&branches=pr/${PULL_REQUEST_TO_BRANCH}&sha1=${PULL_REQUEST_FROM_HASH}&STASH_PULL_REQUEST_FROM_BRANCH=${PULL_REQUEST_FROM_BRANCH}&STASH_PULL_REQUEST_ID=${PULL_REQUEST_ID}&STASH_PULL_REQUEST_ACTION=${PULL_REQUEST_ACTION}&STASH_BUTTON_TRIGGER_TITLE=${BUTTON_TRIGGER_TITLE}&STASH_PULL_REQUEST_URL=${PULL_REQUEST_URL}&STASH_PULL_REQUEST_VERSION=${PULL_REQUEST_VERSION}&STASH_PULL_REQUEST_USER_NAME=${PULL_REQUEST_USER_NAME}&STASH_REPORT_BUILD_STATUS=true&REBASE_ON_REPO_REF=true","user":"KEEP_THIS_TO_LEAVE_UNCHANGED","uuid":"db3a61c0-463a-41bf-9ef5-8b5aaaf8dde0","postContentEncoding":"NONE"},{"filterRegexp":"^CORE/tailf###Test Merge FullPipe$","filterString":"${PULL_REQUEST_TO_REPO_PROJECT_KEY}/${PULL_REQUEST_TO_REPO_NAME}###${BUTTON_TRIGGER_TITLE}","headers":[],"method":"GET","name":"CORE/tailf.git: Test Merge FullPipe","password":"KEEP_THIS_TO_LEAVE_UNCHANGED","proxyPassword":"KEEP_THIS_TO_LEAVE_UNCHANGED","proxyUser":"KEEP_THIS_TO_LEAVE_UNCHANGED","triggerIfCanMerge":"ALWAYS","triggerIgnoreStateList":["DECLINED","MERGED"],"triggers":["BUTTON_TRIGGER"],"updatePullRequestRefs":false,"url":"https://jenkins3.lab.tail-f.com/git/notifyCommit?url=${PULL_REQUEST_TO_SSH_CLONE_URL}&branches=pr-full/${PULL_REQUEST_TO_BRANCH}&sha1=${PULL_REQUEST_FROM_HASH}&STASH_PULL_REQUEST_FROM_BRANCH=${PULL_REQUEST_FROM_BRANCH}&STASH_PULL_REQUEST_ID=${PULL_REQUEST_ID}&STASH_PULL_REQUEST_ACTION=${PULL_REQUEST_ACTION}&STASH_BUTTON_TRIGGER_TITLE=${BUTTON_TRIGGER_TITLE}&STASH_PULL_REQUEST_URL=${PULL_REQUEST_URL}&STASH_PULL_REQUEST_VERSION=${PULL_REQUEST_VERSION}&STASH_PULL_REQUEST_USER_NAME=${PULL_REQUEST_USER_NAME}&STASH_REPORT_BUILD_STATUS=true&REBASE_ON_REPO_REF=true","user":"KEEP_THIS_TO_LEAVE_UNCHANGED","uuid":"066ffe50-1868-4763-b33a-26dd5277344f","postContentEncoding":"NONE"},{"filterRegexp":"^CORE/tailf###Test Merge Webui$","filterString":"${PULL_REQUEST_TO_REPO_PROJECT_KEY}/${PULL_REQUEST_TO_REPO_NAME}###${BUTTON_TRIGGER_TITLE}","headers":[],"method":"GET","name":"CORE/tailf.git: Test Merge Webui","password":"KEEP_THIS_TO_LEAVE_UNCHANGED","proxyPassword":"KEEP_THIS_TO_LEAVE_UNCHANGED","proxyPort":-1,"proxyUser":"KEEP_THIS_TO_LEAVE_UNCHANGED","triggerIfCanMerge":"ALWAYS","triggerIgnoreStateList":["DECLINED","MERGED"],"triggers":["BUTTON_TRIGGER"],"updatePullRequestRefs":false,"url":"https://jenkins3.lab.tail-f.com/git/notifyCommit?url=${PULL_REQUEST_TO_SSH_CLONE_URL}&branches=pr-one/${PULL_REQUEST_TO_BRANCH}&sha1=${PULL_REQUEST_FROM_HASH}&STASH_PULL_REQUEST_ID=${PULL_REQUEST_ID}&STASH_PULL_REQUEST_ACTION=${PULL_REQUEST_ACTION}&STASH_BUTTON_TRIGGER_TITLE=${BUTTON_TRIGGER_TITLE}&STASH_PULL_REQUEST_URL=${PULL_REQUEST_URL}&STASH_PULL_REQUEST_VERSION=${PULL_REQUEST_VERSION}&STASH_PULL_REQUEST_USER_NAME=${PULL_REQUEST_USER_NAME}&STASH_REPORT_BUILD_STATUS=true&REBASE_ON_REPO_REF=true","user":"KEEP_THIS_TO_LEAVE_UNCHANGED","uuid":"461a0b70-a674-4e80-aa0b-55df51584f6d","postContentEncoding":"NONE"},{"filterRegexp":"^NED###Test Branch$","filterString":"${PULL_REQUEST_TO_REPO_PROJECT_KEY}###${BUTTON_TRIGGER_TITLE}","headers":[{"name":"Content-Type","value":"application/x-www-form-urlencoded"}],"method":"POST","name":"NED/*: Test Branch","password":"KEEP_THIS_TO_LEAVE_UNCHANGED","postContent":"BUTTON_TRIGGER_TITLE=${BUTTON_TRIGGER_TITLE}&PULL_REQUEST_ID=${PULL_REQUEST_ID}&PULL_REQUEST_TITLE=${PULL_REQUEST_TITLE}&PULL_REQUEST_VERSION=${PULL_REQUEST_VERSION}&PULL_REQUEST_FROM_BRANCH=${PULL_REQUEST_FROM_BRANCH}&PULL_REQUEST_FROM_HASH=${PULL_REQUEST_FROM_HASH}&PULL_REQUEST_TO_BRANCH=${PULL_REQUEST_TO_BRANCH}&PULL_REQUEST_TO_HASH=${PULL_REQUEST_TO_HASH}&PULL_REQUEST_TO_REPO_NAME=${PULL_REQUEST_TO_REPO_NAME}&PULL_REQUEST_TO_REPO_PROJECT_KEY=${PULL_REQUEST_TO_REPO_PROJECT_KEY}&token=a3cdd6e5faba766d3a134a1ca05dd5ab6e64ebd0&cause=Pull%20request%20by%3A%20${PULL_REQUEST_USER_DISPLAY_NAME}","proxyPassword":"KEEP_THIS_TO_LEAVE_UNCHANGED","proxyPort":-1,"proxyUser":"KEEP_THIS_TO_LEAVE_UNCHANGED","triggerIfCanMerge":"ALWAYS","triggerIgnoreStateList":["DECLINED","MERGED"],"triggers":["BUTTON_TRIGGER"],"updatePullRequestRefs":false,"url":"http://synchrony.lab.tail-f.com:8080/job/BB-pull-request/buildWithParameters","user":"KEEP_THIS_TO_LEAVE_UNCHANGED","uuid":"014c89c4-8ba6-441c-91a8-280fb3c0f85f","postContentEncoding":"NONE"},{"filterRegexp":"^NED###Test Merge$","filterString":"${PULL_REQUEST_TO_REPO_PROJECT_KEY}###${BUTTON_TRIGGER_TITLE}","headers":[{"name":"Content-Type","value":"application/x-www-form-urlencoded"}],"method":"POST","name":"NED/*: Test Merge","password":"KEEP_THIS_TO_LEAVE_UNCHANGED","postContent":"BUTTON_TRIGGER_TITLE=${BUTTON_TRIGGER_TITLE}&PULL_REQUEST_ID=${PULL_REQUEST_ID}&PULL_REQUEST_TITLE=${PULL_REQUEST_TITLE}&PULL_REQUEST_VERSION=${PULL_REQUEST_VERSION}&PULL_REQUEST_FROM_BRANCH=${PULL_REQUEST_FROM_BRANCH}&PULL_REQUEST_FROM_HASH=${PULL_REQUEST_FROM_HASH}&PULL_REQUEST_TO_BRANCH=${PULL_REQUEST_TO_BRANCH}&PULL_REQUEST_TO_HASH=${PULL_REQUEST_TO_HASH}&PULL_REQUEST_TO_REPO_NAME=${PULL_REQUEST_TO_REPO_NAME}&PULL_REQUEST_TO_REPO_PROJECT_KEY=${PULL_REQUEST_TO_REPO_PROJECT_KEY}&token=a3cdd6e5faba766d3a134a1ca05dd5ab6e64ebd0&cause=Pull%20request%20by%3A%20${PULL_REQUEST_USER_DISPLAY_NAME}","proxyPassword":"KEEP_THIS_TO_LEAVE_UNCHANGED","proxyPort":-1,"proxyUser":"KEEP_THIS_TO_LEAVE_UNCHANGED","triggerIfCanMerge":"NOT_CONFLICTING","triggerIgnoreStateList":["DECLINED","MERGED"],"triggers":["BUTTON_TRIGGER"],"updatePullRequestRefs":false,"url":"http://synchrony.lab.tail-f.com:8080/job/BB-pull-request/buildWithParameters","user":"KEEP_THIS_TO_LEAVE_UNCHANGED","uuid":"1a6622d8-b8f5-4ce6-a38a-9c1caddcb6d2","postContentEncoding":"NONE"},{"filterRegexp":"^NED###Test Merge All$","filterString":"${PULL_REQUEST_TO_REPO_PROJECT_KEY}###${BUTTON_TRIGGER_TITLE}","headers":[{"name":"Content-Type","value":"application/x-www-form-urlencoded"}],"method":"POST","name":"NED/*: Test Merge All","password":"KEEP_THIS_TO_LEAVE_UNCHANGED","postContent":"BUTTON_TRIGGER_TITLE=${BUTTON_TRIGGER_TITLE}&PULL_REQUEST_ID=${PULL_REQUEST_ID}&PULL_REQUEST_TITLE=${PULL_REQUEST_TITLE}&PULL_REQUEST_VERSION=${PULL_REQUEST_VERSION}&PULL_REQUEST_FROM_BRANCH=${PULL_REQUEST_FROM_BRANCH}&PULL_REQUEST_FROM_HASH=${PULL_REQUEST_FROM_HASH}&PULL_REQUEST_TO_BRANCH=${PULL_REQUEST_TO_BRANCH}&PULL_REQUEST_TO_HASH=${PULL_REQUEST_TO_HASH}&PULL_REQUEST_TO_REPO_NAME=${PULL_REQUEST_TO_REPO_NAME}&PULL_REQUEST_TO_REPO_PROJECT_KEY=${PULL_REQUEST_TO_REPO_PROJECT_KEY}&token=a3cdd6e5faba766d3a134a1ca05dd5ab6e64ebd0&cause=Pull%20request%20by%3A%20${PULL_REQUEST_USER_DISPLAY_NAME}","proxyPassword":"KEEP_THIS_TO_LEAVE_UNCHANGED","proxyPort":-1,"proxyUser":"KEEP_THIS_TO_LEAVE_UNCHANGED","triggerIfCanMerge":"NOT_CONFLICTING","triggerIgnoreStateList":["DECLINED","MERGED"],"triggers":["BUTTON_TRIGGER"],"updatePullRequestRefs":false,"url":"http://synchrony.lab.tail-f.com:8080/job/BB-pull-request-all/buildWithParameters","user":"KEEP_THIS_TO_LEAVE_UNCHANGED","uuid":"b1da8edc-d248-4f6a-842a-6fb47860e031","postContentEncoding":"NONE"},{"filterRegexp":"^PKG###Test Branch$","filterString":"${PULL_REQUEST_TO_REPO_PROJECT_KEY}###${BUTTON_TRIGGER_TITLE}","headers":[{"name":"Content-Type","value":"application/x-www-form-urlencoded"}],"method":"POST","name":"Test Branch","password":"KEEP_THIS_TO_LEAVE_UNCHANGED","postContent":"BUTTON_TRIGGER_TITLE=${BUTTON_TRIGGER_TITLE}&PULL_REQUEST_USER_NAME=${PULL_REQUEST_USER_NAME}&PULL_REQUEST_TO_REPO_NAME=${PULL_REQUEST_TO_REPO_NAME}&PULL_REQUEST_TO_HASH=${PULL_REQUEST_TO_HASH}&PULL_REQUEST_TO_BRANCH=${PULL_REQUEST_TO_BRANCH}&PULL_REQUEST_ID=${PULL_REQUEST_ID}&PULL_REQUEST_TO_REPO_PROJECT_KEY=${PULL_REQUEST_TO_REPO_PROJECT_KEY}&PULL_REQUEST_FROM_REPO_NAME=${PULL_REQUEST_FROM_REPO_NAME}&PULL_REQUEST_FROM_HASH=${PULL_REQUEST_FROM_HASH}&PULL_REQUEST_FROM_BRANCH=${PULL_REQUEST_FROM_BRANCH}","projectKey":"PKG","proxyPassword":"KEEP_THIS_TO_LEAVE_UNCHANGED","proxyPort":-1,"proxyUser":"KEEP_THIS_TO_LEAVE_UNCHANGED","triggerIfCanMerge":"ALWAYS","triggerIgnoreStateList":["DECLINED","MERGED"],"triggers":["BUTTON_TRIGGER"],"updatePullRequestRefs":false,"url":"http://jenkins5-stg.lab.tail-f.com:8080/job/project_pull_request/buildWithParameters?token=testingtesting123","user":"KEEP_THIS_TO_LEAVE_UNCHANGED","uuid":"61c2041a-de44-4869-bddd-46122fb64401","postContentEncoding":"NONE"},{"filterRegexp":"^PKG###Test Branch$","filterString":"${PULL_REQUEST_TO_REPO_PROJECT_KEY}###${BUTTON_TRIGGER_TITLE}","headers":[{"name":"Content-Type","value":"application/x-www-form-urlencoded"}],"method":"POST","name":"Test Branch","password":"KEEP_THIS_TO_LEAVE_UNCHANGED","postContent":"BUTTON_TRIGGER_TITLE=${BUTTON_TRIGGER_TITLE}&PULL_REQUEST_USER_NAME=${PULL_REQUEST_USER_NAME}&PULL_REQUEST_TO_REPO_NAME=${PULL_REQUEST_TO_REPO_NAME}&PULL_REQUEST_TO_HASH=${PULL_REQUEST_TO_HASH}&PULL_REQUEST_TO_BRANCH=${PULL_REQUEST_TO_BRANCH}&PULL_REQUEST_ID=${PULL_REQUEST_ID}&PULL_REQUEST_TO_REPO_PROJECT_KEY=${PULL_REQUEST_TO_REPO_PROJECT_KEY}&PULL_REQUEST_FROM_REPO_NAME=${PULL_REQUEST_FROM_REPO_NAME}&PULL_REQUEST_FROM_HASH=${PULL_REQUEST_FROM_HASH}&PULL_REQUEST_FROM_BRANCH=${PULL_REQUEST_FROM_BRANCH}","projectKey":"PKG","proxyPassword":"KEEP_THIS_TO_LEAVE_UNCHANGED","proxyPort":-1,"proxyUser":"KEEP_THIS_TO_LEAVE_UNCHANGED","triggerIfCanMerge":"ALWAYS","triggerIgnoreStateList":["DECLINED","MERGED"],"triggers":["BUTTON_TRIGGER"],"updatePullRequestRefs":false,"url":"https://jenkins5-stg.lab.tail-f.com:8443/job/project_pull_request/buildWithParameters?token=testingtesting123","user":"KEEP_THIS_TO_LEAVE_UNCHANGED","uuid":"4c183cbd-fbcf-4fb1-a146-b2bca49bd802","postContentEncoding":"NONE"},{"filterRegexp":"^PKG###Test Branch$","filterString":"${PULL_REQUEST_TO_REPO_PROJECT_KEY}###${BUTTON_TRIGGER_TITLE}","headers":[{"name":"Content-Type","value":"application/x-www-form-urlencoded"}],"method":"POST","name":"Test Branch","password":"KEEP_THIS_TO_LEAVE_UNCHANGED","postContent":"BUTTON_TRIGGER_TITLE=${BUTTON_TRIGGER_TITLE}&PULL_REQUEST_USER_NAME=${PULL_REQUEST_USER_NAME}&PULL_REQUEST_TO_REPO_NAME=${PULL_REQUEST_TO_REPO_NAME}&PULL_REQUEST_TO_HASH=${PULL_REQUEST_TO_HASH}&PULL_REQUEST_TO_BRANCH=${PULL_REQUEST_TO_BRANCH}&PULL_REQUEST_ID=${PULL_REQUEST_ID}&PULL_REQUEST_TO_REPO_PROJECT_KEY=${PULL_REQUEST_TO_REPO_PROJECT_KEY}&PULL_REQUEST_FROM_REPO_NAME=${PULL_REQUEST_FROM_REPO_NAME}&PULL_REQUEST_FROM_HASH=${PULL_REQUEST_FROM_HASH}&PULL_REQUEST_FROM_BRANCH=${PULL_REQUEST_FROM_BRANCH}","projectKey":"PKG","proxyPassword":"KEEP_THIS_TO_LEAVE_UNCHANGED","proxyPort":-1,"proxyUser":"KEEP_THIS_TO_LEAVE_UNCHANGED","triggerIfCanMerge":"ALWAYS","triggerIgnoreStateList":["DECLINED","MERGED"],"triggers":["BUTTON_TRIGGER"],"updatePullRequestRefs":false,"url":"https://jenkins5-stg.lab.tail-f.com:8443/job/project_pull_request/buildWithParameters?token=testingtesting123","user":"KEEP_THIS_TO_LEAVE_UNCHANGED","uuid":"58629ceb-e865-4735-86f0-65d24b6be8c1","postContentEncoding":"NONE"},{"filterRegexp":"^PKG###Test Merge$","filterString":"${PULL_REQUEST_TO_REPO_PROJECT_KEY}###${BUTTON_TRIGGER_TITLE}","headers":[{"name":"Content-Type","value":"application/x-www-form-urlencoded"}],"method":"POST","name":"Test Merge","password":"KEEP_THIS_TO_LEAVE_UNCHANGED","postContent":"BUTTON_TRIGGER_TITLE=${BUTTON_TRIGGER_TITLE}&PULL_REQUEST_USER_NAME=${PULL_REQUEST_USER_NAME}&PULL_REQUEST_TO_REPO_NAME=${PULL_REQUEST_TO_REPO_NAME}&PULL_REQUEST_TO_HASH=${PULL_REQUEST_TO_HASH}&PULL_REQUEST_TO_BRANCH=${PULL_REQUEST_TO_BRANCH}&PULL_REQUEST_ID=${PULL_REQUEST_ID}&PULL_REQUEST_TO_REPO_PROJECT_KEY=${PULL_REQUEST_TO_REPO_PROJECT_KEY}&PULL_REQUEST_FROM_REPO_NAME=${PULL_REQUEST_FROM_REPO_NAME}&PULL_REQUEST_FROM_HASH=${PULL_REQUEST_FROM_HASH}&PULL_REQUEST_FROM_BRANCH=${PULL_REQUEST_FROM_BRANCH}","projectKey":"PKG","proxyPassword":"KEEP_THIS_TO_LEAVE_UNCHANGED","proxyPort":-1,"proxyUser":"KEEP_THIS_TO_LEAVE_UNCHANGED","triggerIfCanMerge":"NOT_CONFLICTING","triggerIgnoreStateList":["DECLINED","MERGED"],"triggers":["BUTTON_TRIGGER"],"updatePullRequestRefs":false,"url":"https://jenkins5-stg.lab.tail-f.com:8443/job/project_pull_request/buildWithParameters?token=testingtesting123","user":"KEEP_THIS_TO_LEAVE_UNCHANGED","uuid":"2c7b4d1f-ac6b-437a-a153-8b6b99b31b00","postContentEncoding":"NONE"},{"filterRegexp":"test_button","filterString":"${BUTTON_TRIGGER_TITLE}","headers":[],"method":"GET","name":"test","password":"KEEP_THIS_TO_LEAVE_UNCHANGED","projectKey":"CORE","proxyPassword":"KEEP_THIS_TO_LEAVE_UNCHANGED","proxyUser":"KEEP_THIS_TO_LEAVE_UNCHANGED","repositorySlug":"tailf","triggerIfCanMerge":"ALWAYS","triggerIgnoreStateList":[],"triggers":["APPROVED","COMMENTED","DECLINED","MERGED","OPENED","BUTTON_TRIGGER","UPDATED"],"updatePullRequestRefs":false,"url":"https://engci-jenkins-blr.cisco.com/jenkins/job/team_SCMDevops/job/bb-pipelines/build?token=PIPE","user":"KEEP_THIS_TO_LEAVE_UNCHANGED","uuid":"bbe5707c-998f-42e2-bf60-482322c61fb4","postContentEncoding":"NONE"}]

**Comment by tomasbjerre** [comment]
Looks to me like you have a problem with your keystore. Not much to investigate from my part.

**Comment by jay00929** [comment]
By using pull-request-notifier-for-bitbucket plugin, we are trying to create a new button in pull request view to enable the notification method and to triggered a new event. Same we already did back and that was working fine. While today when we are trying to enable a new button in different repository, message appears success but unable to view that button in any pull request. I can see below error in my atlassian-bitbucket.log:

2019-08-08 19:01:45,705 ERROR [http-nio-7990-exec-39] jayprakash.singh @ZYIE8Jx1141x8216400x1 1ftanqm 136.232.1.30,127.0.0.1 "GET /rest/prnfb-admin/1.0/settings/buttons/repository/674/pullrequest/3 HTTP/1.0" c.a.p.r.c.e.j.ThrowableExceptionMapper Uncaught exception thrown by REST service: Unable to build keystore from /opt/atlassian/bitbucket/5.13.1/bin/jayprakash.singh
java.lang.RuntimeException: Unable to build keystore from /opt/atlassian/bitbucket/5.13.1/bin/jayprakash.singh
at se.bjurr.prnfb.http.ClientKeyStore.<init>(ClientKeyStore.java:36)
at se.bjurr.prnfb.service.ButtonsService.getButtons(ButtonsService.java:125)
at se.bjurr.prnfb.presentation.ButtonServlet.get(ButtonServlet.java:150)
at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
at com.atlassian.analytics.client.filter.UniversalAnalyticsFilter.doFilter(UniversalAnalyticsFilter.java:92)
at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:39)
at com.atlassian.bitbucket.internal.xcode.web.XcodeUserAgentFilter.doFilter(XcodeUserAgentFilter.java:36)
