### ISSUE TITLE
Request - create notifications via REST

### ISSUE THREAD

**Issue by James-Dengel** [tomasbjerre/pull-request-notifier-for-bitbucket#315]
This is a request or question.

I create my jenkins jobs via the REST API,

three different buidls one of which is a pull request build.

Is there a way using rest to create a pull request trigger on the server for a new jenkins job, so i don't have to go through the UI each time and reduce errors ?

**Comment by tomasbjerre** [comment]
It is possible to create notifications with the rest api of this plugin. It is documented in the readme. But i suggest you do it once with the gui of this plugin and observe what API calls are being made. Then automate those calls with whatever scripting language you use.

**Comment by James-Dengel** [comment]
I honestly did a quick grep of the README and missed this, so sorry for that.
