### ISSUE TITLE
Bitbucket Server 6.0 support

### ISSUE THREAD

**Issue by derschatta** [tomasbjerre/pull-request-notifier-for-bitbucket#321]
Currently the plugin is not compatible to version 6.0.0 of Bitbucket Server (released 12th of February 2019).

Please make it compatible so we can continue using this great plugin.

Thanks!!

**Comment by tomasbjerre** [comment]
I had a look and started working on this in a branch: https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/tree/feature/bbs6

A problem that is not trivial to solve is that template is removed from AJS:
https://docs.atlassian.com/aui/5.6.8/docs/template.html

And that means the plugin:s GUI fails here:
https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/blob/feature/bbs6/src/main/resources/utils.js#L162

I will probably not work on this. I am no longer using the plugin. And the built in webhook is getting better. And also #313 .

**Comment by derschatta** [comment]
That's a shame. Hopefully someone picks it up. In the meanwhile we went and built our own intermediate solution using the native Webhooks. Still some things like the ability to add buttons etc. are kind of neat and having that would still be great.

**Comment by chq81** [comment]
> That's a shame. Hopefully someone picks it up. In the meanwhile we went and built our own intermediate solution using the native Webhooks. Still some things like the ability to add buttons etc. are kind of neat and having that would still be great.

Thanks to my old colleague for pointing that out :) We are also using that plugin extensively and would really like to see it working again in the future.

**Comment by derschatta** [comment]
The world is small @chq81 :D 

The way we solved it for us without the plugin was to create a proxy script (in our case PHP) which accepts the data provided by the native Bitbucket webhooks and converts it into a compatible GET request to Jenkins.

We've also added support for manual triggering a build by adding a comment like '/build' to the pull request.

Unfortunately our one is quite custom and we can't just put it up on Github without modifying it heavily (maybe if I find some sparetime :)). But it's a relative straightforward thing to do.

**Comment by tomasbjerre** [comment]
You can consume the native webhook with https://github.com/jenkinsci/generic-webhook-trigger-plugin

**Comment by srkallam1986** [comment]
Hi,

Please let us know if you have any ETA on making this plugin compatible with the  Bitbucket  v6.0.x.

Thanks!

**Comment by tomasbjerre** [comment]
No. I have no plans on doing that. Pull requests are welcome.

**Comment by tomasbjerre** [comment]
4.0 released with 6.0 support.
https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/releases/tag/pull-request-notifier-for-bitbucket-4.0

Headers had to be removed, PR:s to get it back are welcome. See #336

**Comment by jansohn** [comment]
This means we cannot use CSRF Protection (`Jenkins-Crumb`) anymore, correct?

**Comment by tomasbjerre** [comment]
You can use this plugin in Jenkins: https://github.com/jenkinsci/generic-webhook-trigger-plugin/
It does not require a `crumb`.

**Comment by jansohn** [comment]
Seems a lot more complicated than triggering the multi-branch pipeline job directly...

**Comment by tomasbjerre** [comment]
You want to trigger a scan of multibranch pipeline? Try this one: https://github.com/jenkinsci/multibranch-scan-webhook-trigger-plugin
It also uses CrumbExclusion : https://github.com/jenkinsci/multibranch-scan-webhook-trigger-plugin/blob/master/src/main/java/com/igalg/jenkins/plugins/mswt/ComputedFolderWebHookRequestReceiver.java#L65

**Comment by jansohn** [comment]
Still requires a lot more configuration than the current solution with `Jenkins-Crumb`. Currently I do not need to configure any tokens.

Would be really nice if `Jenkins-Crumb` could still be used with this plugin.

**Comment by tomasbjerre** [comment]
Actually, the problem here was the templating... dynamically adding/removing headers in the form in the GUI. But if we have a fixed number of configurable headers, perhaps 5, then we dont need the template and we can continue to support headers in the plugin.... I'll have a look at that later.

**Comment by tomasbjerre** [comment]
Released 4.1 with support for **one** header.

https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/releases/tag/pull-request-notifier-for-bitbucket-4.1

**Comment by bingshiao** [comment]
@tomasbjerre Thank you for 4.1 release. Is it published on [Atlassian Marketpalce](https://marketplace.atlassian.com)?

**Comment by tomasbjerre** [comment]
No see: https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/issues/313

**Comment by radoha** [comment]
> Released 4.1 with support for **one** header.
> 
> https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/releases/tag/pull-request-notifier-for-bitbucket-4.1

Can it be used with Bitbucket 6.4.0 ?

**Comment by tomasbjerre** [comment]
Perhaps, I did not test that version.

**Comment by atique-shair** [comment]
Hi,
We plan to upgrade our Bitbucket DC to 6.4.0 most likely next month. However, we came to know that 6.4.0 may not be supported here. Can you confirm if you you have already tested Bitbucket 6.4.0 version and have positive feedback (?) to help us move forward with Bitbucket upgrade. Thanks.
