### ISSUE TITLE
Configurations missing under configure screen

### ISSUE THREAD

**Issue by miksandb** [tomasbjerre/pull-request-notifier-for-bitbucket#322]
After upgrading the app to 3.24 and Bitbucket to 6.1.1, when going to the Configure screen none of the configurations are available. They can be accessed via the REST API and are working, but I am unable to modify the existing one.

The new version also added a new button called pr-triggerbutton on Pull Requests, but it is not listed as a button under /rest/prnfb-admin/1.0/settings/buttons.

**Comment by tomasbjerre** [comment]
See: https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/issues/321
