### ISSUE TITLE
Pull request notification is not triggering Jenkins and not responding anything after pull request opened/created and other events

### ISSUE THREAD

**Issue by naveen0725** [tomasbjerre/pull-request-notifier-for-bitbucket#324]
If things don't work as you expect, perhaps you should file an issue. But first, try troubleshooting it and provide as much info as possible. Here are some things that may help if added to an issue.

 * Plugin version used - 3.23
 * Bitbucket Server version used - Atlassian Bitbucket v5.13.1
 * Stack traces in Bitbucket Server log file - Nothing that much important, all are warnings and some with sqllite
 * Any browser console log messages, you can find it in Developer Tools in Chome by pressing F12- No
 * Your configuration:
   * http://bitbucket.<organization>.com/bitbucket/rest/prnfb-admin/1.0/settings
   * http://bitbucket.<organization>.com/bitbucket/rest/prnfb-admin/1.0/settings/buttons
   * http://bitbucket.<organization>.com/bitbucket/rest/prnfb-admin/1.0/settings/notifications
 * If the system you are trying to notify does not seem to get notified:
  * Check that the triggered URL looks as expected. You can do that by invoking https://requestb.in/ and inspect its results.
  * Try to SSH to the Bitbucket Server machine and run same URL with Curl to make sure it's not a firewall issue.

If you do not have access to the server log files, one idea is to:

 * Also trigger on button pressed, and add a button
 * Open a PR
 * Open Chrome developer tools, F12
 * Press the button in the PR
 * Check the response in the network tab in Chrome. See if it contains something interesting

I tried all the other options mentioned

**Comment by tomasbjerre** [comment]
You did not supply your configuration. Impossible to investigate.
