### ISSUE TITLE
Bitbucket Server 6.2 support

### ISSUE THREAD

**Issue by Geert-Wielens** [tomasbjerre/pull-request-notifier-for-bitbucket#331]
Currently the plugin is not compatible to version 6.2 of Bitbucket Server (released 9th  of April 2019).

Please make it compatible so we can continue using this great plugin.

Thanks!!

**Comment by tomasbjerre** [comment]
https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/issues/321
