### ISSUE TITLE
Use regex to match parts of a variable value

### ISSUE THREAD

**Issue by agentmerlin** [tomasbjerre/pull-request-notifier-for-bitbucket#333]
I'd like to be able to use regex to match certain parts of variable values and have the match available as a new variable named: ${VARIABLE_REGEX_MATCH}

The specific use-case I have is to match part of the ${PULL_REQUEST_FROM_BRANCH} that contains an issue number and use that number in a URL POST payload.

I have already implemented this feature on a fork and looks like this:

<img width="746" alt="Screen Shot 2019-05-07 at 9 30 07 AM" src="https://user-images.githubusercontent.com/2895355/57316480-bd0ce180-70aa-11e9-8d48-5b70859c8bd2.png">

**Comment by tomasbjerre** [comment]
How does it differ from *injection url* and `${INJECTION_URL_VALUE}`?

**Comment by agentmerlin** [comment]
My understanding is that ${INJECTION_URL_VALUE} comes from making a GET request to another service. This new variable would not need to make a request to anther service, it would only need to resolve the variable name provided

**Comment by tomasbjerre** [comment]
Ok sounds good, pull requests are welcome =)

**Comment by tomasbjerre** [comment]
I published the release here: https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/releases/tag/pull-request-notifier-for-bitbucket-3.25
