### ISSUE TITLE
We try to GET another Notifier config then try to POST to another repository,we get an error

### ISSUE THREAD

**Issue by kaku0315** [tomasbjerre/pull-request-notifier-for-bitbucket#335]
Hi,

We try to GET another Notifier config then try to POST to another repository, we get an error.

405 method not allowed.

It seems that there is no way to directly paste it. Is there any setting that should be adjusted?

Our command below - 

GET http://git.com.tw/rest/prnfb-admin/1.0/settings/notifications/projectKey/TEST/repositorySlug/simple_repo_sp

POST http://git.com.tw/rest/prnfb-admin/1.0/settings/notifications/projectKey/DEMO/repositorySlug/jira_test

We want to copy a repository's configuration directly to other repositories via the API.

Kaku

**Comment by tomasbjerre** [comment]
The rest api is documented in the readme.
