### ISSUE TITLE
Is this plugin available in Atlassian marketplace now? 

### ISSUE THREAD

**Issue by kranthikumar490** [tomasbjerre/pull-request-notifier-for-bitbucket#337]
If things don't work as you expect, perhaps you should file an issue. But first, try troubleshooting it and provide as much info as possible. Here are some things that may help if added to an issue.

 * Plugin version used.
 * Bitbucket Server version used.
 * Stack traces in Bitbucket Server log file.
 * Any browser console log messages, you can find it in Developer Tools in Chome by pressing F12.
 * Your configuration:
   * http://localhost:7990/bitbucket/rest/prnfb-admin/1.0/settings
   * http://localhost:7990/bitbucket/rest/prnfb-admin/1.0/settings/buttons
   * http://localhost:7990/bitbucket/rest/prnfb-admin/1.0/settings/notifications
 * If the system you are trying to notify does not seem to get notified:
  * Check that the triggered URL looks as expected. You can do that by invoking https://requestb.in/ and inspect its results.
  * Try to SSH to the Bitbucket Server machine and run same URL with Curl to make sure it's not a firewall issue.
  * Enable runtime debug logging of 'se.bjurr.prnfb.http.UrlInvoker' following https://confluence.atlassian.com/bitbucketserver/bitbucket-server-debug-logging-776640147.html

If you do not have access to the server log files, one idea is to:

 * Also trigger on button pressed, and add a button
 * Open a PR
 * Open Chrome developer tools, F12
 * Press the button in the PR
 * Check the response in the network tab in Chrome. See if it contains something interesting

**Comment by kranthikumar490** [comment]
Hello Thomas, I tried navigating with https://marketplace.atlassian.com/plugins/se.bjurr.prnfs.pull-request-notifier-for-stash/server/overview but didn't work. Is there any mis-spells in the URL?

**Comment by tomasbjerre** [comment]
https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/issues/313
