### ISSUE TITLE
Is there a way to know who clicked the button?

### ISSUE THREAD

**Issue by VTommy** [tomasbjerre/pull-request-notifier-for-bitbucket#339]
Hello

I'm currently using version 3.22. Is there a way I can add the email of the person who clicks the button into the button form? Or I can get the email in the trigger activated by the button click event?

Thanks.

**Comment by tomasbjerre** [comment]
Yes: The ${PULL_REQUEST_USER...} contains information about the user who issued the event. Who commented it, who rejected it, who approved it...
