### ISSUE TITLE
Found invalid crumb "some-crumb"

### ISSUE THREAD

**Issue by kentgitbub** [tomasbjerre/pull-request-notifier-for-bitbucket#348]
After upgrading Jenkins from 2.189 to 2.193 due to security issues **none** of the jobs I have setup in jenkins to be triggered by the pull-request-notifier is started. There are 2 options the way I see it: 
1. some of the changes in Jenkins is breaking this plugin, or
2. implentation in Jenkins doesn't work as intended.

None of the configurations of the 20+ jobs I have that is triggered by this plugin have changed.  
I'm on BitBucket 6.4.0, the plugin version is 4.1, Jenkins is on 2.193. 

Extract from log:
2019-09-04 08:22:33.903+0000 [id=35]	WARNING	hudson.security.csrf.CrumbFilter#doFilter: Found invalid crumb e55f02079f26ceaa8d7751f38e119adeea156a549c169642bdeeafb4029b0317.  Will check remaining parameters for a valid one...
2019-09-04 08:22:33.903+0000 [id=35]	WARNING	hudson.security.csrf.CrumbFilter#doFilter: No valid crumb was included in request for /job/PKING-pm/buildWithParameters by jenkins. Returning 403.

**Comment by tomasbjerre** [comment]
Perhaps same as https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/issues/349

**Comment by kentgitbub** [comment]
I'll have a look at the above issue. 

In the mean time, I got some replies from Daniel Beck on this. I wrote a similar bug-report on Jenkins core since I couldn't determine if this was a problem in the core Jenkins or the plugin. Please have a look at [some-crumb](https://issues.jenkins-ci.org/browse/JENKINS-59219)

**Comment by tomasbjerre** [comment]
Ok. Based on the response in JENKINS-59219 this is a duplicate of the problem in #349. And the "strict-crumb-issuer plugin" seems to solve it.
