### ISSUE TITLE
Add Feature: ${PULL_REQUEST_REVIEWERS_APPROVED_COUNT} >= n

### ISSUE THREAD

**Issue by repuckett** [tomasbjerre/pull-request-notifier-for-bitbucket#354]
I have a use case where having:  ${PULL_REQUEST_REVIEWERS_APPROVED_COUNT} >= n 
would save some coding.

**Comment by tomasbjerre** [comment]
You can do that with the filter feature: https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/issues/338
