### ISSUE TITLE
Blocking the autocompletion in user mentions in Bitbbucket 6.10

### ISSUE THREAD

**Issue by bdonfouet** [tomasbjerre/pull-request-notifier-for-bitbucket#363]
Hello,
we have upgraded out Bitbucket instance to 6.10 and this plugin, version 2.67 prevent the use of autocompletion when trying to mention a user in comment.
here is the atlassian page talking about this issue:
https://confluence.atlassian.com/bitbucketserverkb/pull-request-tree-and-user-mentions-not-working-after-upgrade-980460107.html

Is there any fix for that issue comming with the next version of the plugin?

Regards

**Comment by RJanata** [comment]
I'm running BB 6.10 and the latest pull-request-notifier 4.10 (available for download at [pull-request-notifier-for-bitbucket-4.1](https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/releases/tag/pull-request-notifier-for-bitbucket-4.1)) and I don't see any troubles. This add-on is no longer available on Atlassian Marketplace (see #313) and manual download from this site is necessary.

Why do you use such outdated version? This old version does not support BB 6 at all (see #321).

**Comment by bdonfouet** [comment]
thanks,
did look for another source of the update other than the atlassian market.
plugin updated and problem fixed.
