### ISSUE TITLE
Trigger button: confirmation dialog 

### ISSUE THREAD

**Issue by andreineculau** [tomasbjerre/pull-request-notifier-for-bitbucket#57]
i have a button which might be seen as unsafe consequence wise,
thus users should only press it when they really need to, and not by mistake

**Comment by andreineculau** [comment]
On limited connectivity so i cannot check but did this issue got fixed or resolved as wontfix? There's no explanation nor a commit reference.

--
http://andreineculau.com

**Comment by tomasbjerre** [comment]
Sorry

**Comment by tomasbjerre** [comment]
This is now added to 2.44. Open issue again if any problems!
