### ISSUE TITLE
buttons should be disabled (or just plain hidden) when there are merge conflicts

### ISSUE THREAD

**Issue by andreineculau** [tomasbjerre/pull-request-notifier-for-bitbucket#70]
#64 disabled the triggers when there are merge conflicts, but the buttons are still visible and clickable

see #51

**Comment by tomasbjerre** [comment]
If I configuire the plugin like this:

![triggersapply](https://cloud.githubusercontent.com/assets/439571/10116291/d9bcee32-642f-11e5-9da0-790cba3fb02a.png)

The button is not visible for a PR with merge conflicts. Or do you mean something else?

**Comment by andreineculau** [comment]
I will double check, but that's not what I experienced, Tomas.

On Sat, Sep 26, 2015 at 9:22 AM, Tomas Bjerre <notifications@github.com>
wrote:

> If I configuire the plugin like this:
>
> [image: triggersapply]
> <https://cloud.githubusercontent.com/assets/439571/10116291/d9bcee32-642f-11e5-9da0-790cba3fb02a.png>
>
> The button is not visible for a PR with merge conflicts. Or do you mean
> something else?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/issues/70#issuecomment-143406037>
> .
>



-- 
andreineculau.com <http://www.andreineculau.com>

**Comment by tomasbjerre** [comment]
This would be a bug, but I cannot reproduce it. Open again if you can.
