### ISSUE TITLE
buttons should be disabled (or just plain hidden) when the PR is closed (declined/merged)

### ISSUE THREAD

**Issue by andreineculau** [tomasbjerre/pull-request-notifier-for-bitbucket#71]
similarly to #64 , but in this case the radio buttons should probably be turned into checkboxes - updated #68 to reflect this

**Comment by tomasbjerre** [comment]
How about this?

![skarmbild fran 2015-09-26 09 54 16](https://cloud.githubusercontent.com/assets/439571/10116407/9b9a3b1e-6434-11e5-977e-60e13b73028c.png)

**Comment by tomasbjerre** [comment]
Released in 2.4. So only available for Bitbucket 4.

**Comment by tomasbjerre** [comment]
and in 1.30:
https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/releases/tag/pull-request-notifier-for-stash-1.30
I may not release that one to Marketplace:
https://answers.atlassian.com/questions/30935697/how-do-i-maintain-plugin-compatible-with-stash-3-and-bitbucket-4
