### ISSUE TITLE
In Bitbucket, no forms are visible in the plugin's configuration screen

### ISSUE THREAD

**Issue by carlmot** [tomasbjerre/pull-request-notifier-for-bitbucket#73]
Upgraded from Stash to Bitbucket 4.0.1 and upgraded all plugins. Now, in the pull-request-notifier-for-bitbucket configuration screen, only the list of variables is shown. The forms are missing.
Uninstalled the plugin and reinstalled, same issue (version 2.4).

**Comment by tomasbjerre** [comment]
Does the betwork tab in the browser say anything? Anything in your logs on the server?

There was a problem like this but it should be fixed in 2.4.

**Comment by carlmot** [comment]
Hi Tomas,

Thanks for the prompt response.

Don't seen anything in the logs.
But yes, there is an error seen in the browser 'Network' tab.

Uncaught Error: Syntax error, unrecognized expression:
input[type="checkbox"][name="url"][value="
http://foobar.com:8080/job/pull_request_handler/buildWithParame…UEST_TO_HASH}&pullRequestAction=${PULL_REQUEST_ACTION}&pullRequestComment="${PULL_REQUEST_COMMENT_TEXT}""]b.error
@ batch.js?locale=en-US:68b.tokenize @ batch.js?locale=en-US:80b @
batch.js?locale=en-US:48d.fn.extend.find @
batch.js?locale=en-US:85d.fn.init @ batch.js?locale=en-US:86a.fn.init @
batch.js?locale=en-US:199d @ batch.js?locale=en-US:40(anonymous function) @
se.bjurr.prnfs.pull-request-notifier-for-stash:resources.js:3d.extend.each
@ batch.js?locale=en-US:45(anonymous function) @
se.bjurr.prnfs.pull-request-notifier-for-stash:resources.js:3d.extend.each
@ batch.js?locale=en-US:45(anonymous function) @
se.bjurr.prnfs.pull-request-notifier-for-stash:resources.js:3d.Callbacks.p
@ batch.js?locale=en-US:91d.Callbacks.q.fireWith @
batch.js?locale=en-US:93c @
batch.js?locale=en-US:170d.ajaxTransport.a.send.b @
batch.js?locale=en-US:181




*Carl Golaszewski*

Motorola Solutions Inc.

Common Applications & Metrics

**Comment by carlmot** [comment]
The value= string on mouse over is:
http://foobar.com:8080/job/pull_request_handler/buildWithParameters?sourceBranch=${PULL_REQUEST_FROM_BRANCH}&targetBranch=${PULL_REQUEST_TO_BRANCH}&pullRequestId=${PULL_REQUEST_ID}&projectKey=${PULL_REQUEST_FROM_REPO_PROJECT_KEY}&repoName=${PULL_REQUEST_FROM_REPO_NAME}&repoId=${PULL_REQUEST_FROM_REPO_ID}&fromCommit=${PULL_REQUEST_FROM_HASH}&toCommit=${PULL_REQUEST_TO_HASH}&pullRequestAction=${PULL_REQUEST_ACTION}&pullRequestComment=





*Carl Golaszewski*

Motorola Solutions Inc.

Common Applications & Metrics

**Comment by tomasbjerre** [comment]
Should be fixed now in 2.5. Open issue again if still not solved!
