### ISSUE TITLE
Variable for merged pull request commit hash

### ISSUE THREAD

**Issue by ultrafez** [tomasbjerre/pull-request-notifier-for-bitbucket#75]
Open pull requests are well supported by the selection of variables available, but there doesn't appear to be a variable to retrieve the commit hash of the merge commit that is created when you merge a pull request.

I need this variable in order to make a request to Jenkins to build merged pull requests, because I'd like to specify the exact commit hash of the merged branch, rather than just use the branch name of the branch that the pull request was merged into (which could be modified before Jenkins gets chance to fetch new changes).

It looks like the commit hash is available from the `PullRequestMergedEvent` in Bitbucket Server (see [API docs](https://developer.atlassian.com/static/javadoc/bitbucket-server/4.0.0/api/reference/com/atlassian/bitbucket/event/pull/PullRequestMergedEvent.html))

**Comment by tomasbjerre** [comment]
Released in 1.33 and 2.8
2.8 in Marketplace and 1.33 here:
https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/releases
Open issue again if not working! =)

**Comment by ultrafez** [comment]
That was amazingly fast, thanks!
