### ISSUE TITLE
Wrong url built when using & in branch names

### ISSUE THREAD

**Issue by nikolaykolev** [tomasbjerre/pull-request-notifier-for-bitbucket#76]
When a & is used in branch name and you have a trigger which sends a request to somewhere with ${PULL_REQUEST_FROM_ID} or ${PULL_REQUEST_FROM_BRANCH} the symbol & is not escaped. When this symbol is not escaped the http request has 1 more wrong GET param.
Example: branchName=some-fixes&more-fixes
built url: http://jenkins.asd.com/buildWithParam?branchname=some-fixes&more-fixes
In this case jenkins recognises 2 params instead of 1
should be: http://jenkins.asd.com/buildWithParam?branchname=some-fixes%26more-fixes

**Comment by tomasbjerre** [comment]
Released now in Marketplace :) Open issue again if not solved!

**Comment by nikolaykolev** [comment]
Thank you! :) I'll get in touch if we find other bugs
