### ISSUE TITLE
v1.34 in Atlassian Marketplace listed against wrong BB Server version?

### ISSUE THREAD

**Issue by ultrafez** [tomasbjerre/pull-request-notifier-for-bitbucket#77]
In Atlassian Marketplace, v1.34 is listed as being available for Bitbucket Server 4.0.0 - 4.0.2, but the last 1.* version (1.29) is built for Bitbucket Server 2.12.6 - 3.11.4. If I understand your version numbering correctly, all builds of v1 of the plugin should work on the older BB Server version, is this right?

**Comment by tomasbjerre** [comment]
Yes. 1.x is stash 3 and 2 is bitbucket 4

**Comment by ultrafez** [comment]
Sorry, I didn't explain that very well! Version 1.29 and 2.1 contain the same features, but are released for different versions of Bitbucket Server (see screenshot from the [version history](https://marketplace.atlassian.com/plugins/se.bjurr.prnfs.pull-request-notifier-for-stash/versions)):
![v1.29 and v2.1](http://i.imgur.com/Vj0xP0j.png)

Version 1.34 and 2.9 contain the same features too, but they're both released for the same version of Bitbucket:
![v1.34 and 2.9](http://i.imgur.com/plfvZsa.png)

Shouldn't v1.34 be released for Bitbucket Server 2.12.6 - 3.11.4? At the moment the latest version available for Bitbucket 3 is 1.29.

**Comment by tomasbjerre** [comment]
Thanks! =) You are right, I changed it now.
