### ISSUE TITLE
Processing on Bitbucket Server's event threads

### ISSUE THREAD

**Issue by bstuart9** [tomasbjerre/pull-request-notifier-for-bitbucket#78]
Pull-request notifier is using @EventListener methods that are processing events directly on the event threads.

We have an article that describes the issues this creates inside Bitbucket Server:
https://confluence.atlassian.com/display/STASHKB/RejectedExecutionException

Please see Bryan Turner's suggestions for more information on how to fix this issue:
https://bitbucket.org/izymesdev/workzone/issues/79/buildeventlistener-is-doing-its-processing

Let me know if you have any questions about fixing this!

**Comment by tomasbjerre** [comment]
Fixed in 2.10 and 1.35, open issue again if problem still occurs! =)
