### ISSUE TITLE
[question] a way to trigger from CLI/REST?

### ISSUE THREAD

**Issue by andreineculau** [tomasbjerre/pull-request-notifier-for-bitbucket#79]
this would save a round trip to the Stash UI for some of us living in the realms of our terminal :)

for now I can only think of using the comment trigger , via https://marketplace.atlassian.com/plugins/de.aeffle.stash.plugins.create-pull-request-via-ssh

but there's nothing for the button trigger, which saves the reviewers from a redundant email notification

**Comment by tomasbjerre** [comment]
Did you look at:
https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/blob/master/src/main/java/se/bjurr/prnfb/ManualResource.java ?

You can do a GET to get a list of buttons that will cause a notification to trigger. And then a POST to trigger it.

**Comment by andreineculau** [comment]
didn't see that one. I'm still on stash 3.x
a mention/docs for this feature would be nice.
thanks!

**Comment by tomasbjerre** [comment]
But you have that resource even in Stash 3.x right?

**Comment by andreineculau** [comment]
Alright. I just hit the "History" button on github, and it probably doesn't
do "--follow"..
Thanks! I can give it a try on my Stash 3 then

On Tue, Oct 20, 2015 at 5:38 PM, Tomas Bjerre <notifications@github.com>
wrote:

> But you have that resource even in Stash 3.x right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/issues/79#issuecomment-149587743>
> .
>



-- 
andreineculau.com <http://www.andreineculau.com>

**Comment by andreineculau** [comment]
Yup, it works.
For anyone looking for the url it's
https://example.com/rest/prnfs-admin/1.0/manual?repositoryId=1&pullRequestId=1

PS: Going by PROJECT_KEY and REPO_NAME would be more convenient

On Tue, Oct 20, 2015 at 5:53 PM, Andrei Neculau <andrei.neculau@gmail.com>
wrote:

> Alright. I just hit the "History" button on github, and it probably
> doesn't do "--follow"..
> Thanks! I can give it a try on my Stash 3 then
>
> On Tue, Oct 20, 2015 at 5:38 PM, Tomas Bjerre <notifications@github.com>
> wrote:
>
>> But you have that resource even in Stash 3.x right?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/issues/79#issuecomment-149587743>
>> .
>>
>
>
>
> --
> andreineculau.com <http://www.andreineculau.com>
>



-- 
andreineculau.com <http://www.andreineculau.com>
