### ISSUE TITLE
Wrong PULL_REQUEST_URL

### ISSUE THREAD

**Issue by eratolekov** [tomasbjerre/pull-request-notifier-for-bitbucket#82]
Hi Tomas

Thanks for plugin!

If name of repo in Bitbucket Server contains spaces, PULL_REQUEST_URL contains these spaces too.
Wrong PULL_REQUEST_URL
```
https://example.com/projects/PROJ/repos/Repo Name with Spaces/pull-requests/2
```

The correct PULL_REQUEST_URL is
```
https://example.com/projects/PROJ/repos/repo-name-with-spaces/pull-requests/2
```

**Comment by tomasbjerre** [comment]
This should be fixed now if you update the plugin

**Comment by eratolekov** [comment]
Hi Tomas

I guess better to use [getSlug()](https://developer.atlassian.com/static/javadoc/bitbucket-server/4.1.0/api/reference/com/atlassian/bitbucket/repository/Repository.html#getSlug()) instead of getName().

**Comment by tomasbjerre** [comment]
Yes, feel free to submit a pull request for that :)

**Comment by tomasbjerre** [comment]
Im opening issue again. Should use getSlug to fix this correctly.
