### ISSUE TITLE
Strange chars in PULL_REQUEST_URL

### ISSUE THREAD

**Issue by eratolekov** [tomasbjerre/pull-request-notifier-for-bitbucket#83]
Hi Tomas

I do not know why, but when I copy URL from build description (see attached screen), and replace [spaces with dashes](https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/issues/82), I'm trying to open this URL in browser. And I'm getting 404.

After some investigations, I found strange chars in url
```
https://example.com/projec%E2%80%8Bts/PROJ/repos/some-repo/pull-requests/2
```
Google says E2 80 8B is a zero-width-space.

![url-from-build-description](https://cloud.githubusercontent.com/assets/5917898/10990266/7666db42-847b-11e5-8052-570714c26046.png)

**Comment by tomasbjerre** [comment]
What if you create a shell build step and just "echo $VARIABLE" in you build job. What does it output?

**Comment by eratolekov** [comment]
I'll try to do it on monday

**Comment by eratolekov** [comment]
Hi Tomas

echo $VARIABLE (or echo %VARIABLE% for windows batch) return empty value.

We are using [EnvInject Plugin](https://wiki.jenkins-ci.org/display/JENKINS/EnvInject+Plugin). There is no VARIABLE environment variable in the list of envs of the build. (available on url ```https://jenkins.instance/job/Example-Job/57/injectedEnvVars/```)
