### ISSUE TITLE
Parameterized Jenkins' job error

### ISSUE THREAD

**Issue by eratolekov** [tomasbjerre/pull-request-notifier-for-bitbucket#84]
Hi Tomas

Jenkins' job has active setting _This build is parameterized_. There is one string parameter. The parameter has some default value.

When this job starts manually or from [Stash Webhook](https://marketplace.atlassian.com/plugins/com.nerdwin15.stash-stash-webhook-jenkins) or from git poll timer, this parameter is initialized by correct default value.

When this job starts from [PR Notifier for Stash](https://marketplace.atlassian.com/plugins/se.bjurr.prnfs.pull-request-notifier-for-stash), this parameter is absent in list of environment variables of build. And this breaks the build.

**Comment by tomasbjerre** [comment]
If Stash Webhook does this, I think it should be here somewhere:
https://github.com/Nerdwin15/stash-jenkins-postreceive-webhook/blob/master/src/main/java/com/nerdwin15/stash/webhook/Notifier.java
But I cannot see that it does something like that.

The plugin just invokes the URL, as described here:
https://wiki.jenkins-ci.org/display/JENKINS/Parameterized+Build

And I dont see anything there about retrieving default values.
