### ISSUE TITLE
Trigger Button User

### ISSUE THREAD

**Issue by praqmaTim** [tomasbjerre/pull-request-notifier-for-bitbucket#85]
It would be really great if we could pass the user who pushed the trigger button to Jenkins. Something Like {PULL_REQUEST_TRIGGER_BUTTON_AUTHOR} or some such. We have Jenkins jobs that do a pre-merge, build execution and if successful pushes the merge back to stash. So we are gating the integration branch and it would be great if we could identify who integrated the changes from a pull request in Jenkins.

Additionally we would really like to have these changes avaialable on pull-request-notifier-for-stash if possible as we can't presently upgrade to bitbucket server version.

**Comment by tomasbjerre** [comment]
There are:
${PULL_REQUEST_USER_DISPLAY_NAME} The one pushing the button.
${PULL_REQUEST_AUTHOR_DISPLAY_NAME} The one who created the PR.

Open issue again if they dont resolve correctly!
