### ISSUE TITLE
No notification sent on pull request update

### ISSUE THREAD

**Issue by nikolaykolev** [tomasbjerre/pull-request-notifier-for-bitbucket#86]
When a pull request is opened once and than updated (new commit, squash or whatever) there is no notification sent while it is enabled for "UPDATED" property. If I can provide more data tell me, for now I don't know what info can be usefull? I have checked reopened, opened, button_trigger and updated. All work except when updated.

**Comment by tomasbjerre** [comment]
Update happens when title of pr is changed. What you want is rescoped :)

**Comment by tomasbjerre** [comment]
Open issue again if rescoped does not work for you!

**Comment by nikolaykolev** [comment]
oh ... sorry ... didn't know that .. thanks a lot!
