### ISSUE TITLE
Trigger build button not shown in IE11

### ISSUE THREAD

**Issue by marcelleke** [tomasbjerre/pull-request-notifier-for-bitbucket#87]
I'm using Bitbucket server version 4.0.1
And pull-request-notifier-for-bitbucket version 2.12

In Internet Explorer 11 the trigger build button is not shown.
In Firefox it is working fine.

**Comment by marcelleke** [comment]
It seems it working file now, I'm using IE 11.0.9600.18097

If there are no other users with this problem, the issue may be closed.

**Comment by tomasbjerre** [comment]
Ok, I don't have any Windows installation to test this on so that is nice =)
