### ISSUE TITLE
Can not use any trigger other than BUTTON_TRIGGER when used a customized button for a repo

### ISSUE THREAD

**Issue by s-afroz** [tomasbjerre/pull-request-notifier-for-bitbucket#88]
I would like to perform different actions for different repos. For example, I want to display trigger builds for some repos while do a build-and-deploy for some other repos. In each case, these actions will be performed as soon as the pull request is open/re-open/re-scoped or the specific trigger button is clicked from within the pull request by an admin. We launch a Jenkins job with specific parameters for each repo.

In order to achieve this, I need to 
(1) Display "Trigger Build" for some repos and "Build and Deploy" for some other repos. It was possible by following the helpful suggestions from Thomas as below.
        1. Add the button and name it "Build and Deploy"
        2. Add a trigger
        3. filter text: ${PULL_REQUEST_FROM_REPO_NAME}-${BUTTON_TRIGGER_TITLE}
        4. filter regexp: name of repo, like "rep_1-Build and Deploy"
        5. Configure the URL and anything else you want to occur when button is pressed.
(2) Enable multiple trigger check boxes in the same trigger configuration.
      OPEN, RE-OPEN, BUTTON-TRIGGER

Item (2) is not possible at the moment along with item (1). Meaning, if I use the filters as described and enable OPEN, RE-OPEN, and BUTTON_TRIGGER check boxes, opening or re-opening a pull request for that repo does not trigger the job. Only clicking on the button from the pull request triggers the job. To get around this issue, I have to create 2 triggers for each repo, one with the button title in the filter and the other without it.

Would be nice if we could use one trigger to achieve both.

**Comment by tomasbjerre** [comment]
Perhaps this filter regexp will work for you?

`rep_1-(Build and Deploy)?$`

https://jex.im/regulex/#!embed=false&flags=&re=rep_1-(Build%20and%20Deploy)%3F%24

The ${BUTTON_TRIGGER_TITLE} will evaluate to empty if its not a button trigger event. So this regexp will match rep_1- when open/re-open/re-scoped and rep_1-Build and Deploy when button pressed.

**Comment by s-afroz** [comment]
Thanks Tomas. It did what I wanted it to do.
