### ISSUE TITLE
PULL_REQUEST_TO_SSH_CLONE_URL sometimes does not have the full URL

### ISSUE THREAD

**Issue by s-afroz** [tomasbjerre/pull-request-notifier-for-bitbucket#89]
We observed that this parameter sometimes have full URL, and sometimes short URL. In the beginning we had a very restrictive regexp that matched the full name against this parameter to trigger the job. We noticed that, sometimes the build job was not triggered (about 10-20%). After making the regexp more forgiving, the trigger was happening 100% of time. But, the failure is now occurring during "git clone" step in the form of "Host key verification failed". 

When it fails, PULL_REQUEST_TO_SSH_CLONE_URL has following value:
ssh://git@xxxxxxx:7999/xxxx/xxxxx.git

And, when it passes, it has
ssh://git@xxxxxxx-stash.global.xxxxxx.net:7999/xxxx/xxxxx.git

Our build server is not able to use the short form of the stash URL.

One observation is, every time it fails, it failed from the automatic trigger criteria (OPEN). After seeing the failure, if I go and trigger the build from the BUTTON_TRIGGER, it passes. Did not try to do RE-OPEN after the failure.

**Comment by tomasbjerre** [comment]
Which version of Stash do you use?

**Comment by s-afroz** [comment]
Stash: v3.8.0, PullReqNotifier: 1.37.

**Comment by s-afroz** [comment]
More Info: The pull request author used the short form of the bitbucket server when creating the pull request. We used a workaround in the jenkins job to add the domain name at the end of the bitbucket server address in such cases.
