### ISSUE TITLE
Add an option to ignore certificates

### ISSUE THREAD

**Issue by itay** [tomasbjerre/pull-request-notifier-for-bitbucket#90]
Java and SSL certificates is a giant pain. Specifically, Java can sometimes reject totally valid certs because it has SNI enabled, or it decides it doesn't like the issuer, etc.

Can we add an option to ignore all certificate errors? You can see an example of doing this here:
https://github.com/Nerdwin15/stash-jenkins-postreceive-webhook/blob/master/src/main/java/com/nerdwin15/stash/webhook/service/ConcreteHttpClientFactory.java#L43

It would be super useful, and mean we don't need to worry about SSL if everything is in the internal network and it is using trusted servers.

**Comment by itay** [comment]
@tomasbjerre any thoughts on this? :)

**Comment by tomasbjerre** [comment]
I like the feature. But the referenced sample code is using alot of depricated api:s. So I did not want to copy that code.

**Comment by tomasbjerre** [comment]
Came across this, should be useful to look at when implementing this.
https://github.com/Nerdwin15/stash-jenkins-postreceive-webhook/pull/130

**Comment by tomasbjerre** [comment]
@itay  can you try this build:
https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/releases/tag/untagged-1a2f2f6cf881f170c521

If it works for you, I'll release it to Marketplace.

**Comment by tomasbjerre** [comment]
The feature is added, open issue again if its not working =)

**Comment by itay** [comment]
@tomasbjerre I'll try and do verification today/tomorrow - I need to bring up a dev environment to do that.

**Comment by tomasbjerre** [comment]
This is now in 2.13 https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/releases/tag/pull-request-notifier-for-bitbucket-2.13
