### ISSUE TITLE
Change multiple buttons to be in a dropdown

### ISSUE THREAD

**Issue by itay** [tomasbjerre/pull-request-notifier-for-bitbucket#91]
We use multiple buttons for causing different automations to happen, and it's becoming a little bit unwieldy as they are all just in one line.

It would be great if they could be in one dropdown-y thing, where you can just select which action you want to trigger.

**Comment by tomasbjerre** [comment]
Thanks! Very nice. I merged it now. Also added sorting of the buttons. I will release it now.
