### ISSUE TITLE
Get reviewers of pr

### ISSUE THREAD

**Issue by zhang6464** [tomasbjerre/pull-request-notifier-for-bitbucket#93]
Is there any attribute for reviewers?
I wanna send a sms to reviewers about the pr info, how could I get the reviewer list plz?

**Comment by tomasbjerre** [comment]
Perhaps by adding a variable containing comma separated list of reviewers?
I saw your fork, will you work on a pr for this?

**Comment by zhang6464** [comment]
@tomasbjerre ye, I have done that, but has a bit difficult in starting the project with commands below
```
export MAVEN_OPTS=-Dplugin.resource.directories=`pwd`/src/main/resources
mvn bitbucket:run
```
Some maven packages can't be installed. I'm in China, something is blocked I guess...

**Comment by tomasbjerre** [comment]
Did you have a look at the .travis.yml file?
Den 25 jan 2016 09:42 skrev "zhang meng" <notifications@github.com>:

**Comment by zhang6464** [comment]
Just network error, now is OK.
I'll post a pr for this, code review is really welcome, I'm not familiar with java...

**Comment by tomasbjerre** [comment]
Nice, thanks!

**Comment by zhang6464** [comment]
I saw that travis building is done.
And when will the package update on atlassian marketplace after pr merged?

**Comment by tomasbjerre** [comment]
Perhaps later today. I would like to have @itay comment on #90 first since that will also be included in the release.

You may update your PR with README.md and CHANGELOG.md. Or I will do that also later today.

**Comment by zhang6464** [comment]
okay, I'll update my .md files.

**Comment by tomasbjerre** [comment]
PR is merged
